"""Put a generated SDK header in front of a real C++ compiler.

    py tools/verify/compile_sdk_header.py

WHY THIS EXISTS
  The SDK-header export shipped for months emitting `uint8_t[0x40] CellBounds;` for every
  OptionalProperty and every unresolved StructProperty -- the array extent BEFORE the identifier,
  which is not valid C++. A real 75,342-line export carried 5 of them, so the whole header was
  uncompilable. The emitters were unit-covered the entire time; what no check in this repo did was
  COMPILE the artifact. Reading a header only proves it parses the way you already assumed.

WHAT IT COMPILES
  `out/sdk-smoke/sdk_smoke.cpp`, written by SdkHeaderDeclaratorTests during `dotnet test`. It is
  the real emitter's output for a fixture covering both raw-byte fallbacks, a resolved struct,
  containers, pointers, an enum, a packed bitfield run, interior padding and tail padding, plus a
  self-contained stub prelude -- so it includes NOTHING and needs no VS dev shell.

FAILING LOUDLY (working-lessons Sec.1)
  Every way this can not-run is an error, never a pass:
    * artifact missing        -> run `dotnet test` first
    * artifact older than SdkExportService.cs -> stale, regenerate
    * no MSVC found           -> nothing was compiled, so nothing was proven
  A green run means cl.exe accepted the generated declarations.

Exit 0 = the header compiles. Anything else = it does not, or could not be checked.
"""
import argparse
import os
import pathlib
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
ARTIFACT = REPO / "out" / "sdk-smoke" / "sdk_smoke.cpp"
EMITTER = REPO / "ui" / "UE5DumpUI" / "Services" / "SdkExportService.cs"


def fail(msg):
    print("COMPILE SMOKE FAILED: %s" % msg)
    return 1


def find_cl():
    """Locate cl.exe. Returns (path, source) or (None, reason)."""
    # 1. Already inside a VS dev shell.
    vc = os.environ.get("VCToolsInstallDir")
    if vc:
        cand = pathlib.Path(vc) / "bin" / "Hostx64" / "x64" / "cl.exe"
        if cand.is_file():
            return cand, "VCToolsInstallDir"

    # 2. vswhere -> the default toolset of the newest install.
    for pf in ("ProgramFiles(x86)", "ProgramFiles"):
        base = os.environ.get(pf)
        if not base:
            continue
        vswhere = pathlib.Path(base) / "Microsoft Visual Studio" / "Installer" / "vswhere.exe"
        if not vswhere.is_file():
            continue
        try:
            out = subprocess.run(
                # Filter identical to build.ps1 and build_dll.py -- see the note in
                # build.ps1's VS-selection block. They share one build/ directory.
                [str(vswhere), "-latest", "-products", "*", "-prerelease",
                 "-requires", "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
                 "-property", "installationPath"],
                capture_output=True, text=True, timeout=60)
        except (OSError, subprocess.SubprocessError) as e:
            return None, "vswhere failed: %s" % e
        install = out.stdout.strip().splitlines()
        if not install:
            continue
        root = pathlib.Path(install[0])
        ver_file = root / "VC" / "Auxiliary" / "Build" / "Microsoft.VCToolsVersion.default.txt"
        if not ver_file.is_file():
            continue
        ver = ver_file.read_text(encoding="utf-8").strip()
        cand = root / "VC" / "Tools" / "MSVC" / ver / "bin" / "Hostx64" / "x64" / "cl.exe"
        if cand.is_file():
            return cand, "vswhere (%s)" % ver

    return None, "no MSVC x64 toolset found (VCToolsInstallDir unset, vswhere found nothing)"


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--file", default=str(ARTIFACT),
                    help="translation unit to compile (default: the test-written artifact)")
    ap.add_argument("--allow-stale", action="store_true",
                    help="skip the 'artifact older than the emitter' guard")
    args = ap.parse_args()

    # Absolute: /Zs writes nothing, but cl.exe still resolves the source against ITS cwd, and a
    # relative path silently became "C1083: No such file" -- which reads exactly like a compile
    # failure. A rig that reports the wrong failure is worse than one that reports none.
    src = pathlib.Path(args.file).resolve()
    if not src.is_file():
        return fail("%s does not exist.\n"
                    "  It is written by SdkHeaderDeclaratorTests. Run:\n"
                    "    dotnet test \"ui/UE5DumpUI.Tests/UE5DumpUI.Tests.csproj\" -c Release" % src)

    if not args.allow_stale and EMITTER.is_file():
        if src.stat().st_mtime < EMITTER.stat().st_mtime:
            return fail("%s is OLDER than %s.\n"
                        "  It was generated by a previous version of the emitter, so compiling it\n"
                        "  says nothing about the code you just changed. Re-run dotnet test."
                        % (src.name, EMITTER.name))

    cl, how = find_cl()
    if cl is None:
        return fail("%s.\n"
                    "  Nothing was compiled, so nothing was proven. Install the VS C++ workload,\n"
                    "  or run this from a Visual Studio developer shell." % how)

    print("compiler : %s  (%s)" % (cl, how))
    print("source   : %s  (%d bytes)" % (src, src.stat().st_size))

    env = dict(os.environ)
    # cl.exe loads c1.dll / c1xx.dll / c2.dll from its own directory.
    env["PATH"] = str(cl.parent) + os.pathsep + env.get("PATH", "")

    # /Zs = syntax check only: full front-end parse, no object file, no linker, no INCLUDE needed
    # (the artifact deliberately includes nothing). /permissive- turns on conforming lookup.
    # /utf-8 because a real game's identifiers are not guaranteed ASCII and the default source
    # charset is the machine's ANSI codepage (950 here), which would raise C4819 on a valid file.
    cmd = [str(cl), "/nologo", "/Zs", "/TP", "/permissive-", "/W3", "/EHsc", "/utf-8", str(src)]
    print("command  : %s" % " ".join(cmd[1:]))
    try:
        res = subprocess.run(cmd, capture_output=True, text=True, env=env, timeout=300)
    except (OSError, subprocess.SubprocessError) as e:
        return fail("could not run cl.exe: %s" % e)

    output = (res.stdout + res.stderr).strip()
    if output:
        print("--- cl.exe output ---")
        print(output)
        print("---------------------")

    if res.returncode != 0:
        return fail("cl.exe exited %d -- the generated header does NOT compile." % res.returncode)

    # A warning is not a failure here, but it should be visible rather than buried.
    warned = [l for l in output.splitlines() if ": warning " in l]
    if warned:
        print("NOTE: %d compiler warning(s) above; the header still compiles." % len(warned))

    print("COMPILE SMOKE OK: the generated SDK header compiles.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
