r"""SDKHDR step 5: compile the OptionalProperty-owning structs from a REAL exported SDK header.

    py tools/verify/sdkhdr_step5.py [--header out/DumperTest_SDK.h]

WHY THIS IS NOT compile_sdk_header.py
    That rig compiles `out/sdk-smoke/sdk_smoke.cpp`, which the C# tests generate from a FIXTURE.
    It proves the emitter's declarator shape is valid C++. Step 5 asks a different question: take
    the structs that actually own the `OptionalProperty` members **out of a real 75,342-line
    export** and put those bytes in front of cl.exe. A fixture cannot answer that, because the
    fixture is not the artifact the user ends up with.

WHAT IT DOES
    1. finds every line in the header carrying `OptionalProperty`;
    2. extracts the whole top-level `struct`/`class` block that owns each one, VERBATIM;
    3. reuses the stub prelude already at the top of `out/sdk-smoke/sdk_smoke.cpp` (primitives,
       containers, a few engine bases) -- nothing is invented that the repo does not already ship;
    4. emits `struct <Name> {};` forward stubs for any type the excerpt references and the prelude
       does not declare -- base classes especially. The excerpted DECLARATIONS are never rewritten,
       only surrounded, so what cl.exe sees is the real emitter's text.
    5. compiles with `cl /Zs /TP /permissive- /utf-8` (syntax-only, no link, no dev shell needed).

SCOPE, per the row's own warning: this is an EXCERPT on purpose. `GenerateFullSdkAsync` emits
classes in GObjects order with no topological sort, so the whole header very likely does not
compile as one translation unit for reasons that have nothing to do with this defect. A failure
here is only meaningful if it is a syntax error at a `[`.

FAILING LOUDLY: a missing header, a missing prelude, zero OptionalProperty owners found, or no
MSVC are all errors -- never a pass. Zero owners in particular would make the whole check vacuous.
"""
import argparse
import pathlib
import re
import subprocess
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from compile_sdk_header import find_cl  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[2]
PRELUDE_MARKER = "// Auto-generated by UE5CEDumper"


def say(s):
    enc = sys.stdout.encoding or "utf-8"
    sys.stdout.write(s.encode(enc, "replace").decode(enc, "replace") + "\n")


def owner_blocks(lines, needle):
    """Verbatim top-level struct/class blocks containing `needle`, de-duplicated."""
    opens = [i for i, l in enumerate(lines) if re.match(r'^(struct|class)\s+\w+', l)]
    blocks, seen = [], set()
    for idx, l in enumerate(lines):
        if needle not in l:
            continue
        start = max((o for o in opens if o < idx), default=None)
        if start is None:
            continue
        end = start
        while end < len(lines) and not lines[end].startswith("};"):
            end += 1
        if start in seen:
            continue
        seen.add(start)
        blocks.append((start, end, lines[start:end + 1]))
    return blocks


def referenced_types(block_lines):
    out = set()
    for l in block_lines:
        l = l.split("//")[0]
        m = re.match(r'^(?:struct|class)\s+\w+\s*:\s*public\s+(\w+)', l)
        if m:
            out.add(m.group(1))
        for m in re.finditer(r'\b(?:struct|class|enum class)\s+(\w+)\s*[\*&]?\s+\w+\s*;', l):
            out.add(m.group(1))
        for m in re.finditer(r'\b(?:TArray|TSet|TSubclassOf|TWeakObjectPtr|TSoftObjectPtr|'
                             r'TSoftClassPtr|TLazyObjectPtr|TScriptInterface)\s*<\s*(?:class\s+|struct\s+)?'
                             r'(\w+)', l):
            out.add(m.group(1))
        for m in re.finditer(r'\bTMap\s*<\s*(?:class\s+|struct\s+)?(\w+)\s*,\s*'
                             r'(?:class\s+|struct\s+)?(\w+)', l):
            out.add(m.group(1)); out.add(m.group(2))
        # Bare `TypeName MemberName;` -- the form an enum member takes, with no
        # struct/class keyword in front of it. Missing this is what made the first
        # run stop on `EDumperTestGrade Grade;` with C3646, which reads like a
        # header defect and is not one.
        m = re.match(r'^\s*([A-Za-z_]\w*)\s+[A-Za-z_]\w*\s*(?::\s*\d+\s*)?;\s*$', l)
        if m:
            out.add(m.group(1))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--header", default="out/DumperTest_SDK.h")
    ap.add_argument("--negative-control", action="store_true",
                    help="rewrite each OptionalProperty line back to the PRE-FIX spelling "
                         "(extent before the identifier) and expect cl to REJECT it. A run that "
                         "cannot be made to fail has not shown the compiler is looking.")
    a = ap.parse_args()

    hdr = ROOT / a.header
    smoke = ROOT / "out" / "sdk-smoke" / "sdk_smoke.cpp"
    if not hdr.is_file():
        say("FAIL: header not found: %s -- export one from the UI first" % hdr)
        return 1
    if not smoke.is_file():
        say("FAIL: %s missing -- run `dotnet test` to regenerate the prelude" % smoke)
        return 1

    lines = hdr.read_text(encoding="utf-8", errors="replace").splitlines()
    say("header : %s (%d bytes, %d lines)" % (hdr.name, hdr.stat().st_size, len(lines)))

    blocks = owner_blocks(lines, "OptionalProperty")
    if not blocks:
        say("FAIL: no OptionalProperty owner found -- this check would be VACUOUS, not a pass")
        return 1
    say("OptionalProperty owners: %d" % len(blocks))
    for s, e, b in blocks:
        say("   %-46s lines %d..%d (%d)" % (b[0][:46], s + 1, e + 1, e - s + 1))

    smoke_txt = smoke.read_text(encoding="utf-8", errors="replace")
    cut = smoke_txt.find(PRELUDE_MARKER)
    if cut < 0:
        say("FAIL: prelude marker not found in %s" % smoke.name)
        return 1
    prelude = smoke_txt[:cut]

    declared = set(re.findall(r'^(?:struct|class)\s+(\w+)', prelude, re.M))
    declared |= set(re.findall(r'^enum class\s+(\w+)', prelude, re.M))
    declared |= {"uint8_t", "int8_t", "int16_t", "uint16_t", "int32_t", "uint32_t",
                 "int64_t", "uint64_t", "float", "double", "bool", "void", "char"}
    for _, _, b in blocks:
        m = re.match(r'^(?:struct|class)\s+(\w+)', b[0])
        if m:
            declared.add(m.group(1))

    need = set()
    for _, _, b in blocks:
        need |= referenced_types(b)
    stubs = sorted(t for t in need if t not in declared)
    say("forward stubs added for undeclared types: %d  %s" % (len(stubs), stubs))

    body = [prelude,
            "// ---- forward stubs (types the excerpt references, not in the prelude) ----"]
    body += ["struct %s { void* _stub; };" % t for t in stubs]
    body.append("")
    body.append("// ---- VERBATIM excerpt from %s ----" % hdr.name)
    flipped = 0
    for _, _, b in blocks:
        bb = list(b)
        if a.negative_control:
            for i, l in enumerate(bb):
                m = re.match(r'^(\s*)(\w+)\s+(\w+)(\[0x[0-9A-Fa-f]+\]);(.*OptionalProperty.*)$', l)
                if m:
                    # pre-fix spelling: the extent baked into the TYPE, before the identifier
                    bb[i] = "%s%s%s %s;%s" % (m.group(1), m.group(2), m.group(4), m.group(3), m.group(5))
                    flipped += 1
        body += bb + [""]
    if a.negative_control:
        say("NEGATIVE CONTROL: rewrote %d declaration(s) to the pre-fix spelling" % flipped)
        if flipped == 0:
            say("FAIL: nothing to flip -- the control cannot run")
            return 1
    out = ROOT / "out" / "sdk-smoke" / "real_excerpt.cpp"
    out.write_text("\n".join(body), encoding="utf-8")
    say("wrote %s (%d lines)" % (out, len(body)))

    cl, src = find_cl()
    if cl is None:
        say("FAIL: no MSVC found (%s) -- nothing was compiled, so nothing was proven" % src)
        return 1
    say("cl.exe : %s   [%s]" % (cl, src))

    r = subprocess.run([str(cl), "/nologo", "/Zs", "/TP", "/permissive-", "/utf-8", str(out)],
                       capture_output=True, text=True, errors="replace", cwd=str(out.parent))
    say("")
    say("cl exit code: %d   <-- must be 0" % r.returncode)
    tail = (r.stdout + r.stderr).strip().splitlines()
    for l in tail[:30]:
        say("   " + l[:150])
    if a.negative_control:
        say("")
        if r.returncode != 0 and "C2059" in (r.stdout + r.stderr):
            say("PASS (control): cl REJECTS the pre-fix spelling with C2059 -- the check can fail.")
            return 0
        say("FAIL (control): the pre-fix spelling was accepted, or failed for the wrong reason.")
        return 1
    if r.returncode == 0:
        say("")
        say("PASS: the real export's OptionalProperty owners compile.")
    return r.returncode


if __name__ == "__main__":
    sys.exit(main())
