using System.Globalization;
using System.Text;
using UE5DumpUI.Models;

namespace UE5DumpUI.Services;

/// <summary>
/// Generates a non-interactive CE AA Script that invokes a UFunction with
/// pre-baked argument values. Designed for redistribution as part of a
/// Cheat Engine table -- the user enables the script and the function
/// fires once with the baked values, no UI interaction needed.
///
/// The generated script depends on <c>ue5_invoke_helper.lua</c> being
/// embedded in the same .CT via Table -> Add File... (see
/// <see cref="HelperFileResource"/> for the export action). At runtime the
/// script uses <c>findTableFile</c> to locate the helper and calls
/// <c>invokeUFunction</c> with the baked params table.
///
/// Sister to <see cref="InvokeScriptGenerator"/>:
/// <list type="bullet">
/// <item>InvokeScriptGenerator builds an in-CE form so the user fills
///     values at runtime in CE.</item>
/// <item>BakedScriptGenerator inlines the values at generation time and
///     produces a script ~5x smaller; the user fills values in the
///     UE5DumpUI dialog, then ships a static AA Script.</item>
/// </list>
/// Both use single-quoted Lua strings so the output transmits cleanly
/// through the AOBMaker JSON pipe.
/// </summary>
public static class BakedScriptGenerator
{
    /// <summary>Stable name of the embedded helper file the generated
    /// script will look up via <c>findTableFile</c>.</summary>
    public const string HelperFileName = "ue5_invoke_helper.lua";

    /// <summary>
    /// Generate a complete CE AA Script that invokes <paramref name="funcName"/>
    /// on a live instance of <paramref name="className"/> with the supplied
    /// baked parameter values.
    /// </summary>
    /// <param name="className">UClass name (e.g. "PlayerCharacter"). The
    ///     helper's CMD_INVOKE_BY_NAME path will <c>findInstance</c> live
    ///     non-CDO objects matching this name.</param>
    /// <param name="funcName">UFunction name (e.g. "AddMoney").</param>
    /// <param name="parmsSize">Total size of the function's params buffer
    ///     in bytes. The helper zero-fills this range before writing baked
    ///     values, so unsupplied params (e.g. return slot) start clean.</param>
    /// <param name="bakedValues">Param values to write. Pass an empty list
    ///     for void-return / no-arg functions; the generator will still
    ///     emit a clean invoke call.</param>
    /// <returns>A self-contained AA Script string with [ENABLE]/[DISABLE]
    ///     blocks. Trailing LF only (no CR) for CE compatibility.</returns>
    public static string Generate(
        string className,
        string funcName,
        int parmsSize,
        IReadOnlyList<BakedParamValue> bakedValues,
        BakedParamValue? returnParam = null,
        bool verifyReturn = false)
    {
        var sb = new StringBuilder(4096);

        Line(sb, "[ENABLE]");
        Line(sb, "{$lua}");
        Line(sb, "if syntaxcheck then return end");
        CeLuaHygiene.AppendDebugPreamble(sb);
        Line(sb, "-- ================================================================");
        Line(sb, $"-- UFunction Invoker (baked args): {className}::{funcName}");
        Line(sb, $"-- Generated by UE5CEDumper | {CeLuaHygiene.AttributionUrl}");
        Line(sb, "--");
        Line(sb, "-- REQUIREMENT: ue5_invoke_helper.lua MUST be embedded in this");
        Line(sb, "-- table via 'Table -> Add File...' (one-time setup per .CT).");
        Line(sb, "-- Get the file from UE5DumpUI: Tools -> Export CE Helper Lua File...");
        Line(sb, "-- ================================================================");
        Line(sb);

        // Helper loader -- no filesystem fallback; explicit error on missing.
        AppendHelperLoader(sb);

        // Baked params table (or empty marker for no-arg functions)
        AppendBakedParamsTable(sb, bakedValues);

        // Invoke + result handling (silent on success, print + showMessage on error;
        // when verifyReturn is set, emits a diagnostic block instead).
        AppendInvokeAndResultHandler(sb, className, funcName, parmsSize,
                                     returnParam, verifyReturn);

        // Auto-disable + close lua engine on success (your hygiene rule).
        // Verify-return mode keeps the engine open so the diagnostic print
        // remains readable -- the close branch is conditionally suppressed.
        AppendCleanupAndClose(sb, keepEngineOpen: verifyReturn);

        Line(sb, "{$asm}");
        Line(sb, "[DISABLE]");
        Line(sb, "{$lua}");
        Line(sb, "-- nop");
        Line(sb, "{$asm}");

        return sb.ToString();
    }

    // ------------------------------------------------------------------
    // Section emitters
    // ------------------------------------------------------------------

    /// <summary>Emit the standard "load ue5_invoke_helper.lua from the embedded
    /// table file" preamble (no filesystem fallback). Public so sibling
    /// generators (e.g. <see cref="DebugCameraScriptGenerator"/>) reuse the
    /// exact, proven loader instead of duplicating it.</summary>
    public static void AppendHelperLoader(StringBuilder sb)
    {
        Line(sb, "-- Load helper from embedded table file (NO filesystem fallback)");
        Line(sb, $"local tf = findTableFile('{HelperFileName}')");
        Line(sb, "if not tf then");
        Line(sb, "  showMessage(");
        Line(sb, $"    '[Invoke] {HelperFileName} not found in this table.\\n\\n' ..");
        Line(sb, $"    'Setup: Table -> Add File... -> select {HelperFileName}\\n' ..");
        Line(sb, "    '(Export it from UE5DumpUI: Tools -> Export CE Helper Lua File)')");
        Line(sb, "  if memrec then memrec.Active = false end");
        Line(sb, "  return");
        Line(sb, "end");
        Line(sb, "do");
        Line(sb, "  local ss = createStringStream()");
        Line(sb, "  ss.copyFrom(tf.Stream, tf.Stream.Size)");
        Line(sb, "  local fn, err = load(ss.DataString)");
        Line(sb, "  ss.destroy()");
        Line(sb, "  if not fn then");
        Line(sb, "    showMessage('[Invoke] Helper load error:\\n' .. tostring(err))");
        Line(sb, "    if memrec then memrec.Active = false end");
        Line(sb, "    return");
        Line(sb, "  end");
        Line(sb, "  fn()");
        Line(sb, "end");
        Line(sb);
    }

    private static void AppendBakedParamsTable(
        StringBuilder sb, IReadOnlyList<BakedParamValue> values)
    {
        if (values.Count == 0)
        {
            Line(sb, "-- (no input params -- direct invoke)");
            Line(sb, "local PARAMS = {}");
            Line(sb);
            return;
        }

        Line(sb, "-- ====== BAKED PARAMS (edit values here) ==============================");
        Line(sb, "local PARAMS = {");
        foreach (var v in values)
        {
            // Input path uses MapInputType so string params keep their wide/
            // narrow distinction ('fstring' vs 'fstringn') the helper needs.
            // v.Size was in hand here the whole time and used only by the 'fstruct'
            // arm below; an EnumProperty needs it too or it is written as 4 bytes
            // over the next param (audit #5 Y16 site 2).
            var helperType = MapInputType(v.UeTypeName, v.Size);
            var literal = RenderLiteral(v.UeTypeName, v.LiteralText);
            // By-value struct ('fstruct'): emit the exact byte size so the
            // helper zeroes the right region instead of falling back to its
            // fragile next-offset-difference heuristic (the params list is in
            // declaration order, not sorted by offset).
            var sizeField = helperType == "fstruct" ? $"size={v.Size}, " : "";
            // Each row: { name='...', type='...', offset=N, [size=N,] value=LITERAL },  -- shortType
            Line(sb,
                $"  {{ name='{EscapeLua(v.ParamName)}', type='{helperType}', " +
                $"offset={v.Offset}, {sizeField}value={literal} }},  " +
                $"-- {ShortTypeNameForComment(v.UeTypeName, v.Size)} {v.Size}B");
        }
        Line(sb, "}");
        Line(sb, "-- =====================================================================");
        Line(sb);
    }

    private static void AppendInvokeAndResultHandler(
        StringBuilder sb, string className, string funcName, int parmsSize,
        BakedParamValue? returnParam, bool verifyReturn)
    {
        // Verify mode: emit a Before/After raw-byte dump around the invoke
        // so the user can distinguish "function didn't run" (After == Before)
        // from "wrong return offset" (return value lands somewhere else).
        // The dump covers the smaller of (parmsSize, 32) bytes -- enough for
        // typical 1-2 input + 1 return functions without flooding the output.
        if (verifyReturn)
        {
            Line(sb, "-- ====== Verify mode: dump params buffer + decoded return ======");
            Line(sb, "-- Resolve mailbox via getAddressSafe + module-prefixed fallback,");
            Line(sb, "-- mirroring the helper's findMailbox(). Bare getAddress() is fine");
            Line(sb, "-- in some setups but throws / returns garbage in others when CE's");
            Line(sb, "-- symbol resolver only registers the prefixed form -- without this");
            Line(sb, "-- guard the dump call would later hit string.format with nil.");
            Line(sb, "local _mb_dbg = (function()");
            Line(sb, "  local a = getAddressSafe('g_invokeMailbox')");
            Line(sb, "  if not a or a == 0 then a = getAddressSafe('UE5Dumper.g_invokeMailbox') end");
            Line(sb, "  return a or 0");
            Line(sb, "end)()");
            Line(sb, $"local _PD_dbg = _mb_dbg + (UE5_INVOKE_PARAMS_OFFSET or 0x328)");
            int dumpLen = Math.Max(8, Math.Min(parmsSize, 32));
            Line(sb, $"local _DUMP_LEN = {dumpLen}  -- min(parmsSize, 32)");
            Line(sb, "local function _dumpHex(label)");
            Line(sb, "  if _mb_dbg == 0 then");
            Line(sb, "    print(label .. ': <mailbox unresolved -- is UE5Dumper.dll injected?>')");
            Line(sb, "    return");
            Line(sb, "  end");
            Line(sb, "  local s = label .. ': '");
            Line(sb, "  for i = 0, _DUMP_LEN - 1 do");
            // `or 0` keeps the dump alive even if readByte returns nil for a
            // single byte (e.g. half-page boundary on a tiny region) -- shows
            // 00 instead of crashing the whole script.
            Line(sb, "    s = s .. string.format('%02X ', readByte(_PD_dbg + i) or 0)");
            Line(sb, "  end");
            Line(sb, "  print(s)");
            Line(sb, "end");
            // Wipe the params buffer to parmsSize BEFORE the Before dump.
            // The mailbox is a single shared buffer reused across every
            // invoke in this CE session -- the DLL has no clean transition
            // point to zero it after a call (would race with Lua reading
            // the return value), and the helper's writeBakedParams zero
            // happens AFTER this dump. Without this pre-zero, the Before
            // dump shows leftover bytes from the previous invoke (e.g.
            // ES2 / Geri 2026-05-11 test: scen 2's Before showed scen 1's
            // [3, 4, 7] payload). Pre-zeroing here makes Before always
            // appear clean, so Before vs After unambiguously isolates
            // what THIS invoke wrote.
            Line(sb, "if _mb_dbg ~= 0 then");
            Line(sb, $"  for i = 0, {parmsSize} - 1 do writeByte(_PD_dbg + i, 0) end");
            Line(sb, "end");
            Line(sb, "_dumpHex('[Invoke] Before')");
            Line(sb);
        }

        Line(sb, verifyReturn
            ? "-- Invoke (verify mode -- prints decoded return value on success)"
            : "-- Invoke (silent on success -- only prints/showMessage on error)");
        Line(sb,
            $"local ok, err = invokeUFunction('{EscapeLua(className)}', " +
            $"'{EscapeLua(funcName)}', {parmsSize}, PARAMS)");

        if (verifyReturn)
        {
            Line(sb, "_dumpHex('[Invoke] After ')");
            Line(sb, "if ok then");
            if (returnParam != null)
            {
                var displayType = MapToHelperType(returnParam.UeTypeName, returnParam.Size);
                // The helper's readUFunctionReturn doesn't recognise 'pointer'
                // (defaults to int32 = 4-byte read on the 8-byte pointer slot).
                // Send 'qword' on the wire while showing 'pointer' in the
                // human-readable label so the user still sees the UE-side type.
                var readType = displayType == "pointer" ? "qword" : displayType;
                var fmt = ReturnPrintFormat(returnParam.UeTypeName);

                if (IsComplexReturnType(returnParam.UeTypeName))
                {
                    // FString / FText / TArray / TMap / TSet / FStruct etc. are
                    // multi-byte buffer layouts the helper has no decoder for.
                    // Print just the raw decoded label and tell the user to
                    // read the After: dump for the actual bytes -- still useful
                    // ("ReturnValue is non-zero in the dump → function ran").
                    Line(sb,
                        $"  print('[Invoke] OK: {EscapeLua(className)}::{EscapeLua(funcName)} " +
                        $"-> {EscapeLua(returnParam.ParamName)} ({displayType}@{returnParam.Offset}, " +
                        $"size={returnParam.Size}B) -- complex return; see After: dump above')");
                }
                else
                {
                    Line(sb,
                        $"  local _ret = readUFunctionReturn({returnParam.Offset}, '{readType}')");
                    Line(sb,
                        $"  print(string.format('[Invoke] OK: {EscapeLua(className)}::{EscapeLua(funcName)} " +
                        $"-> {EscapeLua(returnParam.ParamName)} ({displayType}@{returnParam.Offset}) = " +
                        $"{fmt}', _ret))");
                }
            }
            else
            {
                // Void-return: still confirm the call completed.
                Line(sb,
                    $"  print('[Invoke] OK: {EscapeLua(className)}::{EscapeLua(funcName)} " +
                    "(void return)')");
            }
            Line(sb, "else");
            Line(sb, "  print(string.format('[Invoke] FAILED: %s::%s -- %s',");
            Line(sb, $"                      '{EscapeLua(className)}', " +
                      $"'{EscapeLua(funcName)}', tostring(err)))");
            Line(sb, "  showMessage('Invoke failed:\\n' .. tostring(err))");
            Line(sb, "end");
        }
        else
        {
            Line(sb, "if not ok then");
            Line(sb, "  print(string.format('[Invoke] FAILED: %s::%s -- %s',");
            Line(sb, $"                      '{EscapeLua(className)}', " +
                      $"'{EscapeLua(funcName)}', tostring(err)))");
            Line(sb, "  showMessage('Invoke failed:\\n' .. tostring(err))");
            Line(sb, "end");

            // DEBUG-only return-value print (verify mode already prints its own,
            // richer diagnostic, so this only fires in the non-verify path).
            // Quiet by default; when UE5_DEBUG=1 the value is printed and the
            // window is kept open (the success-close is DEBUG==0-gated). The
            // helper's mailbox is resolved here (getAddressSafe + module-prefixed
            // fallback, mirroring findMailbox) so the raw slot can be read.
            if (returnParam != null &&
                returnParam.Offset >= 0 &&
                (parmsSize <= 0 || returnParam.Offset < parmsSize))
            {
                Line(sb, "if ok and DEBUG ~= 0 then");
                Line(sb, "  local _mbret = getAddressSafe('g_invokeMailbox')");
                Line(sb, "  if not _mbret or _mbret == 0 then _mbret = getAddressSafe('UE5Dumper.g_invokeMailbox') end");
                Line(sb, "  if _mbret and _mbret ~= 0 then");
                Line(sb, "    local _PDret = _mbret + (UE5_INVOKE_PARAMS_OFFSET or 0x328)");
                CeInvokeReturn.AppendDecodeAndPrint(sb, className, funcName,
                    returnParam.ParamName, returnParam.UeTypeName,
                    returnParam.Size, returnParam.Offset, "_PDret", "    ");
                Line(sb, "  end");
                Line(sb, "end");
            }
        }
        Line(sb);
    }

    private static void AppendCleanupAndClose(StringBuilder sb, bool keepEngineOpen)
    {
        Line(sb, "-- Auto-disable memrec; on success also close the lua engine window.");
        Line(sb, "-- (Errors leave the window open so you can read the message.)");
        Line(sb, "local t = createTimer(nil, false)");
        Line(sb, "t.Interval = 100");
        Line(sb, "t.OnTimer = function(s)");
        Line(sb, "  s.Enabled = false");
        Line(sb, "  s.destroy()");
        Line(sb, "  if memrec then memrec.Active = false end");
        if (keepEngineOpen)
        {
            // Verify mode: leave the engine window open so the user can
            // read the Before/After dump and the decoded return print.
            Line(sb, "  -- (verify mode: engine window kept open so you can read the diagnostic)");
        }
        else
        {
            // Close on success ONLY when DEBUG is off -- if the user set UE5_DEBUG=1
            // they want the window (and any dbg output) to stay readable.
            Line(sb, "  if ok and DEBUG == 0 then");
            Line(sb, "    synchronize(function() getLuaEngine().Close() end)");
            Line(sb, "  end");
        }
        Line(sb, "end");
        Line(sb, "t.Enabled = true");
        Line(sb);
    }

    /// <summary>
    /// Pick a <c>string.format</c> specifier for the decoded return value
    /// based on UE type. Doubles/floats use <c>%.10g</c> (matches the
    /// diagnostic snippet documented in the dev guide); pointer-shaped
    /// types render as 0x%X; ints render as %d.
    /// </summary>
    private static string ReturnPrintFormat(string ueTypeName) => ueTypeName switch
    {
        "DoubleProperty" or "FloatProperty"           => "%.10g",
        "ObjectProperty" or "ClassProperty" or "NameProperty"
            or "SoftObjectProperty" or "SoftClassProperty"
            or "WeakObjectProperty" or "LazyObjectProperty"
            or "InterfaceProperty" or "UInt64Property" => "0x%X",
        "BoolProperty"                                 => "%d",
        _                                              => "%d",
    };

    // ------------------------------------------------------------------
    // Type + literal helpers
    // ------------------------------------------------------------------

    /// <summary>
    /// Map a UE FProperty type name to the helper-recognised type token
    /// (see <c>writeBakedParams</c> in scripts/ue5_invoke_helper.lua).
    /// </summary>
    /// <remarks>
    /// All pointer-shaped types (object/class/name/soft/weak/lazy/interface/
    /// uint64) collapse to <c>'pointer'</c>; the helper writes them as a
    /// qword. Unrecognised types fall through to <c>'int32'</c> and the
    /// generator stamps a TODO in the literal so the user notices.
    /// </remarks>
    /// <param name="size">
    /// Engine-reported byte width, used ONLY by <c>EnumProperty</c> (audit #5 Y16).
    /// UE sizes an enum by its underlying type -- 1 byte for the common
    /// TEnumAsByte / <c>enum class : uint8</c> -- so the old flat <c>'int32'</c>
    /// wrote 4 bytes and clobbered the next parameter. 0 (the sizeless overload)
    /// keeps the historical 4-byte answer.
    ///
    /// <para>Only enums consult it, deliberately: every other type's width is
    /// implied by its name, and letting <c>size</c> override those would turn a
    /// mis-reported size into a wrong write for types that are currently correct.
    /// <c>MapToHelperTypeIgnoresSizeForEveryTypeButEnum</c> pins that.</para>
    ///
    /// <para>No Lua change is needed: <c>writeBakedParams</c> already accepts the
    /// <c>byte</c> / <c>int16</c> / <c>int64</c> tokens, so nobody has to re-embed
    /// the helper.</para>
    /// </param>
    /// <summary>
    /// Size-less overload. Every type whose width is fixed by its NAME maps
    /// identically; <c>EnumProperty</c> — the one type whose width is not — falls back
    /// to the legacy <c>int32</c>. Callers holding a real param should pass its size.
    /// Same shape as <c>FreezeScriptGenerator.MapToHelperType</c>, which Y15 built.
    /// </summary>
    public static string MapToHelperType(string ueTypeName)
        => MapToHelperType(ueTypeName, 0);

    public static string MapToHelperType(string ueTypeName, int size) => ueTypeName switch
    {
        "BoolProperty"                                => "bool",
        "ByteProperty" or "Int8Property"              => "byte",
        "Int16Property" or "UInt16Property"           => "int16",
        "IntProperty" or "UInt32Property"             => "int32",
        // Whatever the engine reported, never implied by the name -- the same rule
        // ParamBufferBuilder.EffectiveIntWidth already applies on the FIRE path.
        "EnumProperty"                                => size switch
        {
            1 => "byte",
            2 => "int16",
            8 => "int64",
            _ => "int32",
        },
        "Int64Property"                               => "int64",
        "UInt64Property"                              => "pointer",
        "FloatProperty"                               => "float",
        "DoubleProperty"                              => "double",
        "ObjectProperty" or "ClassProperty" or "NameProperty"
            or "SoftObjectProperty" or "SoftClassProperty"
            or "WeakObjectProperty" or "LazyObjectProperty"
            or "InterfaceProperty"                    => "pointer",
        // Complex multi-byte buffer types -- the helper has no scalar
        // decoder for these, so the verify-mode emit treats them as a
        // raw region (size taken from the param) and tells the user to
        // read the After: hex dump. Still better than silently falling
        // through to int32 and reading 4 random bytes.
        // FString + UE5.5+ FUtf8String / FAnsiString: all multi-byte buffer types the
        // helper can't scalar-decode (treated as a raw region → "see hex dump" hint).
        // Without these arms the new variants fall to the int32 default and mis-read 4
        // bytes of the string header.
        "StrProperty" or "Utf8StrProperty" or "AnsiStrProperty" => "fstring",
        "TextProperty"                                => "ftext",
        "ArrayProperty"                               => "tarray",
        "MapProperty"                                 => "tmap",
        "SetProperty"                                 => "tset",
        "StructProperty"                              => "fstruct",
        "DelegateProperty" or "MulticastDelegateProperty"
            or "MulticastInlineDelegateProperty"
            or "MulticastSparseDelegateProperty"      => "delegate",
        _                                             => "int32",
    };

    /// <summary>
    /// Map a UE FProperty type to the helper token used when <b>writing an
    /// input</b> param. Identical to <see cref="MapToHelperType"/> except
    /// string types keep their wide/narrow distinction — <c>StrProperty</c>
    /// stays <c>'fstring'</c> (UTF-16) while <c>Utf8StrProperty</c>/
    /// <c>AnsiStrProperty</c> become <c>'fstringn'</c> (raw bytes) — because
    /// the helper needs it to build the right char buffer. The return-value
    /// path keeps calling <see cref="MapToHelperType"/> (which collapses all
    /// three to <c>'fstring'</c>) so its complex-type classification is
    /// unaffected.
    /// </summary>
    public static string MapInputType(string ueTypeName)
        => MapInputType(ueTypeName, 0);

    /// <summary>Size-aware form — this is the WRITE path, so an enum reaching it with
    /// the wrong width corrupts the next parameter (audit #5 Y16 site 2).</summary>
    public static string MapInputType(string ueTypeName, int size) => ueTypeName switch
    {
        "StrProperty"                          => "fstring",
        "Utf8StrProperty" or "AnsiStrProperty" => "fstringn",
        _                                      => MapToHelperType(ueTypeName, size),
    };

    /// <summary>
    /// True for types the helper's <c>readUFunctionReturn</c> can't decode
    /// as a single scalar -- caller emits a "see hex dump" hint instead
    /// of an actual read+print line. Keeps the diagnostic honest rather
    /// than printing a misleading 4-byte slice of an FString header.
    /// </summary>
    public static bool IsComplexReturnType(string ueTypeName)
    {
        var t = MapToHelperType(ueTypeName);
        return t is "fstring" or "ftext" or "tarray" or "tmap"
                 or "tset" or "fstruct" or "delegate";
    }

    /// <summary>
    /// Render a user-entered text value as a Lua numeric literal, picking
    /// the encoding (decimal int, decimal float, hex) by UE type. Falls
    /// back to a parenthesised raw expression with a TODO comment marker
    /// when parsing fails -- the generator never silently mangles input.
    /// </summary>
    public static string RenderLiteral(string ueTypeName, string text)
    {
        // String types render as a quoted Lua string literal (helper reads
        // p.value as the text and builds the FString). An empty value is a
        // valid empty string, not the numeric 0 fallback.
        if (ueTypeName is "StrProperty" or "Utf8StrProperty" or "AnsiStrProperty")
            return "'" + EscapeLua(text ?? "") + "'";

        var t = (text ?? "").Trim();
        if (t.Length == 0) return "0";

        // Pointer-shaped types: prefer hex form
        if (ueTypeName is "ObjectProperty" or "ClassProperty" or "NameProperty"
            or "SoftObjectProperty" or "SoftClassProperty"
            or "WeakObjectProperty" or "LazyObjectProperty"
            or "InterfaceProperty" or "UInt64Property" or "Int64Property")
        {
            if (TryParseHexOrDecimal(t, out ulong u))
            {
                // Emit zero as plain "0" for readability; non-zero as 0xHEX
                return u == 0 ? "0" : $"0x{u:X}";
            }
            return MarkUnparsed(t);
        }

        // Bool: accept true/false/0/1/yes/no
        if (ueTypeName == "BoolProperty")
        {
            return ParseBoolLiteral(t) is { } b ? (b ? "1" : "0") : MarkUnparsed(t);
        }

        // Float / double: prefer InvariantCulture decimal
        if (ueTypeName is "FloatProperty" or "DoubleProperty")
        {
            // IsFinite is not belt-and-braces here. double.TryParse ACCEPTS "NaN",
            // "Infinity" and "-Infinity" (and overflowing literals round to ±Infinity),
            // so the parse "succeeds" and MarkUnparsed never fires — then ToString("R")
            // emits those bare words, which are not Lua number literals. Lua reads them
            // as an undefined global, i.e. `nil`, and the baked param silently becomes
            // nothing at all. Input is unvalidated upstream (InvokeParamDialog). (B23)
            if (double.TryParse(t, NumberStyles.Float, CultureInfo.InvariantCulture, out var d)
                && double.IsFinite(d))
            {
                return d.ToString("R", CultureInfo.InvariantCulture);
            }
            return MarkUnparsed(t);
        }

        // Integer scalars (incl. enum/byte/int16): allow decimal or 0x form.
        // Emit as signed-decimal so negative values round-trip naturally; the
        // helper's writeBakedParams uses math.floor on the value so any
        // accidental fraction would be silently truncated upstream anyway.
        if (TryParseHexOrDecimal(t, out ulong i))
        {
            // If the user wrote 0x..., preserve the hex form for readability;
            // otherwise stick to decimal so negative inputs read naturally.
            if (t.StartsWith("0x", StringComparison.OrdinalIgnoreCase))
                return $"0x{i:X}";
            return unchecked((long)i).ToString(CultureInfo.InvariantCulture);
        }
        return MarkUnparsed(t);
    }

    private static string MarkUnparsed(string raw)
        => $"--[[unparsed:{EscapeLuaComment(raw)}]] 0";

    /// <summary>Shared with <see cref="ParamBufferBuilder"/> so the FIRE path and the exported
    /// script parse the same inputs, negatives included (audit #5 Y2/Y5).</summary>
    internal static bool TryParseHexOrDecimal(string text, out ulong value)
    {
        value = 0;
        var t = text.Trim();
        if (t.Length == 0) return false;

        // Negative decimal -> reinterpret as ulong (sign-preserved bit pattern)
        if (t.StartsWith("-", StringComparison.Ordinal))
        {
            if (long.TryParse(t, NumberStyles.Integer, CultureInfo.InvariantCulture, out var s))
            {
                value = unchecked((ulong)s);
                return true;
            }
            return false;
        }

        if (t.StartsWith("0x", StringComparison.OrdinalIgnoreCase))
        {
            return ulong.TryParse(t.AsSpan(2), NumberStyles.HexNumber,
                                  CultureInfo.InvariantCulture, out value);
        }

        return ulong.TryParse(t, NumberStyles.Integer,
                              CultureInfo.InvariantCulture, out value);
    }

    /// <summary>Shared with <see cref="ParamBufferBuilder"/> so the FIRE path and the exported
    /// script accept the SAME spellings -- they used to disagree (audit #5 Y3).</summary>
    internal static bool? ParseBoolLiteral(string text) => text.ToLowerInvariant() switch
    {
        "true" or "1" or "yes" or "on"  => true,
        "false" or "0" or "no" or "off" => false,
        _                                => null,
    };

    /// <summary>Short type label rendered in the trailing comment of each
    /// PARAMS row (purely human-readable; not parsed).
    ///
    /// <para>Size-less overload; enums report the legacy <c>enum(int32)</c>.</para></summary>
    public static string ShortTypeNameForComment(string typeName)
        => ShortTypeNameForComment(typeName, 0);

    /// <summary>Size-aware form. Only <c>EnumProperty</c> consults the size — the
    /// comment used to hardcode <c>enum(int32)</c>, so after Y16 corrected the WRITE
    /// the generated script's own comment would have gone on asserting the old width
    /// (audit #5 Y16, the cosmetic straggler folded in rather than filed).</summary>
    public static string ShortTypeNameForComment(string typeName, int size) => typeName switch
    {
        "EnumProperty"   => size switch
        {
            1 => "enum(uint8)",
            2 => "enum(int16)",
            8 => "enum(int64)",
            _ => "enum(int32)",
        },
        "BoolProperty"   => "bool",
        "ByteProperty"   => "uint8",
        "Int8Property"   => "int8",
        "Int16Property"  => "int16",
        "UInt16Property" => "uint16",
        "IntProperty"    => "int32",
        "UInt32Property" => "uint32",
        "Int64Property"  => "int64",
        "UInt64Property" => "uint64",
        "FloatProperty"  => "float",
        "DoubleProperty" => "double",
        "NameProperty"   => "FName",
        "ObjectProperty" => "UObject*",
        "ClassProperty"  => "UClass*",
        _                => typeName.Replace("Property", ""),
    };

    /// <summary>Escape a string for embedding in a Lua single-quoted literal.
    /// Also breaks any closing long bracket (<c>]]</c>, <c>]=]</c>, <c>]==]</c>, …):
    /// harmless to Lua inside a quoted string, but AOBMaker's CE plugin wraps the
    /// WHOLE script in <c>[==[ … ]==]</c>, so the byte sequence must not appear
    /// ANYWHERE in the emitted text. Unlike a comment we cannot pad with a space
    /// here (that would change the string's value), so the leading <c>]</c> is
    /// emitted as a decimal escape instead -- same value, different source bytes.
    /// Reached with user text via the string-param path in <see cref="FormatValue"/>.</summary>
    public static string EscapeLua(string s) => CeLuaHygiene.EscapeLuaString(s);

    // R2: the body used to live here, hand-copied. Its own comment said "keep them
    // mirrors" — which is a divergence being maintained by hand, and there is no
    // reason for two implementations of one escape table. The name stays so callers
    // and tests do not churn; the behaviour is now defined in exactly one place.

    /// <summary>Escape for embedding in a Lua block comment <c>--[[...]]</c>.
    /// Breaks EVERY closing long bracket -- <c>]]</c>, <c>]=]</c>, <c>]==]</c>, any
    /// level -- by padding after the opening <c>]</c>, so none can terminate a
    /// long bracket early.
    ///
    /// Level 2 (<c>]==]</c>) matters as much as level 0 even though our own comment
    /// is level 0: AOBMaker's CE plugin wraps the WHOLE submitted script in
    /// <c>[==[ ... ]==]</c> at a HARDCODED level (pipe_server.cpp HandleCreateAAScript),
    /// unlike its InjectTableFile handler which picks a non-colliding level. A user
    /// typing <c>]==]</c> into an unparseable param would otherwise terminate that
    /// wrapper and break the CreateAAScript push. This is the widest free-text
    /// channel into any generated script (InvokeParamDialog -> MarkUnparsed).</summary>
    private static string EscapeLuaComment(string s)
    {
        if (string.IsNullOrEmpty(s)) return s ?? "";
        var sb = new StringBuilder(s.Length + 8);
        for (int i = 0; i < s.Length; i++)
        {
            char c = s[i];
            sb.Append(c);
            if (c != ']') continue;
            // Look ahead for ']' '='* ']' -- a closing long bracket of any level.
            int j = i + 1;
            while (j < s.Length && s[j] == '=') j++;
            if (j < s.Length && s[j] == ']')
                sb.Append(' ');   // split it; the '='* run is copied by later iterations
        }
        // A trailing ']' would fuse with MarkUnparsed's own "]]" into "]]]", closing
        // the comment ONE CHAR EARLY and leaving "] 0" as dangling syntax. Pad it.
        if (sb.Length > 0 && sb[sb.Length - 1] == ']') sb.Append(' ');
        return sb.ToString();
    }

    /// <summary>Append a line with LF-only ending (no CR) for CE compatibility.</summary>
    private static void Line(StringBuilder sb, string text = "")
    {
        sb.Append(text);
        sb.Append('\n');
    }
}
