using System.Text;

namespace UE5DumpUI.Services;

/// <summary>
/// Generates a CE memory-record AA Script for the robust Debug Camera toggle.
///
/// Unlike <see cref="BakedScriptGenerator"/> (a one-shot invoke whose
/// <c>[DISABLE]</c> is a nop), this is a STATEFUL checkbox: ticking runs
/// <c>[ENABLE]</c> → <c>setDebugCamera(1)</c> (camera ON), unticking runs
/// <c>[DISABLE]</c> → <c>setDebugCamera(0)</c> (camera OFF). Both blocks load
/// <c>ue5_invoke_helper.lua</c> (embedded in the .CT) and call the shared
/// <c>setDebugCamera</c> wrapper, which forwards to the <c>UE5_SetDebugCamera</c>
/// DLL export — so the whole toggle + controller-swap fallback (for Shipping
/// builds that strip <c>DisableDebugCamera</c>) runs DLL-side, identical to the
/// Console panel's Force On / Force Off.
/// </summary>
public static class DebugCameraScriptGenerator
{
    /// <summary>Build the [ENABLE]/[DISABLE] memory-record script.</summary>
    public static string Generate()
    {
        var sb = new StringBuilder(2048);
        EmitBlock(sb, "[ENABLE]", enable: true);
        EmitBlock(sb, "[DISABLE]", enable: false);
        return sb.ToString();
    }

    // Mimic mailbox layout (must match dll/src/Mimic.h MailboxData):
    //   0x00 cmd (write LAST to trigger), 0x04 status (poll == 1), 0x08 result,
    //   0x10 instanceAddr (here: the request 0=OFF / 1=ON). CMD_SET_DEBUG_CAMERA=7.
    private static void EmitBlock(StringBuilder sb, string header, bool enable)
    {
        var label = enable ? "ON" : "OFF";
        var req   = enable ? 1 : 0;
        Line(sb, header);
        Line(sb, "{$lua}");
        Line(sb, "if syntaxcheck then return end");
        CeLuaHygiene.AppendDebugPreamble(sb);
        Line(sb, "-- ================================================================");
        Line(sb, $"-- Debug Camera force {label} -- Generated by UE5CEDumper | {CeLuaHygiene.AttributionUrl}");
        Line(sb, "-- Tick = camera ON, untick = camera OFF. SELF-CONTAINED: talks to");
        Line(sb, "-- UE5Dumper.dll's mailbox directly -- no ue5_invoke_helper.lua");
        Line(sb, "-- needed. The DLL toggles and, when the game can't disable, switches");
        Line(sb, "-- the player's controller back to the original PlayerController.");
        Line(sb, "-- Requires UE5Dumper.dll injected (version.dll proxy or CE inject).");
        Line(sb, "-- ================================================================");
        Line(sb);

        // Resolve the exported mailbox symbol (tolerate the module-qualified form).
        Line(sb, "local mb = getAddressSafe('g_invokeMailbox')");
        Line(sb, "if not mb or mb == 0 then mb = getAddressSafe('UE5Dumper.g_invokeMailbox') end");
        Line(sb, "if not mb or mb == 0 then");
        Line(sb, "  showMessage('[DebugCamera] g_invokeMailbox not found -- is " +
                  "UE5Dumper.dll injected?')");
        Line(sb, "  if memrec then memrec.Active = false end");
        Line(sb, "  return");
        Line(sb, "end");
        // Contract check BEFORE the first write: if the layout moved we would
        // otherwise scribble on whatever now lives at those offsets.
        CeLuaHygiene.AppendContractCheck(sb, "DebugCamera", MailboxTimeout.UntickAndReturn);
        Line(sb);

        // Mailbox round-trip: write request, trigger CMD_SET_DEBUG_CAMERA=7, poll.
        // Bounded wait for IDLE before the FIRST write (audit #5 AA10). This
        // generator had no guard at all -- 7 of the 11 mailbox emitters did not, so
        // a toggle fired while another command was still in flight wrote straight
        // over it. Above the OPERAND writes, not merely above the status clear:
        // operands land in the same mailbox, so writing them corrupts the command in
        // flight just as surely -- the same reason the contract check sits here.
        CeLuaHygiene.AppendIdleWaitOrBail(sb, "mb", "DebugCamera");
        Line(sb, $"writeQword(mb + {CeMailboxLayout.OffInstanceAddr}, {req})   -- request: {req} = {label}");
        Line(sb, $"writeInteger(mb + {CeMailboxLayout.OffStatus}, 0)    -- clear status");
        Line(sb, $"writeInteger(mb + {CeMailboxLayout.OffCmd}, {CeMailboxLayout.CmdSetDebugCamera})    -- CMD_SET_DEBUG_CAMERA (write LAST)");
        // Shared wait: real-time deadline, status-specific diagnosis, and the untick
        // that stops a timed-out row claiming to be active.
        CeLuaHygiene.AppendMailboxWait(sb, "DebugCamera");
        Line(sb, $"local state = readInteger(mb + {CeMailboxLayout.OffResult}, true)   -- 1=ON, 0=OFF, -1=error");
        Line(sb, $"dbg('[DebugCamera] {label} -> state=' .. tostring(state))");
        // Test against the REQUEST, not against -1. `UE5_SetDebugCamera` re-reads the
        // state after firing ToggleDebugCamera and returns whatever it finds
        // (Frieren.cpp:1037-1046) — so a toggle that fired cleanly but did not take
        // returns 0 on an ENABLE, with no error code. Checking only -1 read that as
        // success: no message, window closed, row left ticked on a camera that never
        // turned on.
        Line(sb, $"if state ~= {req} then");
        Line(sb, $"  showMessage('[DebugCamera] {label} failed (state=' .. tostring(state) .. ') " +
                  "-- no live CheatManager, or the game refused the toggle.')");
        // Nothing was applied on this branch, so the record must not stay ticked.
        Line(sb, "  if memrec then memrec.Active = false end");
        Line(sb, "elseif DEBUG == 0 then");
        Line(sb, $"  {CeLuaHygiene.CloseCall}   -- clean success: close the Lua Engine window");
        Line(sb, "end");
        Line(sb, "{$asm}");
    }

    /// <summary>Append a line with LF-only ending (no CR) for CE compatibility.</summary>
    private static void Line(StringBuilder sb, string text = "")
    {
        sb.Append(text);
        sb.Append('\n');
    }
}
