using System.Collections.Generic;
using System.Text;
using UE5DumpUI.Models;

namespace UE5DumpUI.Services;

/// <summary>
/// Generates CE memory-record AA Scripts for the Fly toggles (Dunste) that call
/// the injected UE5Dumper.dll via the mailbox — the DLL-driven counterpart to the
/// pure-Lua standalone-trainer fly.
///
/// Two STATEFUL checkboxes (like <see cref="ProtectionScriptGenerator"/>):
///   • <see cref="FlyToggle.Enabled"/> — <c>[ENABLE]</c> fires <c>CMD_FLY</c> op
///     <c>FLY_OP_SET_ENABLED</c> value 1 (force MOVE_Flying + start the worker),
///     <c>[DISABLE]</c> value 0 (restore). One row per keyboard preset (WASD /
///     numpad / arrows) — WASD often collides with the game's own movement, so the
///     ENABLE first fires <c>FLY_OP_SET_PRESET</c> to pick that row's key set.
///   • <see cref="FlyToggle.Noclip"/> — op <c>FLY_OP_SET_NOCLIP</c> value 1/0
///     (disable / restore the actor's collision so flight passes through walls).
///
/// SELF-CONTAINED: talks to the DLL mailbox directly (no ue5_invoke_helper.lua).
/// Input is sampled DLL-side, so the toggle only arms/disarms + picks the preset.
/// </summary>
public static class FlyScriptGenerator
{
    // Mimic mailbox layout (must match dll/src/Mimic.h MailboxData + FlyOp):
    //   0x00 cmd (write LAST to trigger) = CMD_FLY(11)
    //   0x04 status (poll == 1), 0x08 result (1 active / 0 off / negative FlyResult)
    //   0x10 instanceAddr = op  (SET_ENABLED=0 / SET_PRESET=2 / SET_NOCLIP=4)
    //   0x18 ufuncAddr    = value (enable 1|0 / preset 0|1|2 / noclip 1|0)
    private const int CmdFly = CeMailboxLayout.CmdFly;
    private const int OpSetPreset = 2;   // FLY_OP_SET_PRESET

    /// <summary>Which Fly toggle to emit — the enum value IS the mailbox op.</summary>
    public enum FlyToggle
    {
        Enabled = 0,   // FLY_OP_SET_ENABLED
        Noclip  = 4,   // FLY_OP_SET_NOCLIP
    }

    /// <summary>Keyboard presets (index = Dunste::Preset / FLY_OP_SET_PRESET value).</summary>
    public static readonly string[] PresetNames = { "WASD", "Numpad", "Arrows" };

    private static string Name(FlyToggle t) => t == FlyToggle.Noclip ? "Fly Noclip" : "Fly";

    /// <summary>Build the [ENABLE]/[DISABLE] memory-record script. For Fly (Enabled)
    /// pass preset 0/1/2 to bake FLY_OP_SET_PRESET before enabling (so the DLL reads
    /// that key set); -1 leaves the DLL's current preset. Noclip ignores preset.</summary>
    public static string Generate(FlyToggle toggle, int preset = -1)
    {
        var sb = new StringBuilder(2560);
        EmitBlock(sb, "[ENABLE]", toggle, preset, enable: true);
        EmitBlock(sb, "[DISABLE]", toggle, preset, enable: false);
        return sb.ToString();
    }

    private static void EmitBlock(StringBuilder sb, string header, FlyToggle toggle, int preset, bool enable)
    {
        string name  = Name(toggle);
        string label = enable ? "ON" : "OFF";
        bool   hasPreset = toggle == FlyToggle.Enabled && preset >= 0 && preset < PresetNames.Length;
        string presetTag = hasPreset ? $" [{PresetNames[preset]}]" : "";
        Line(sb, header);
        Line(sb, "{$lua}");
        Line(sb, "if syntaxcheck then return end");
        CeLuaHygiene.AppendDebugPreamble(sb);
        Line(sb, "-- ================================================================");
        Line(sb, $"-- {name}{presetTag} force {label} -- Generated by UE5CEDumper | {CeLuaHygiene.AttributionUrl}");
        if (toggle == FlyToggle.Noclip)
        {
            Line(sb, "-- Tick = Noclip ON (disable the pawn's collision so flight passes");
            Line(sb, "-- through walls), untick = OFF (restore collision).");
        }
        else
        {
            Line(sb, $"-- Tick = Fly ON with the {(hasPreset ? PresetNames[preset] : "current")} key preset (MOVE_Flying, no");
            Line(sb, "-- gravity); untick = OFF. Movement keys are read DLL-side; keep the");
            Line(sb, "-- GAME window focused. Turn with the mouse.");
        }
        Line(sb, "-- SELF-CONTAINED: talks to UE5Dumper.dll's mailbox directly -- no");
        Line(sb, "-- ue5_invoke_helper.lua needed. Requires UE5Dumper.dll injected");
        Line(sb, "-- (version.dll proxy or CE inject). Single-player only.");
        Line(sb, "-- ================================================================");
        Line(sb);

        // Resolve the exported mailbox symbol (tolerate the module-qualified form).
        Line(sb, "local mb = getAddressSafe('g_invokeMailbox')");
        Line(sb, "if not mb or mb == 0 then mb = getAddressSafe('UE5Dumper.g_invokeMailbox') end");
        Line(sb, "if not mb or mb == 0 then");
        Line(sb, $"  showMessage('[{name}] g_invokeMailbox not found -- is " +
                  "UE5Dumper.dll injected?')");
        Line(sb, "  if memrec then memrec.Active = false end");
        Line(sb, "  return");
        Line(sb, "end");
        // Contract check BEFORE the first write (see AppendContractCheck).
        CeLuaHygiene.AppendContractCheck(sb, name);
        Line(sb);

        // In [ENABLE] of a preset Fly, pick the key set first (poll-only round-trip).
        if (enable && hasPreset)
            EmitCall(sb, name, OpSetPreset, preset, readState: false,
                     comment: $"op: FLY_OP_SET_PRESET ({PresetNames[preset]})");
        // Main round-trip: enable/disable (or noclip on/off) — reads the result.
        EmitCall(sb, name, (int)toggle, enable ? 1 : 0, readState: true,
                 comment: $"op: FLY_OP_SET_{(toggle == FlyToggle.Noclip ? "NOCLIP" : "ENABLED")}");
        Line(sb, "{$asm}");
    }

    // One mailbox round-trip: write op+value, trigger CMD_FLY (last), poll status.
    // readState=true also reads the result, dbg's it, surfaces a failure, and
    // closes the Lua Engine on clean success (the terminal call in a block).
    private static void EmitCall(StringBuilder sb, string name, int op, int value, bool readState, string comment)
    {
        // Bounded wait for IDLE before the FIRST write (audit #5 AA10). This
        // generator had no guard at all -- 7 of the 11 mailbox emitters did not, so
        // a toggle fired while another command was still in flight wrote straight
        // over it. Above the OPERAND writes, not merely above the status clear:
        // operands land in the same mailbox, so writing them corrupts the command in
        // flight just as surely -- the same reason the contract check sits here.
        CeLuaHygiene.AppendIdleWaitOrBail(sb, "mb", "Fly");
        Line(sb, $"writeQword(mb + {CeMailboxLayout.OffInstanceAddr}, {op})    -- {comment}");
        Line(sb, $"writeQword(mb + {CeMailboxLayout.OffUfuncAddr}, {value})    -- value = {value}");
        Line(sb, $"writeInteger(mb + {CeMailboxLayout.OffStatus}, 0)    -- clear status");
        Line(sb, $"writeInteger(mb + {CeMailboxLayout.OffCmd}, {CmdFly})    -- CMD_FLY (write LAST)");
        // Shared wait: real-time deadline, status-specific diagnosis, and the untick
        // that stops a timed-out row claiming to be active. Emitted once per call, and
        // a preset Fly emits TWO calls into one chunk — its locals are block-scoped, so
        // the second declaration simply shadows the first.
        CeLuaHygiene.AppendMailboxWait(sb, name);
        if (readState)
        {
            Line(sb, $"local state = readInteger(mb + {CeMailboxLayout.OffResult}, true)   -- 1=active, 0=off, <0=error");
            Line(sb, $"dbg('[{name}] op={op} -> state=' .. tostring(state))");
            Line(sb, "if state < 0 then");
            Line(sb, $"  showMessage('[{name}] -- no pawn / no CharacterMovement? (enter gameplay first)')");
            // Applied nothing -> the record must not stay ticked.
            Line(sb, "  if memrec then memrec.Active = false end");
            Line(sb, "elseif DEBUG == 0 then");
            Line(sb, $"  {CeLuaHygiene.CloseCall}   -- clean success: close the Lua Engine window");
            Line(sb, "end");
        }
    }

    /// <summary>Build the .CT batch rows: one Fly row per key preset + a Noclip row,
    /// for <see cref="CheatTableBuilder.Build"/>.</summary>
    public static List<CheatTableRow> BuildBatchRows()
    {
        var rows = new List<CheatTableRow>();
        for (int p = 0; p < PresetNames.Length; p++)
            rows.Add(new CtScriptRow
            {
                Category = "Fly",
                Description = $"Fly ({PresetNames[p]})",
                Script = Generate(FlyToggle.Enabled, p),
            });
        rows.Add(new CtScriptRow
        {
            Category = "Fly",
            Description = "Fly Noclip (through walls)",
            Script = Generate(FlyToggle.Noclip),
        });
        return rows;
    }

    /// <summary>Append a line with LF-only ending (no CR) for CE compatibility.</summary>
    private static void Line(StringBuilder sb, string text = "")
    {
        sb.Append(text);
        sb.Append('\n');
    }
}
