using System.Text;

namespace UE5DumpUI.Services;

/// <summary>
/// Generates a CE memory-record AA Script for the Keep-Foreground lock (Grausam).
///
/// A STATEFUL checkbox like <see cref="ProtectionScriptGenerator"/>: ticking runs
/// <c>[ENABLE]</c> → mailbox <c>CMD_FOREGROUND</c> op <c>FG_OP_SET</c> value 1 (the
/// DLL hooks <c>GetForegroundWindow</c> + subclasses the game window so the game
/// always believes it is the foreground app, defeating <c>t.IdleWhenNotForeground</c>
/// idle / focus-loss pause); unticking runs <c>[DISABLE]</c> → value 0. SELF-CONTAINED:
/// talks to the UE5Dumper.dll mailbox directly — no <c>ue5_invoke_helper.lua</c>.
/// The command is thread-agnostic (pure Win32) and runs on the DLL's polling thread,
/// so it works even while the game thread is asleep.
/// </summary>
public static class ForegroundScriptGenerator
{
    // Mimic mailbox layout (must match dll/src/Mimic.h MailboxData + ForegroundOp):
    //   0x00 cmd (write LAST to trigger) = CMD_FOREGROUND(12)
    //   0x04 status (poll == 1), 0x08 result (1 on / 0 off / <0 error)
    //   0x10 instanceAddr = op  (FG_OP_SET = 0)
    //   0x18 ufuncAddr    = value (1 = ON / 0 = OFF)
    private const int CmdForeground = CeMailboxLayout.CmdForeground;
    private const int OpSet = 0;

    /// <summary>Build the [ENABLE]/[DISABLE] memory-record script.</summary>
    public static string Generate()
    {
        var sb = new StringBuilder(2048);
        EmitBlock(sb, "[ENABLE]", enable: true);
        EmitBlock(sb, "[DISABLE]", enable: false);
        return sb.ToString();
    }

    private static void EmitBlock(StringBuilder sb, string header, bool enable)
    {
        var label = enable ? "ON" : "OFF";
        var value = enable ? 1 : 0;
        Line(sb, header);
        Line(sb, "{$lua}");
        Line(sb, "if syntaxcheck then return end");
        CeLuaHygiene.AppendDebugPreamble(sb);
        Line(sb, "-- ================================================================");
        Line(sb, $"-- Keep Foreground {label} -- Generated by UE5CEDumper | {CeLuaHygiene.AttributionUrl}");
        Line(sb, "-- Tick = the game always thinks it is the foreground app (its game");
        Line(sb, "-- thread keeps running when unfocused); untick = normal behaviour.");
        Line(sb, "-- SELF-CONTAINED: talks to UE5Dumper.dll's mailbox directly -- no");
        Line(sb, "-- ue5_invoke_helper.lua needed. The DLL hooks GetForegroundWindow and");
        Line(sb, "-- subclasses the game window (rewrites WM_ACTIVATEAPP etc.).");
        Line(sb, "-- Requires UE5Dumper.dll injected (version.dll proxy or CE inject).");
        Line(sb, "-- ================================================================");
        Line(sb);

        // Resolve the exported mailbox symbol (tolerate the module-qualified form).
        Line(sb, "local mb = getAddressSafe('g_invokeMailbox')");
        Line(sb, "if not mb or mb == 0 then mb = getAddressSafe('UE5Dumper.g_invokeMailbox') end");
        Line(sb, "if not mb or mb == 0 then");
        Line(sb, "  showMessage('[KeepForeground] g_invokeMailbox not found -- is " +
                  "UE5Dumper.dll injected?')");
        Line(sb, "  if memrec then memrec.Active = false end");
        Line(sb, "  return");
        Line(sb, "end");
        // Contract check BEFORE the first write: if the layout moved we would
        // otherwise scribble on whatever now lives at those offsets.
        CeLuaHygiene.AppendContractCheck(sb, "KeepForeground", MailboxTimeout.UntickAndReturn);
        Line(sb);

        // Mailbox round-trip: write op + value, trigger CMD_FOREGROUND=12, poll status.
        // Bounded wait for IDLE before the FIRST write (audit #5 AA10). This
        // generator had no guard at all -- 7 of the 11 mailbox emitters did not, so
        // a toggle fired while another command was still in flight wrote straight
        // over it. Above the OPERAND writes, not merely above the status clear:
        // operands land in the same mailbox, so writing them corrupts the command in
        // flight just as surely -- the same reason the contract check sits here.
        CeLuaHygiene.AppendIdleWaitOrBail(sb, "mb", "KeepForeground");
        Line(sb, $"writeQword(mb + {CeMailboxLayout.OffInstanceAddr}, {OpSet})    -- op: FG_OP_SET");
        Line(sb, $"writeQword(mb + {CeMailboxLayout.OffUfuncAddr}, {value})    -- value: {value} = {label}");
        Line(sb, $"writeInteger(mb + {CeMailboxLayout.OffStatus}, 0)    -- clear status");
        Line(sb, $"writeInteger(mb + {CeMailboxLayout.OffCmd}, {CmdForeground})    -- CMD_FOREGROUND (write LAST)");
        // Shared wait: real-time deadline, status-specific diagnosis, and the untick
        // that stops a timed-out row claiming to be active.
        CeLuaHygiene.AppendMailboxWait(sb, "KeepForeground");
        Line(sb, $"local state = readInteger(mb + {CeMailboxLayout.OffResult}, true)   -- 1=on, 0=off, <0=hook error");
        Line(sb, $"dbg('[KeepForeground] {label} -> state=' .. tostring(state))");
        Line(sb, "if state < 0 then");
        Line(sb, $"  showMessage('[KeepForeground] {label} failed (hook error ' .. tostring(state) .. ')')");
        // Nothing was applied on this branch, so the record must not stay ticked.
        Line(sb, "  if memrec then memrec.Active = false end");
        Line(sb, "elseif DEBUG == 0 then");
        Line(sb, $"  {CeLuaHygiene.CloseCall}   -- clean success: close the Lua Engine window");
        Line(sb, "end");
        Line(sb, "{$asm}");
    }

    /// <summary>Append a line with LF-only ending (no CR) for CE compatibility.</summary>
    private static void Line(StringBuilder sb, string text = "")
    {
        sb.Append(text);
        sb.Append('\n');
    }
}
