using System.Text;
using UE5DumpUI.Models;

namespace UE5DumpUI.Services;

/// <summary>
/// Generates a CE AA Script that locks a UE property value across ALL
/// live instances of a class. The generated script depends on
/// <c>ue5_freeze_helper.lua</c> being embedded in the .CT via
/// <see cref="IAobMakerBridge.InjectTableFileAsync"/> (or manual
/// <c>Table -&gt; Add File...</c>); at runtime it loads the helper and
/// calls <c>freezeProperty(cfg)</c>, then <c>handle.start()</c> /
/// <c>handle.stop()</c> from the [ENABLE] / [DISABLE] blocks.
///
/// Mirror of <see cref="BakedScriptGenerator"/> for the freeze use case:
/// single-quoted Lua strings for clean transit through the AOBMaker JSON
/// pipe, trailing LF (no CR), self-contained helper-loader prologue.
/// </summary>
public static class FreezeScriptGenerator
{
    /// <summary>Stable name of the embedded helper file the generated
    /// script looks up via <c>findTableFile</c>. Must match
    /// <see cref="FreezeHelperLuaResource.DefaultFileName"/>.</summary>
    public const string HelperFileName = "ue5_freeze_helper.lua";

    /// <summary>
    /// Build the AA Script for one freeze tuple. The output is a complete
    /// AA Script string with <c>[ENABLE]</c> / <c>[DISABLE]</c> blocks --
    /// enabling the script starts the freeze, disabling it stops cleanly.
    /// </summary>
    public static string Generate(FreezeScriptParams p)
    {
        var helperType = MapToHelperType(p.UeTypeName, p.PropertySize);
        var sb = new StringBuilder(2048);

        Line(sb, "[ENABLE]");
        Line(sb, "{$lua}");
        Line(sb, "if syntaxcheck then return end");
        CeLuaHygiene.AppendDebugPreamble(sb);
        Line(sb, "-- ================================================================");
        Line(sb, $"-- Property Freeze: {p.ClassName}::{p.PropertyName}");
        Line(sb, $"-- Generated by UE5CEDumper | {CeLuaHygiene.AttributionUrl}");
        Line(sb, "--");
        Line(sb, "-- REQUIREMENT: ue5_freeze_helper.lua MUST be embedded in this");
        Line(sb, "-- table. Inject via UE5DumpUI:");
        Line(sb, "--   Tools -> Inject Freeze Helper into Current CE Table");
        Line(sb, "-- ================================================================");
        Line(sb);

        // CFG block FIRST so the human eye lands on the editable values.
        AppendCfgBlock(sb, p, helperType);

        // Helper loader -- mirrors BakedScriptGenerator's prologue.
        AppendHelperLoader(sb);

        // Handles are stashed in a shared global table keyed by the
        // (class, prop, offset) tuple so multiple freeze scripts coexist
        // in the same CE Lua engine without clobbering each other's
        // handle. The key string is deterministic -- re-enabling the
        // same script re-uses the same slot.
        var handleKey = $"{p.ClassName}::{p.PropertyName}@0x{p.PropertyOffset:X}";

        Line(sb, "-- Per-script keyed handle storage so multiple Freeze scripts");
        Line(sb, "-- coexist in the same Lua engine without clobbering each other.");
        Line(sb, "_ue5_freeze_handles = _ue5_freeze_handles or {}");
        Line(sb, $"local FREEZE_KEY = '{EscapeLua(handleKey)}'");
        Line(sb);
        Line(sb, "-- Defensive stop: if a previous activation didn't clean up");
        Line(sb, "-- (rare -- AA Script reload while active), drop the stale handle.");
        Line(sb, "if _ue5_freeze_handles[FREEZE_KEY] then");
        Line(sb, "  pcall(_ue5_freeze_handles[FREEZE_KEY].stop)");
        Line(sb, "  _ue5_freeze_handles[FREEZE_KEY] = nil");
        Line(sb, "end");
        Line(sb);
        // Hand the CE record to the helper. Emitted OUTSIDE the "EDIT VALUES" block on
        // purpose: it is wiring, not a knob, and `memrec` is a chunk-local the
        // autoassembler injects — a user copying the CFG table elsewhere would carry a
        // dangling name with it.
        //
        // Without this, a freeze that gives up after MAX_FAIL_STREAK failed rescans
        // stops writing and leaves the row TICKED (in CE a red X on the checkbox means
        // ACTIVE, not failed), with its only report going to a Lua Engine window this
        // generator has already closed. CLAUDE.md's rule for a stateful toggle is that a
        // bail-out which applied nothing must untick, and a freeze that has stopped
        // writing is applying nothing. (`[FREEZESTUCK-2026-08-18]`)
        Line(sb, "-- An abandoned freeze unticks this record instead of lying about it.");
        Line(sb, "CFG.memrec = memrec");
        Line(sb);
        Line(sb, "-- Build the freeze handle from CFG and start the timers.");
        Line(sb, "local ok, handleOrErr = pcall(freezeProperty, CFG)");
        Line(sb, "if not ok then");
        Line(sb, "  showMessage('[Freeze] freezeProperty error:\\n' .. tostring(handleOrErr))");
        Line(sb, CeLuaHygiene.DeferredUntickLua("  "));
        Line(sb, "  return");
        Line(sb, "end");
        Line(sb, "_ue5_freeze_handles[FREEZE_KEY] = handleOrErr");
        // `pcall` answers "did Lua raise", NEVER "did anything get frozen" -- and no
        // mailbox failure can raise, because they are all caught inside the helper's
        // own pcall. So this used to report a clean success for a freeze that applied
        // nothing, auto-close the Lua window over it, and leave the record ticked.
        // start() now returns (ok, err, count); read it. (audit #5 AA12 + AA13)
        Line(sb, "local sok, sok2, serr, scount, scapped = pcall(handleOrErr.start)");
        Line(sb, "if not sok then");
        Line(sb, "  _ue5_freeze_handles[FREEZE_KEY] = nil");
        Line(sb, "  showMessage('[Freeze] start error:\\n' .. tostring(sok2))");
        Line(sb, CeLuaHygiene.DeferredUntickLua("  "));
        Line(sb, "  return");
        Line(sb, "end");
        // Three outcomes, and an older embedded helper is a FOURTH state that must not
        // be guessed at. A helper at <= 1.1 returns nothing from start(), so sok2 is
        // nil -- neither success nor failure. Reporting either would be an invented
        // verdict, so say what is actually known and leave the window open.
        Line(sb, "if sok2 == nil then");
        Line(sb, "  print('[Freeze] this table has an older ue5_freeze_helper.lua: it " +
                 "cannot report whether anything was frozen. Re-inject it via " +
                 "UE5DumpUI -> Tools -> Inject Freeze Helper into Current CE Table.')");
        // HARD failure: no DLL / contract mismatch / stale mailbox. Nothing is frozen
        // and nothing will be, so stop the timers start() already created -- the handle
        // slot must not be nil'd without stopping, or two timers are stranded writing
        // into the game with nothing able to reach them -- then untick and return
        // BEFORE the close, so the window stays open on the error (CLAUDE.md: "on ANY
        // error path the close MUST be unreachable").
        Line(sb, "elseif not sok2 then");
        Line(sb, "  pcall(handleOrErr.stop)");
        Line(sb, "  _ue5_freeze_handles[FREEZE_KEY] = nil");
        CeLuaHygiene.AppendFailedEnable(
            sb, "'[Freeze] nothing was frozen:\\n' .. tostring(serr)", "  ");
        // ARMED BUT EMPTY is NOT a failure: a class-wide freeze exists precisely so
        // instances that spawn later are picked up (helper header: "newly spawned
        // teammates / pickups / NPCs are picked up automatically"), so unticking here
        // would turn the feature into the bug. Say it once, ungated -- this is a
        // user-facing fact, not a diagnostic -- and keep the window open.
        Line(sb, "elseif scount == 0 then");
        Line(sb, $"  print('[Freeze] armed: no live instances of " +
                 $"{EscapeLua(p.ClassName)} (or any subclass) right now -- " +
                 "the freeze applies as they spawn.')");
        // A CAPPED pool is a success with a caveat, and the caveat has to be louder
        // than the count: `scount` is then a FLOOR, not a total, and the instances
        // past the cap are NOT held. A derived sweep off a broad base (Actor, Pawn)
        // reaches this routinely, so it is the normal case here, not an edge one —
        // same treatment Solide's status line already gives its own capped pool.
        Line(sb, "elseif scapped then");
        Line(sb, $"  print('[Freeze] armed on ' .. tostring(scount) .. ' instance(s) of " +
                 $"{EscapeLua(p.ClassName)} or a subclass -- CAP REACHED, so that is a " +
                 "floor, not a total: more instances exist and are NOT held. " +
                 "Narrow className in CFG to cover the ones you want.')");
        Line(sb, "end");
        Line(sb);
        Line(sb,
            $"dbg(string.format('[Freeze] Started: {EscapeLua(p.ClassName)}::" +
            $"{EscapeLua(p.PropertyName)} = %s ({helperType}@0x{p.PropertyOffset:X}) " +
            "on %s instance(s)', tostring(CFG.value), tostring(scount)))");
        // Close ONLY on a start that reported an outcome, froze something, and froze
        // ALL of it. nil (old helper), 0 (armed, empty) and a capped pool all keep the
        // window up, because each just printed something the user needs to read —
        // closing over the cap notice would put it straight back where the abandonment
        // message was: written, and never seen.
        CeLuaHygiene.AppendCloseOnSuccess(
            sb, "sok2 == true and scount ~= 0 and not scapped");
        Line(sb);
        Line(sb, "{$asm}");
        Line(sb, "[DISABLE]");
        Line(sb, "{$lua}");
        Line(sb, "if syntaxcheck then return end");
        CeLuaHygiene.AppendDebugPreamble(sb);
        Line(sb, "_ue5_freeze_handles = _ue5_freeze_handles or {}");
        Line(sb, $"local FREEZE_KEY = '{EscapeLua(handleKey)}'");
        Line(sb, "local h = _ue5_freeze_handles[FREEZE_KEY]");
        Line(sb, "if h then");
        Line(sb, "  pcall(h.stop)");
        Line(sb, "  _ue5_freeze_handles[FREEZE_KEY] = nil");
        Line(sb,
            $"  dbg('[Freeze] Stopped: {EscapeLua(p.ClassName)}::" +
            $"{EscapeLua(p.PropertyName)}')");
        Line(sb, "end");
        // Clean untick -- close the Lua Engine window.
        CeLuaHygiene.AppendCloseOnSuccess(sb);
        Line(sb, "{$asm}");

        return sb.ToString();
    }

    // ------------------------------------------------------------------
    // Section emitters
    // ------------------------------------------------------------------

    private static void AppendCfgBlock(
        StringBuilder sb, FreezeScriptParams p, string helperType)
    {
        Line(sb, "-- ====== EDIT VALUES BELOW =============================================");
        Line(sb, "local CFG = {");
        Line(sb, $"  className          = '{EscapeLua(p.ClassName)}',");
        // Scope. A Property Search row for an INHERITED field is keyed to the class
        // that DECLARES it, so this name is routinely an ancestor (`Actor` for
        // bCanBeDamaged / bHidden / bReplicates) and an exact-class pool holds
        // whichever stray instance of that ancestor the level has — never the pawn
        // the user was looking at. The Force submenu on the same row already walks
        // subclasses (Solide, audit #5 A6); the two must not scope oppositely.
        // (`[FREEZESCOPE-2026-08-18]`)
        Line(sb, "  derived            = true,  -- also hold every SUBCLASS " +
                 "(set false for exact class only)");
        Line(sb, $"  propOffset         = 0x{p.PropertyOffset:X},");
        Line(sb, $"  valueType          = '{helperType}',");
        Line(sb, $"  value              = {p.ValueLiteral},");
        // Packed-bitfield bool: emit the FieldMask so the helper does a masked
        // read-modify-write instead of stamping the whole byte. Emitted ONLY for
        // a real packed bool — a native bool (mask 0) owns its byte and must keep
        // the plain whole-byte write, and emitting a mask for it would be wrong
        // in the other direction. See FreezeScriptParams.BoolFieldMask (AA1).
        if (helperType == "bool" && IsPackedBoolMask(p.BoolFieldMask))
        {
            Line(sb, $"  boolMask           = 0x{p.BoolFieldMask:X2}," +
                     "  -- packed bitfield: only this bit is written");
        }
        Line(sb, "  tickIntervalMs     = 50,    -- writes 20x/sec; lower = more CPU");
        Line(sb, "  refreshIntervalSec = 5,     -- re-enum instances every 5s");
        Line(sb, "  -- filter = function(addr) return true end,  -- optional");
        Line(sb, "}");
        Line(sb, "-- =====================================================================");
        Line(sb);
    }

    private static void AppendHelperLoader(StringBuilder sb)
    {
        Line(sb, "-- Load ue5_freeze_helper.lua from the table file (no fs fallback).");
        Line(sb, $"local tf = findTableFile('{HelperFileName}')");
        Line(sb, "if not tf then");
        Line(sb, "  showMessage(");
        Line(sb, $"    '[Freeze] {HelperFileName} not found in this table.\\n\\n' ..");
        Line(sb, "    'Setup: UE5DumpUI -> Tools -> Inject Freeze Helper into Current CE Table')");
        Line(sb, CeLuaHygiene.DeferredUntickLua("  "));
        Line(sb, "  return");
        Line(sb, "end");
        Line(sb, "do");
        Line(sb, "  local ss = createStringStream()");
        // copyFrom (not Stream.write) -- consistent with invoke helper's loader
        // and the CE Lua quirk noted in memory (Stream.write copies forward,
        // copyFrom is the safe reverse).
        Line(sb, "  ss.copyFrom(tf.Stream, tf.Stream.Size)");
        Line(sb, "  local fn, err = load(ss.DataString)");
        Line(sb, "  ss.destroy()");
        Line(sb, "  if not fn then");
        Line(sb, "    showMessage('[Freeze] Helper load error:\\n' .. tostring(err))");
        Line(sb, CeLuaHygiene.DeferredUntickLua("    "));
        Line(sb, "    return");
        Line(sb, "  end");
        Line(sb, "  fn()");
        Line(sb, "end");
        Line(sb);
    }

    // ------------------------------------------------------------------
    // Type mapping (UE -> ue5_freeze_helper.lua valueType)
    // ------------------------------------------------------------------

    /// <summary>
    /// Freeze-helper <c>valueType</c> for an integer field of a given engine-reported
    /// byte width. The sibling of <c>CeXmlExportService.CeWidthForSize</c>: the engine
    /// tells us how wide the field really is, and that beats any guess made from the
    /// type name.
    ///
    /// <para>Width is the whole safety story — <c>ue5_freeze_helper.lua</c>'s writers
    /// are <c>writeByte</c> / <c>writeSmallInteger</c> / <c>writeInteger</c> /
    /// <c>writeQword</c>, so naming a type 4 bytes wide when the field is 1 byte writes
    /// over the three neighbouring bytes on every tick, 20x a second.</para>
    ///
    /// <para>Signedness follows what C++ actually produces for each width, and only
    /// affects which values <c>FreezeValueDialog</c> accepts (the helper's signed and
    /// unsigned writers of one width are the same function): UE's
    /// <c>enum class E : uint8</c> / <c>: uint16</c> are unsigned, while a 4-byte enum
    /// is a plain <c>enum</c> whose implementation-defined underlying type is signed
    /// <c>int</c>. 4 also stays <c>int32</c> because that is what this mapping already
    /// emitted — the only width it was ever right about.</para>
    /// </summary>
    public static string HelperTypeForSize(int size) => size switch
    {
        1 => "uint8",
        2 => "uint16",
        4 => "int32",
        8 => "int64",
        _ => "int32",   // unknown / unreported size → legacy default
    };

    /// <summary>
    /// Map a UE property type string (e.g. "FloatProperty") to the
    /// freeze helper's <c>valueType</c> string. Unsupported / unknown
    /// types map to the empty string so callers can detect them and
    /// gray out the freeze button at the row level.
    ///
    /// <para>Size-less overload: every type whose width is fixed by its NAME maps
    /// identically, and <c>EnumProperty</c> — the one type whose width is not — falls
    /// back to the legacy <c>int32</c>. Callers holding a real property should pass its
    /// size to <see cref="MapToHelperType(string,int)"/>; this form exists for the
    /// callers that only ask "is this type supported at all".</para>
    /// </summary>
    public static string MapToHelperType(string ueTypeName)
        => MapToHelperType(ueTypeName, 0);

    /// <summary>
    /// Size-aware mapping. <paramref name="propSize"/> is the engine-reported byte
    /// width of the field (<c>PropertySearchMatch.PropSize</c>); pass 0 when it is
    /// unknown.
    /// </summary>
    public static string MapToHelperType(string ueTypeName, int propSize) => ueTypeName switch
    {
        "BoolProperty"   => "bool",
        "ByteProperty"   => "uint8",
        "Int8Property"   => "int8",
        "Int16Property"  => "int16",
        "UInt16Property" => "uint16",
        "IntProperty"    => "int32",
        "UInt32Property" => "uint32",
        // EnumProperty stores the underlying integer, and UE's dominant shape is the
        // 1-byte `enum class E : uint8`. This used to be a flat "int32" whose own
        // comment admitted the gap ("if a future game has a 1-byte enum we'd want to
        // surface the size") -- so freezing one emitted a 4-byte writeInteger that
        // clobbered the three following bytes. The engine reported the real width all
        // along; it was dropped at the FreezeScriptParams boundary. (audit #5 Y15 --
        // third site of the family behind W6 and Y2.)
        "EnumProperty"   => HelperTypeForSize(propSize),
        "Int64Property"  => "int64",
        "UInt64Property" => "uint64",
        "FloatProperty"  => "float",
        "DoubleProperty" => "double",
        _                => "",
    };

    /// <summary>
    /// The class a freeze will actually be keyed on: the DEFINING class when the DLL
    /// reported one, else the row's own class.
    ///
    /// <para>One definition, called by both the ViewModel that builds the script and the
    /// dialog that tells the user what is about to happen. They used to pick it
    /// separately — the dialog showed <c>ClassName</c> while the generator emitted
    /// <c>DefiningClassName</c> — which is the "report and reality computed by different
    /// code paths" shape audit #4 named as a root cause, and it is exactly the kind of
    /// mismatch that let a freeze on a pawn's field quietly become a freeze on
    /// <c>Actor</c>.</para>
    /// </summary>
    public static string HeldClassName(string? className, string? definingClassName)
        => !string.IsNullOrEmpty(definingClassName) ? definingClassName! : (className ?? "");

    /// <summary>
    /// Whether the given UE property type is supported by v1 of the
    /// freeze pipeline. Used by the row-level button enablement so
    /// users don't get a script that the helper would reject.
    /// Support is a property of the TYPE, so no size is needed —
    /// an EnumProperty is supported at every width.
    /// </summary>
    public static bool IsTypeSupported(string ueTypeName)
        => !string.IsNullOrEmpty(MapToHelperType(ueTypeName));

    /// <summary>
    /// Whether an <c>FBoolProperty</c> FieldMask describes a <b>packed bitfield</b>
    /// bool — i.e. one that shares its byte with siblings and must be written with a
    /// masked read-modify-write.
    ///
    /// <para>True only for a single set bit in <c>[0x01 … 0x80]</c>. Everything else is
    /// deliberately false and falls back to the plain whole-byte write:</para>
    /// <list type="bullet">
    /// <item><c>0</c> — the DLL reports no mask (native bool, or a pre-AA1 DLL).</item>
    /// <item><c>0xFF</c> — UE's own marker for a native bool (<c>SetBoolSize</c> sets
    /// <c>FieldMask = 255</c> when <c>bIsNativeBool</c>), which owns its whole byte.</item>
    /// <item>Any multi-bit value — not a shape UE produces for a single bool; treating
    /// it as a mask would OR in bits belonging to nobody.</item>
    /// </list>
    /// <para>A mask that reaches here is guaranteed to sit in the byte at the property
    /// offset: the DLL only emits one after reading <c>FieldSize == 1</c>, so the
    /// property is a single byte and there is no <c>ByteOffset</c> to apply.</para>
    /// </summary>
    public static bool IsPackedBoolMask(int fieldMask)
        => fieldMask > 0 && fieldMask < 0xFF && (fieldMask & (fieldMask - 1)) == 0;

    // ------------------------------------------------------------------
    // Lua escaping
    // ------------------------------------------------------------------

    /// <summary>
    /// Escape a string for embedding inside single-quoted Lua literals.
    /// Mirrors BakedScriptGenerator's escape rules.
    /// </summary>
    public static string EscapeLua(string s) => CeLuaHygiene.EscapeLuaString(s);

    // R2: the body used to live here, hand-copied. Its own comment said "keep them
    // mirrors" — which is a divergence being maintained by hand, and there is no
    // reason for two implementations of one escape table. The name stays so callers
    // and tests do not churn; the behaviour is now defined in exactly one place.

    private static void Line(StringBuilder sb, string s = "") => sb.Append(s).Append('\n');
}
