using System.Text;
using UE5DumpUI.Models;

namespace UE5DumpUI.Services;

/// <summary>
/// Generates CE Lua invoke scripts for UFunction calls.
/// The generated script resolves instance + function by name at runtime,
/// builds a GUI form for parameters, and calls UE_InvokeActorEvent.
/// </summary>
public static class InvokeScriptGenerator
{
    /// <summary>
    /// Generate a complete CE AA script that invokes a UFunction.
    /// </summary>
    /// <param name="className">Owner class name (e.g. "playerCharacterBP_C")</param>
    /// <param name="funcName">Function name (e.g. "addMoney")</param>
    /// <param name="func">Function metadata with parameters</param>
    /// <returns>CE Auto Assembler script string (with [ENABLE]/[DISABLE])</returns>
    public static string Generate(string className, string funcName, FunctionInfoModel func)
    {
        var sb = new StringBuilder(4096);
        var inputParams = func.Params.Where(p => !p.IsReturn).ToList();
        var hasParams = inputParams.Count > 0;

        sb.AppendLine("[ENABLE]");
        sb.AppendLine("{$lua}");
        sb.AppendLine("if syntaxcheck then return end");
        sb.AppendLine("-- ================================================================");
        sb.AppendLine($"-- UFunction Invoker: {className}::{funcName}");
        sb.AppendLine("-- Generated by UE5CEDumper — resolves by name, survives restarts");
        sb.AppendLine("-- ================================================================");
        sb.AppendLine();

        // Constants
        sb.AppendLine($"local OWNER_CLASS  = \"{EscapeLua(className)}\"");
        sb.AppendLine($"local FUNC_NAME    = \"{EscapeLua(funcName)}\"");
        sb.AppendLine();

        // UE Dumper connection check
        AppendConnectionCheck(sb);

        // Instance resolver
        AppendInstanceResolver(sb);

        // Function resolver
        AppendFunctionResolver(sb);

        // Print resolved info
        sb.AppendLine("print(string.format(\"  Resolved: %s::%s\", OWNER_CLASS, FUNC_NAME))");
        sb.AppendLine("print(string.format(\"  Instance: 0x%X  |  UFunction: 0x%X\", instanceAddr, ufuncPtr))");
        sb.AppendLine();

        if (hasParams)
        {
            // Build GUI form for parameters
            AppendParamForm(sb, className, funcName, inputParams);
        }
        else
        {
            // No parameters — invoke directly
            AppendDirectInvoke(sb);
        }

        sb.AppendLine("{$asm}");
        sb.AppendLine("[DISABLE]");
        sb.AppendLine("{$lua}");
        sb.AppendLine("-- nop");
        sb.AppendLine("{$asm}");

        return sb.ToString();
    }

    private static void AppendConnectionCheck(StringBuilder sb)
    {
        sb.AppendLine("-- Init UE Dumper if needed");
        sb.AppendLine("if not UE_IsConnected or not UE_IsConnected() then");
        sb.AppendLine("    if UseUE then pcall(UseUE) end");
        sb.AppendLine("end");
        sb.AppendLine("if not UE_IsConnected or not UE_IsConnected() then");
        sb.AppendLine("    print(\"ERROR: UE Dumper not connected!\")");
        sb.AppendLine("    showMessage(\"ERROR: UE Dumper not connected!\\nMake sure the dumper is loaded.\")");
        AppendCleanupTimer(sb, 1);
        sb.AppendLine("    return");
        sb.AppendLine("end");
        sb.AppendLine();
    }

    private static void AppendInstanceResolver(StringBuilder sb)
    {
        sb.AppendLine("-- Find a live instance (skip CDOs)");
        sb.AppendLine("local instOk, instances = pcall(UE_GetAllObjectsOfClass, OWNER_CLASS)");
        sb.AppendLine("local instanceAddr = nil");
        sb.AppendLine("if instOk and instances then");
        sb.AppendLine("    for _, inst in ipairs(instances) do");
        sb.AppendLine("        local addr = inst.obj or 0");
        sb.AppendLine("        local fullName = inst.name or \"\"");
        sb.AppendLine("        if addr ~= 0 and not fullName:find(\"Default__\") then");
        sb.AppendLine("            instanceAddr = addr");
        sb.AppendLine("            break");
        sb.AppendLine("        end");
        sb.AppendLine("    end");
        sb.AppendLine("    if not instanceAddr and #instances > 0 then");
        sb.AppendLine("        instanceAddr = instances[1].obj or 0");
        sb.AppendLine("        if instanceAddr ~= 0 then");
        sb.AppendLine("            print(\"  WARNING: Only CDO instances found for \" .. OWNER_CLASS)");
        sb.AppendLine("        end");
        sb.AppendLine("    end");
        sb.AppendLine("end");
        sb.AppendLine();

        // Subclass fallback
        sb.AppendLine("if not instanceAddr or instanceAddr == 0 then");
        sb.AppendLine("    local subOk, subs = pcall(UE_GetAllSubObjectsOfClass, OWNER_CLASS)");
        sb.AppendLine("    if subOk and subs then");
        sb.AppendLine("        for _, subAddr in ipairs(subs) do");
        sb.AppendLine("            local fn = \"\"");
        sb.AppendLine("            local fnOk, fnStr = pcall(UE_GetObjectFullName, subAddr)");
        sb.AppendLine("            if fnOk and fnStr then fn = fnStr end");
        sb.AppendLine("            if subAddr ~= 0 and not fn:find(\"Default__\") then");
        sb.AppendLine("                instanceAddr = subAddr");
        sb.AppendLine("                break");
        sb.AppendLine("            end");
        sb.AppendLine("        end");
        sb.AppendLine("    end");
        sb.AppendLine("end");
        sb.AppendLine();

        sb.AppendLine("if not instanceAddr or instanceAddr == 0 then");
        sb.AppendLine("    print(\"ERROR: No instance of '\" .. OWNER_CLASS .. \"' found!\")");
        sb.AppendLine("    showMessage(\"ERROR: No live instance of '\" .. OWNER_CLASS .. \"' found!\\nMake sure you are in-game.\")");
        AppendCleanupTimer(sb, 1);
        sb.AppendLine("    return");
        sb.AppendLine("end");
        sb.AppendLine();
    }

    private static void AppendFunctionResolver(StringBuilder sb)
    {
        sb.AppendLine("-- Find the UFunction by name");
        sb.AppendLine("local funcOk, funcs = pcall(UE_GetFunctionsOfObject, instanceAddr, true)");
        sb.AppendLine("local ufuncPtr = nil");
        sb.AppendLine("if funcOk and funcs then");
        sb.AppendLine("    for _, f in ipairs(funcs) do");
        sb.AppendLine("        if f.name == FUNC_NAME then");
        sb.AppendLine("            ufuncPtr = f.ufunction");
        sb.AppendLine("            break");
        sb.AppendLine("        end");
        sb.AppendLine("    end");
        sb.AppendLine("    if not ufuncPtr then");
        sb.AppendLine("        local lower = FUNC_NAME:lower()");
        sb.AppendLine("        for _, f in ipairs(funcs) do");
        sb.AppendLine("            if f.name and f.name:lower() == lower then");
        sb.AppendLine("                ufuncPtr = f.ufunction");
        sb.AppendLine("                break");
        sb.AppendLine("            end");
        sb.AppendLine("        end");
        sb.AppendLine("    end");
        sb.AppendLine("end");
        sb.AppendLine();
        sb.AppendLine("if not ufuncPtr or ufuncPtr == 0 then");
        sb.AppendLine("    print(string.format(\"ERROR: Function '%s' not found on %s!\", FUNC_NAME, OWNER_CLASS))");
        sb.AppendLine("    showMessage(string.format(\"ERROR: Function '%s' not found on %s!\", FUNC_NAME, OWNER_CLASS))");
        AppendCleanupTimer(sb, 1);
        sb.AppendLine("    return");
        sb.AppendLine("end");
        sb.AppendLine();
    }

    private static void AppendDirectInvoke(StringBuilder sb)
    {
        sb.AppendLine("-- No parameters — invoke directly");
        sb.AppendLine("local params = {}");
        sb.AppendLine("print(\"  Invoking with 0 params...\")");
        sb.AppendLine("local ok, retVal = pcall(UE_InvokeActorEvent, instanceAddr, ufuncPtr, params)");
        sb.AppendLine("if not ok then");
        sb.AppendLine("    print(\"  INVOKE FAILED: \" .. tostring(retVal))");
        sb.AppendLine("    showMessage(\"INVOKE FAILED:\\n\" .. tostring(retVal))");
        sb.AppendLine("else");
        sb.AppendLine("    print(\"  INVOKED OK!\")");
        sb.AppendLine("end");
        AppendCleanupTimer(sb, 0);
        sb.AppendLine();
    }

    private static void AppendParamForm(StringBuilder sb, string className, string funcName,
        List<FunctionParamModel> inputParams)
    {
        sb.AppendLine("-- ================================================================");
        sb.AppendLine("-- Build parameter input form");
        sb.AppendLine("-- ================================================================");
        sb.AppendLine($"local PARAM_COUNT = {inputParams.Count}");
        sb.AppendLine("local labelW = 280");
        sb.AppendLine("local editW = 160");
        sb.AppendLine("local rowH = 28");
        sb.AppendLine("local btnH = 50");
        sb.AppendLine("local yPos = 10");
        sb.AppendLine("local contentH = math.max(PARAM_COUNT, 1) * rowH + 20");
        sb.AppendLine("local formH = math.min(contentH + btnH + 50, 600)");
        sb.AppendLine("local formW = labelW + editW + 40");
        sb.AppendLine();
        sb.AppendLine("local frm = createForm(false)");
        sb.AppendLine($"frm.Caption = string.format(\"%s::%s  |  0x%X\", OWNER_CLASS, FUNC_NAME, instanceAddr)");
        sb.AppendLine("frm.Width = formW");
        sb.AppendLine("frm.Height = formH");
        sb.AppendLine("frm.Position = poScreenCenter");
        sb.AppendLine("frm.BorderStyle = bsSizeable");
        sb.AppendLine();
        sb.AppendLine("local edits = {}");

        // Generate labels + edit fields for each parameter
        for (int i = 0; i < inputParams.Count; i++)
        {
            var p = inputParams[i];
            var ceType = GetCeSizeType(p.TypeName, p.Size);
            var label = $"{p.Name}  [{ShortTypeName(p.TypeName)}, {p.Size} B{(p.IsOut ? ", out" : "")}]";
            var defaultVal = GetDefaultValue(p.TypeName);
            int idx = i + 1; // Lua is 1-indexed

            sb.AppendLine("    do");
            sb.AppendLine($"        local lbl = createLabel(frm)");
            sb.AppendLine($"        lbl.Caption = \"{EscapeLua(label)}\"");
            sb.AppendLine($"        lbl.Left = 10");
            sb.AppendLine($"        lbl.Top = yPos + 2");
            sb.AppendLine($"        lbl.AutoSize = true");
            sb.AppendLine($"        local edt = createEdit(frm)");
            sb.AppendLine($"        edt.Text = \"{defaultVal}\"");
            sb.AppendLine($"        edt.Left = labelW + 20");
            sb.AppendLine($"        edt.Top = yPos");
            sb.AppendLine($"        edt.Width = editW");
            sb.AppendLine($"        edits[{idx}] = edt");
            sb.AppendLine($"        yPos = yPos + rowH");
            sb.AppendLine("    end");
        }

        // Buttons
        sb.AppendLine();
        sb.AppendLine("local btnY = formH - btnH - 10");
        sb.AppendLine("local btnFire = createButton(frm)");
        sb.AppendLine("btnFire.Caption = \"FIRE\"");
        sb.AppendLine("btnFire.Width = 120");
        sb.AppendLine("btnFire.Height = 34");
        sb.AppendLine("btnFire.Left = 10");
        sb.AppendLine("btnFire.Top = btnY");
        sb.AppendLine();
        sb.AppendLine("local btnCancel = createButton(frm)");
        sb.AppendLine("btnCancel.Caption = \"Cancel\"");
        sb.AppendLine("btnCancel.Width = 90");
        sb.AppendLine("btnCancel.Height = 34");
        sb.AppendLine("btnCancel.Left = 140");
        sb.AppendLine("btnCancel.Top = btnY");
        sb.AppendLine("btnCancel.OnClick = function() frm.close() end");
        sb.AppendLine();

        // On close: deactivate memrec
        sb.AppendLine("frm.OnClose = function(sender)");
        AppendCleanupTimer(sb, 1);
        sb.AppendLine("    return caFree");
        sb.AppendLine("end");
        sb.AppendLine();

        // Fire button logic
        sb.AppendLine("btnFire.OnClick = function()");
        sb.AppendLine("    local params = {}");
        for (int i = 0; i < inputParams.Count; i++)
        {
            var p = inputParams[i];
            var ceType = GetCeSizeType(p.TypeName, p.Size);
            int idx = i + 1;
            var parseExpr = GetParseExpression(p.TypeName, idx);
            sb.AppendLine($"    table.insert(params, {{type={ceType}, value={parseExpr}}})");
        }
        sb.AppendLine($"    print(string.format(\"  Invoking UE_InvokeActorEvent with %d params...\", #params))");
        sb.AppendLine("    local ok, retVal = pcall(UE_InvokeActorEvent, instanceAddr, ufuncPtr, params)");
        sb.AppendLine("    if not ok then");
        sb.AppendLine("        print(\"  INVOKE FAILED: \" .. tostring(retVal))");
        sb.AppendLine("        showMessage(\"INVOKE FAILED:\\n\" .. tostring(retVal))");
        sb.AppendLine("    else");
        sb.AppendLine("        print(\"  INVOKED OK!\")");
        sb.AppendLine("    end");
        sb.AppendLine("    frm.close()");
        sb.AppendLine("end");
        sb.AppendLine();
        sb.AppendLine("frm.show()");
        sb.AppendLine();
    }

    private static void AppendCleanupTimer(StringBuilder sb, int indent)
    {
        var pad = new string(' ', indent * 4);
        sb.AppendLine($"{pad}local t = createTimer(nil, false)");
        sb.AppendLine($"{pad}t.Interval = 100");
        sb.AppendLine($"{pad}t.OnTimer = function(s) s.Enabled = false; s.destroy(); if memrec then memrec.Active = false end end");
        sb.AppendLine($"{pad}t.Enabled = true");
    }

    /// <summary>Map UE property type to CE size constant.</summary>
    private static string GetCeSizeType(string typeName, int size)
    {
        return typeName switch
        {
            "BoolProperty" => "szByte",
            "ByteProperty" or "Int8Property" => "szByte",
            "Int16Property" or "UInt16Property" => "szWord",
            "IntProperty" or "UInt32Property" or "EnumProperty" => "szDword",
            "Int64Property" or "UInt64Property" => "szQword",
            "FloatProperty" => "szFloat",
            "DoubleProperty" => "szDouble",
            "NameProperty" or "ObjectProperty" or "ClassProperty"
                or "SoftObjectProperty" or "WeakObjectProperty"
                or "LazyObjectProperty" or "InterfaceProperty" => "szQword",
            _ => size switch
            {
                1 => "szByte",
                2 => "szWord",
                4 => "szDword",
                8 => "szQword",
                _ => "szDword",
            },
        };
    }

    /// <summary>Short display name for param type label.</summary>
    private static string ShortTypeName(string typeName)
    {
        return typeName switch
        {
            "BoolProperty" => "bool",
            "ByteProperty" => "uint8",
            "Int8Property" => "int8",
            "Int16Property" => "int16",
            "UInt16Property" => "uint16",
            "IntProperty" => "int32",
            "UInt32Property" => "uint32",
            "Int64Property" => "int64",
            "UInt64Property" => "uint64",
            "FloatProperty" => "float",
            "DoubleProperty" => "double",
            "NameProperty" => "FName",
            "ObjectProperty" => "UObject*",
            "ClassProperty" => "UClass*",
            "StrProperty" => "FString",
            "TextProperty" => "FText",
            "EnumProperty" => "enum",
            "StructProperty" => "struct",
            _ => typeName.Replace("Property", ""),
        };
    }

    /// <summary>Default edit field value for a type.</summary>
    private static string GetDefaultValue(string typeName)
    {
        return typeName switch
        {
            "FloatProperty" or "DoubleProperty" => "0.0",
            "BoolProperty" => "0",
            "NameProperty" or "ObjectProperty" or "ClassProperty"
                or "SoftObjectProperty" or "WeakObjectProperty"
                or "InterfaceProperty" => "0x0",
            _ => "0",
        };
    }

    /// <summary>Lua expression to parse edit field text into a numeric value.</summary>
    private static string GetParseExpression(string typeName, int editIndex)
    {
        // Pointer/FName types: hex-aware parsing
        if (typeName is "NameProperty" or "ObjectProperty" or "ClassProperty"
            or "SoftObjectProperty" or "WeakObjectProperty" or "InterfaceProperty")
        {
            return $"(function() local s = edits[{editIndex}].Text; " +
                   "if s:sub(1,2) == \"0x\" or s:sub(1,2) == \"0X\" then " +
                   "return tonumber(s, 16) or 0 else return tonumber(s) or 0 end end)()";
        }

        // Float types: direct tonumber
        if (typeName is "FloatProperty" or "DoubleProperty")
            return $"tonumber(edits[{editIndex}].Text) or 0.0";

        // Integer types: floor to avoid fractional
        return $"math.floor(tonumber(edits[{editIndex}].Text) or 0)";
    }

    /// <summary>Escape special characters for Lua string literal.</summary>
    private static string EscapeLua(string s)
    {
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n");
    }
}
