using System.Text;
using UE5DumpUI.Models;

namespace UE5DumpUI.Services;

/// <summary>
/// Generates CE Lua invoke scripts for UFunction calls.
/// Uses the shared memory mailbox (g_invokeMailbox) for communication with UE5Dumper DLL.
/// No remote thread injection needed — uses ReadProcessMemory/WriteProcessMemory only.
///
/// IMPORTANT: All Lua string literals use single quotes ('...') to avoid
/// JSON double-quote escaping issues when transmitted via the AOBMaker pipe.
/// Line endings are normalized to LF-only (\n) for CE compatibility.
/// </summary>
public static class InvokeScriptGenerator
{
    // Mailbox offsets (must match Mimic.h MailboxData struct). The tokens shared
    // with the other mailbox generators live in CeMailboxLayout (single source of
    // truth); the invoke-only fields stay local.
    private const string OffCmd          = CeMailboxLayout.OffCmd;
    private const string OffStatus       = CeMailboxLayout.OffStatus;
    private const string OffResult       = CeMailboxLayout.OffResult;
    private const string OffInstanceAddr = CeMailboxLayout.OffInstanceAddr;
    private const string OffUfuncAddr    = CeMailboxLayout.OffUfuncAddr;
    private const string OffParmsSize    = "0x020";
    private const string OffNumParms     = "0x022";
    private const string OffFuncFlags    = "0x024";
    private const string OffClassName    = "0x028";
    private const string OffFuncName     = "0x128";
    private const string OffErrorMsg     = "0x228";
    private const string OffParamsData   = CeMailboxLayout.OffParamsData;

    /// <summary>
    /// Generate a complete CE AA script that invokes a UFunction via mailbox.
    /// </summary>
    public static string Generate(string className, string funcName, FunctionInfoModel func)
    {
        var sb = new StringBuilder(8192);
        var inputParams = func.Params.Where(p => !p.IsReturn).ToList();
        var hasParams = inputParams.Count > 0;

        Line(sb, "[ENABLE]");
        Line(sb, "{$lua}");
        Line(sb, "if syntaxcheck then return end");
        CeLuaHygiene.AppendDebugPreamble(sb);
        Line(sb, "-- ================================================================");
        Line(sb, $"-- UFunction Invoker: {className}::{funcName}");
        Line(sb, $"-- Generated by UE5CEDumper -- uses shared memory mailbox | {CeLuaHygiene.AttributionUrl}");
        Line(sb, "-- No remote thread injection needed (pure memory read/write)");
        Line(sb, "-- ================================================================");
        Line(sb);

        // Constants
        Line(sb, $"local OWNER_CLASS  = '{EscapeLua(className)}'");
        Line(sb, $"local FUNC_NAME    = '{EscapeLua(funcName)}'");
        Line(sb, $"local PARMS_SIZE   = {func.ParmsSize}");
        Line(sb);

        // Forward-declare mb so helper closures can capture the upvalue
        Line(sb, "local mb");
        Line(sb);

        // Find mailbox symbol. Resolved BEFORE the helpers are defined, not after: the
        // helpers capture `mb` as an upvalue and read it when CALLED, so the order is
        // free -- and taking it lets the contract check below sit ahead of every write
        // this script emits, including the writeBytes inside writeMbStr.
        AppendMailboxDetection(sb);

        // Contract check BEFORE the first write, at chunk level -- before writeMbStr /
        // waitDone exist. Every write goes through one of them, so this is the one place
        // that covers all of them while a mismatch can still be reported rather than
        // written. UntickAndReturn: the deferred cleanup timer that normally unticks this
        // record has not been created yet here, so a bare return would strand the row.
        CeLuaHygiene.AppendContractCheck(sb, "Invoke", MailboxTimeout.UntickAndReturn);
        Line(sb);

        // Mailbox helpers
        AppendMailboxHelpers(sb);

        // Instance resolver via CMD_FIND_INSTANCE
        AppendInstanceResolver(sb);

        // Function resolver via CMD_FIND_FUNCTION
        AppendFunctionResolver(sb);

        // Print resolved info
        Line(sb, "dbg(string.format('  Resolved: %s::%s', OWNER_CLASS, FUNC_NAME))");
        Line(sb, "dbg(string.format('  Instance: 0x%X  |  UFunction: 0x%X', instanceAddr, ufuncPtr))");
        Line(sb);

        if (hasParams)
        {
            AppendParamForm(sb, className, funcName, func, inputParams, func.ParmsSize);
        }
        else
        {
            AppendDirectInvoke(sb, className, funcName, func, func.ParmsSize);
        }

        Line(sb, "{$asm}");
        Line(sb, "[DISABLE]");
        Line(sb, "{$lua}");
        Line(sb, "-- nop");
        Line(sb, "{$asm}");

        return sb.ToString();
    }

    /// <summary>Append a line with LF-only ending (no CR).</summary>
    private static void Line(StringBuilder sb, string text = "")
    {
        sb.Append(text);
        sb.Append('\n');
    }

    private static void AppendMailboxHelpers(StringBuilder sb)
    {
        Line(sb, "-- Mailbox helpers (read/write target process memory via CE)");
        Line(sb, "local function writeMbStr(offset, str)");
        Line(sb, "    local bytes = {}");
        Line(sb, "    for i = 1, math.min(#str, 255) do bytes[#bytes+1] = string.byte(str, i) end");
        Line(sb, "    bytes[#bytes+1] = 0");
        Line(sb, "    writeBytes(mb + offset, bytes)");
        Line(sb, "end");
        // ONE emitted helper for the idle wait, called from all three round-trips,
        // rather than four inline copies of the loop. Four hand-placed copies of a rule
        // is the failure mode this whole area keeps hitting: R3 reached Teleport /
        // CoordLibrary / PointerQuery and never reached here, and the wait loop's three
        // defects reached all seven of its hand-rolled copies at once. The BODY comes
        // from CeLuaHygiene so it stays byte-identical with the other generators; only
        // the bail differs per call site, which is why the helper returns a boolean
        // instead of deciding for its callers.
        Line(sb, "local function waitIdle()");
        CeLuaHygiene.AppendIdleWait(sb, "mb", "return false", "    ");
        Line(sb, "    return true");
        Line(sb, "end");
        // The shared wait. Hand-rolled until now, with all three of the defects build
        // 2743 fixed in the other seven copies: it counted sleep(1) iterations against a
        // millisecond constant (15.47 ms each, so the "10 s" bound was ~155 s of frozen
        // Lua Engine), and it reported the mailbox's errorMsg string -- which on a
        // TIMEOUT the DLL never wrote, so the text was either empty or stale from the
        // previous command. `status` is what actually distinguishes "the DLL never saw
        // it" from "it took the command and wedged".
        //
        // RaiseError, not the toggles' UntickAndReturn: waitDone is called from two
        // different frames -- the [ENABLE] chunk itself and, on the param-form path,
        // btnFire.OnClick -- so a `return` would leave only waitDone and let both
        // callers carry on as though the round-trip had completed. A raise is the one
        // bail that aborts both, and it is the contract these call sites already have.
        // The `timeoutMs` parameter is gone: no emitted call site ever passed one, and
        // the deadline now lives in the shared emitter.
        Line(sb, "local function waitDone()");
        CeLuaHygiene.AppendMailboxWait(sb, "Invoke", MailboxTimeout.RaiseError, indent: "    ");
        Line(sb, "end");
        Line(sb, "local function readErr()");
        Line(sb, $"    return readString(mb + {OffErrorMsg}, 256) or 'Unknown error'");
        Line(sb, "end");
        Line(sb);
    }

    private static void AppendMailboxDetection(StringBuilder sb)
    {
        // getAddressSafe, NOT getAddress. celua.txt: getAddress "returns the address of a
        // symbol"; getAddressSafe "returns the address of a symbol, OR NIL IF NOT FOUND".
        // The bare form RAISES on a missing symbol, which is the case this whole block exists
        // to handle -- so when the DLL was not loaded the first call aborted the chunk and took
        // three things with it: the module-prefixed fallback below (never reached), the
        // diagnostic showMessage (never shown, leaving CE's raw Lua error instead), and the
        // cleanup timer -- so the memory record stayed TICKED after a bail-out that applied
        // nothing, against CLAUDE.md's untick rule. This was the last bare getAddress the repo
        // emitted (audit #5 Y8).
        //
        // Both spellings are mandatory and the order is not a preference: depending on how CE
        // picked the module up, an export is reachable bare or only as "<module>.<name>", and
        // which one works is not predictable from here (lessons-learned B33). The sibling
        // generators already do this -- BakedScriptGenerator via getAddressSafe, CeReadinessLua
        // via pcall(getAddress, ...).
        Line(sb, "-- Find mailbox symbol (exported by UE5Dumper DLL)");
        Line(sb, "mb = getAddressSafe('g_invokeMailbox')");
        Line(sb, "if not mb or mb == 0 then");
        Line(sb, "    mb = getAddressSafe('UE5Dumper.g_invokeMailbox')");
        Line(sb, "end");
        Line(sb, "if not mb or mb == 0 then");
        Line(sb, "    print('ERROR: g_invokeMailbox not found!')");
        Line(sb, "    showMessage('ERROR: g_invokeMailbox not found!\\nMake sure UE5Dumper DLL is loaded (version.dll Proxy or CE inject).')");
        AppendCleanupTimer(sb, 1);
        Line(sb, "    return");
        Line(sb, "end");
        Line(sb, "dbg(string.format('  [Invoke] Mailbox at 0x%X', mb))");
        Line(sb);
    }

    private static void AppendInstanceResolver(StringBuilder sb)
    {
        Line(sb, "-- Find a live instance via mailbox CMD_FIND_INSTANCE (2)");
        AppendBusyBail(sb, "instance lookup");
        Line(sb, $"writeMbStr({OffClassName}, OWNER_CLASS)");
        Line(sb, $"writeInteger(mb + {OffStatus}, 0)");
        Line(sb, $"writeInteger(mb + {OffCmd}, 2)");
        Line(sb, "waitDone()");
        Line(sb);

        Line(sb, $"local instanceAddr = readQword(mb + {OffInstanceAddr})");
        Line(sb, $"if readInteger(mb + {OffResult}, true) ~= 0 or instanceAddr == 0 then");
        Line(sb, "    local err = readErr()");
        Line(sb, "    print('ERROR: No instance of [' .. OWNER_CLASS .. '] found: ' .. err)");
        Line(sb, "    showMessage('ERROR: No live instance of [' .. OWNER_CLASS .. '] found!\\n' .. err .. '\\nMake sure you are in-game.')");
        AppendCleanupTimer(sb, 1);
        Line(sb, "    return");
        Line(sb, "end");
        Line(sb);
    }

    private static void AppendFunctionResolver(StringBuilder sb)
    {
        Line(sb, "-- Find UFunction via mailbox CMD_FIND_FUNCTION (3)");
        AppendBusyBail(sb, "function lookup");
        Line(sb, $"writeQword(mb + {OffInstanceAddr}, instanceAddr)");
        Line(sb, $"writeMbStr({OffFuncName}, FUNC_NAME)");
        Line(sb, $"writeInteger(mb + {OffStatus}, 0)");
        Line(sb, $"writeInteger(mb + {OffCmd}, 3)");
        Line(sb, "waitDone()");
        Line(sb);

        Line(sb, $"local ufuncPtr = readQword(mb + {OffUfuncAddr})");
        Line(sb, $"if readInteger(mb + {OffResult}, true) ~= 0 or ufuncPtr == 0 then");
        Line(sb, "    print(string.format('ERROR: Function [%s] not found on %s!', FUNC_NAME, OWNER_CLASS))");
        Line(sb, "    showMessage(string.format('ERROR: Function [%s] not found on %s!', FUNC_NAME, OWNER_CLASS))");
        AppendCleanupTimer(sb, 1);
        Line(sb, "    return");
        Line(sb, "end");
        Line(sb);
    }

    private static void AppendDirectInvoke(StringBuilder sb, string className, string funcName,
        FunctionInfoModel func, int parmsSize)
    {
        Line(sb, "-- No parameters -- invoke directly via CMD_INVOKE (1)");
        AppendBusyBail(sb, "invoke");

        // Zero out params_data (even for void functions, clear the buffer)
        if (parmsSize > 0)
        {
            Line(sb, $"local PD = mb + {OffParamsData}");
            Line(sb, $"for i = 0, {parmsSize - 1} do writeByte(PD + i, 0) end");
        }

        Line(sb, $"writeQword(mb + {OffInstanceAddr}, instanceAddr)");
        Line(sb, $"writeQword(mb + {OffUfuncAddr}, ufuncPtr)");
        Line(sb, $"writeInteger(mb + {OffStatus}, 0)");
        Line(sb, $"writeInteger(mb + {OffCmd}, 1)");
        Line(sb, "dbg('  Invoking via mailbox...')");
        Line(sb, "waitDone()");
        Line(sb);

        Line(sb, $"local result = readInteger(mb + {OffResult}, true)");
        Line(sb, "if result == 0 then dbg('  INVOKED OK!')");
        Line(sb, "else print('  INVOKE FAILED: error code ' .. tostring(result) .. ' ' .. readErr()); showMessage('INVOKE FAILED:\\nerror code ' .. tostring(result)) end");
        // DEBUG-only: decode + print the return value from the params buffer.
        AppendReturnDebugPrint(sb, className, funcName, func, "");
        // Clean success (no args, DEBUG off) -> close the Lua Engine window.
        Line(sb, $"if result == 0 and DEBUG == 0 then {CeLuaHygiene.CloseCall} end");
        AppendCleanupTimer(sb, 0);
        Line(sb);
    }

    private static void AppendParamForm(StringBuilder sb, string className, string funcName,
        FunctionInfoModel func, List<FunctionParamModel> inputParams, int parmsSize)
    {
        Line(sb, "-- ================================================================");
        Line(sb, "-- Build parameter input form");
        Line(sb, "-- ================================================================");
        Line(sb, $"local PARAM_COUNT = {inputParams.Count}");
        Line(sb, "local labelW = 280");
        Line(sb, "local editW = 160");
        Line(sb, "local rowH = 28");
        Line(sb, "local btnH = 50");
        Line(sb, "local yPos = 10");
        Line(sb, "local contentH = math.max(PARAM_COUNT, 1) * rowH + 20");
        Line(sb, "local formH = math.min(contentH + btnH + 50, 600)");
        Line(sb, "local formW = labelW + editW + 40");
        Line(sb);
        Line(sb, "local frm = createForm(false)");
        Line(sb, "frm.Caption = string.format('%s::%s  |  0x%X', OWNER_CLASS, FUNC_NAME, instanceAddr)");
        Line(sb, "frm.Width = formW");
        Line(sb, "frm.Height = formH");
        Line(sb, "frm.Position = poScreenCenter");
        Line(sb, "frm.BorderStyle = bsSizeable");
        Line(sb);
        Line(sb, "local edits = {}");

        // String INPUT params need an FString built by value. This path is
        // self-contained (no helper file), so inline a small builder once when
        // any INPUT (non-out) string param is present. Out-string params are
        // left as empty FStrings (built by the callee), so they don't need it.
        // Comments here are ASCII-only because the emitted script is transmitted
        // through CE / the AOBMaker JSON pipe.
        if (inputParams.Any(p => IsStringType(p.TypeName) && !p.IsOut))
        {
            AppendInlineFStringBuilder(sb);
        }

        // Generate labels + edit fields
        for (int i = 0; i < inputParams.Count; i++)
        {
            var p = inputParams[i];
            // Stage 1: surface expected UClass for pointer params (mirrors the
            // in-app InvokeParamDialog label) so the CE-side form is just as
            // self-documenting.
            var objClassSuffix = !string.IsNullOrEmpty(p.ObjectClassName)
                ? $": {p.ObjectClassName}"
                : "";
            // Struct params keep their edit box so the `edits[i]` indices stay aligned with the
            // param list, but the label says the box is inert -- the alternative is a form that
            // silently ignores what the user typed (audit #5 Y6).
            var structNote = p.TypeName == "StructProperty" ? ", NOT EDITABLE - sent as zeroes" : "";
            var label = $"{p.Name}  [{ShortTypeName(p.TypeName)}{objClassSuffix}, {p.Size} B{(p.IsOut ? ", out" : "")}{structNote}]";
            var defaultVal = GetDefaultValue(p.TypeName);
            int idx = i + 1;

            Line(sb, "    do");
            Line(sb, "        local lbl = createLabel(frm)");
            Line(sb, $"        lbl.Caption = '{EscapeLua(label)}'");
            Line(sb, "        lbl.Left = 10");
            Line(sb, "        lbl.Top = yPos + 2");
            Line(sb, "        lbl.AutoSize = true");
            Line(sb, "        local edt = createEdit(frm)");
            Line(sb, $"        edt.Text = '{defaultVal}'");
            Line(sb, "        edt.Left = labelW + 20");
            Line(sb, "        edt.Top = yPos");
            Line(sb, "        edt.Width = editW");
            Line(sb, $"        edits[{idx}] = edt");
            Line(sb, "        yPos = yPos + rowH");
            Line(sb, "    end");
        }

        // Buttons
        Line(sb);
        Line(sb, "local btnY = formH - btnH - 10");
        Line(sb, "local btnFire = createButton(frm)");
        Line(sb, "btnFire.Caption = 'FIRE'");
        Line(sb, "btnFire.Width = 120");
        Line(sb, "btnFire.Height = 34");
        Line(sb, "btnFire.Left = 10");
        Line(sb, "btnFire.Top = btnY");
        Line(sb);
        Line(sb, "local btnCancel = createButton(frm)");
        Line(sb, "btnCancel.Caption = 'Cancel'");
        Line(sb, "btnCancel.Width = 90");
        Line(sb, "btnCancel.Height = 34");
        Line(sb, "btnCancel.Left = 140");
        Line(sb, "btnCancel.Top = btnY");
        Line(sb, "btnCancel.OnClick = function() frm.close() end");
        Line(sb);

        // On close: deactivate memrec
        Line(sb, "frm.OnClose = function(sender)");
        AppendCleanupTimer(sb, 1);
        Line(sb, "    return caFree");
        Line(sb, "end");
        Line(sb);

        // Fire button logic — write params to mailbox, then CMD_INVOKE
        Line(sb, "btnFire.OnClick = function()");
        // The fourth guard, and the one whose bail shape genuinely differs: this is a
        // CLOSURE, so `return` leaves only the click handler — which is the right
        // behaviour here (the form stays open and the user can press FIRE again) but
        // means it must SAY so. A silent return would look exactly like a FIRE that
        // worked. No cleanup timer either: the record's lifetime belongs to the form,
        // and frm.OnClose is what unticks it.
        Line(sb, "    if not waitIdle() then");
        Line(sb, "        showMessage('[Invoke] the DLL mailbox is busy -- nothing was sent.\\n" +
                 "Another CE script or a previous FIRE is still mid-command; press FIRE again in a moment.')");
        Line(sb, "        return");
        Line(sb, "    end");
        Line(sb, $"    local PD = mb + {OffParamsData}");

        // Zero-fill params buffer
        Line(sb, $"    for i = 0, {parmsSize - 1} do writeByte(PD + i, 0) end");

        // Write each param to the mailbox params_data at its offset
        for (int i = 0; i < inputParams.Count; i++)
        {
            var p = inputParams[i];
            int idx = i + 1;
            // OUT string params must stay a zeroed/empty FString (the callee
            // fills them). Building one would make the callee FMemory::Free our
            // CE-allocated Data buffer -> crash. The zero-fill above already
            // left the 16-byte slot as a valid empty FString.
            if (IsStringType(p.TypeName) && p.IsOut)
            {
                Line(sb, $"    -- {p.Name}: out FString left empty (callee fills it)");
                continue;
            }
            // A struct param has no scalar spelling, and this form has one edit box per
            // param. It used to fall through GetMailboxWriteStatement's size switch to
            // writeInteger, so an FVector (12 B on UE4, 24 on UE5) got FOUR bytes written from
            // math.floor(tonumber(text)) and the rest left zero -- i.e. the call went out with a
            // garbage vector and nothing said so. The params buffer is already zero-filled
            // above, so skipping the write sends a well-defined zeroed struct instead, which is
            // at least a value the callee can survive. Use the app's Invoke dialog (which
            // expands sub-fields) to pass a real one (audit #5 Y6).
            if (p.TypeName == "StructProperty")
            {
                Line(sb, $"    -- {p.Name}: struct ({p.Size} B) left ZEROED - this form cannot edit a struct");
                continue;
            }
            var parseExpr = GetParseExpression(p.TypeName, idx);
            var writeStmt = GetMailboxWriteStatement(p.TypeName, p.Size, p.Offset, parseExpr);
            Line(sb, $"    {writeStmt}");
        }

        Line(sb, $"    writeQword(mb + {OffInstanceAddr}, instanceAddr)");
        Line(sb, $"    writeQword(mb + {OffUfuncAddr}, ufuncPtr)");
        Line(sb, $"    writeInteger(mb + {OffStatus}, 0)");
        Line(sb, $"    writeInteger(mb + {OffCmd}, 1)");
        Line(sb, "    dbg('  Invoking via mailbox...')");
        Line(sb, "    waitDone()");
        Line(sb, $"    local result = readInteger(mb + {OffResult}, true)");
        Line(sb, "    if result == 0 then dbg('  INVOKED OK!')");
        Line(sb, "    else print('  INVOKE FAILED: error code ' .. tostring(result) .. ' ' .. readErr()); showMessage('INVOKE FAILED:\\nerror code ' .. tostring(result)) end");
        // DEBUG-only: decode + print the return value (the created form closes
        // below, but the Lua Engine console keeps the printed value visible).
        AppendReturnDebugPrint(sb, className, funcName, func, "    ");

        Line(sb, "    frm.close()");
        Line(sb, "end");
        Line(sb);
        Line(sb, "frm.show()");
        Line(sb);
    }

    /// <summary>
    /// Emit a DEBUG-gated block that decodes + prints the function's return
    /// value from the mailbox params buffer. No-op for void functions (no
    /// param carries CPF_ReturnParm). The success flag is the mailbox
    /// <c>result</c> local (0 == success); the block never fires when
    /// <c>DEBUG == 0</c>, so it stays quiet by default and only surfaces the
    /// value when the user set <c>UE5_DEBUG=1</c> (which also keeps the window
    /// open). Uses a private <c>_PDret</c> base so it can't collide with the
    /// input-param write path's <c>PD</c> local.
    /// </summary>
    private static void AppendReturnDebugPrint(StringBuilder sb, string className,
        string funcName, FunctionInfoModel func, string indent)
    {
        var ret = func.Params.FirstOrDefault(p => p.IsReturn);
        if (ret == null) return;
        // Guard the offset against the params buffer bounds (a bogus return
        // offset would otherwise read outside the mailbox's params_data).
        if (ret.Offset < 0 || (func.ParmsSize > 0 && ret.Offset >= func.ParmsSize)) return;

        Line(sb, $"{indent}if result == 0 and DEBUG ~= 0 then");
        Line(sb, $"{indent}    local _PDret = mb + {OffParamsData}");
        CeInvokeReturn.AppendDecodeAndPrint(sb, className, funcName, ret.Name,
            ret.TypeName, ret.Size, ret.Offset, "_PDret", indent + "    ");
        Line(sb, $"{indent}end");
    }

    /// <summary>
    /// Emit the busy-mailbox bail for a TOP-LEVEL round-trip: say why, then leave the
    /// <c>[ENABLE]</c> block through the deferred cleanup timer so the CE row does not
    /// stay ticked with nothing applied.
    ///
    /// <para>This guards the round-trip, not just the <c>cmd</c> store — the wait has to
    /// precede the FIRST write of the trip (class name / instanceAddr / the params
    /// zero-fill all land inside the mailbox), which is also where the sibling
    /// generators put it.</para>
    ///
    /// <para><paramref name="what"/> names the step that was not attempted, so a user
    /// who hits this knows which of the three round-trips gave up.</para>
    /// </summary>
    private static void AppendBusyBail(StringBuilder sb, string what)
    {
        Line(sb, "if not waitIdle() then");
        Line(sb, $"    print('ERROR: mailbox busy -- {what} not attempted')");
        Line(sb, $"    showMessage('[Invoke] the DLL mailbox is busy -- {what} not attempted.\\n" +
                 "Another CE script or a previous invoke is still mid-command; try again in a moment.')");
        AppendCleanupTimer(sb, 1);
        Line(sb, "    return");
        Line(sb, "end");
    }

    private static void AppendCleanupTimer(StringBuilder sb, int indent)
    {
        var pad = new string(' ', indent * 4);
        Line(sb, $"{pad}local t = createTimer(nil, false)");
        Line(sb, $"{pad}t.Interval = 100");
        Line(sb, $"{pad}t.OnTimer = function(s) s.Enabled = false; s.destroy(); if memrec then memrec.Active = false end end");
        Line(sb, $"{pad}t.Enabled = true");
    }

    /// <summary>True for UE string property types (built as an FString by value).</summary>
    private static bool IsStringType(string typeName) =>
        typeName is "StrProperty" or "Utf8StrProperty" or "AnsiStrProperty";

    /// <summary>True for the wide (UTF-16) FString; false for narrow FUtf8/FAnsiString.</summary>
    private static bool IsWideString(string typeName) => typeName == "StrProperty";

    /// <summary>
    /// Emit a self-contained CE Lua <c>writeFStr(addr, s, wide)</c> that builds
    /// a by-value UE string (FString / FUtf8String / FAnsiString) at
    /// <c>addr</c>: allocates a char buffer in the target process, writes the
    /// characters + null terminator, and stamps the <c>{Data, Num, Max}</c>
    /// header. The buffer is intentionally leaked — see the emitted note.
    /// (ASCII-only body; the generated script is CE / pipe transmitted.)
    /// </summary>
    private static void AppendInlineFStringBuilder(StringBuilder sb)
    {
        Line(sb, "-- Build a by-value UE string INPUT param at addr {Data, Num, Max}.");
        Line(sb, "-- wide=true -> UTF-16LE (FString); false -> raw bytes (FUtf8/FAnsiString).");
        Line(sb, "-- NOTE: the buffer is intentionally NOT freed -- freeing is unsafe if the");
        Line(sb, "-- callee retained it, and it is CE-allocated (not UE FMemory).");
        Line(sb, "local function writeFStr(addr, s, wide)");
        Line(sb, "    s = tostring(s or '')");
        Line(sb, "    local n = #s");
        Line(sb, "    local bytes = {}");
        Line(sb, "    local buf");
        Line(sb, "    if wide then");
        Line(sb, "        for i = 1, n do bytes[#bytes+1] = string.byte(s, i); bytes[#bytes+1] = 0 end");
        Line(sb, "        bytes[#bytes+1] = 0; bytes[#bytes+1] = 0");
        Line(sb, "        buf = allocateMemory((n + 1) * 2)");
        Line(sb, "    else");
        Line(sb, "        for i = 1, n do bytes[#bytes+1] = string.byte(s, i) end");
        Line(sb, "        bytes[#bytes+1] = 0");
        Line(sb, "        buf = allocateMemory(n + 1)");
        Line(sb, "    end");
        Line(sb, "    writeBytes(buf, bytes)");
        Line(sb, "    writeQword(addr, buf)");
        Line(sb, "    writeInteger(addr + 8, n + 1)");
        Line(sb, "    writeInteger(addr + 12, n + 1)");
        Line(sb, "end");
        Line(sb);
    }

    /// <summary>Generate a CE Lua write statement for a param in the mailbox params_data buffer.</summary>
    private static string GetMailboxWriteStatement(string typeName, int size, int offset, string valueExpr)
    {
        // String params build an FString by value via the inlined writeFStr.
        if (IsStringType(typeName))
            return $"writeFStr(PD + {offset}, {valueExpr}, {(IsWideString(typeName) ? "true" : "false")})";

        string writeFunc = typeName switch
        {
            "BoolProperty" or "ByteProperty" or "Int8Property"
                => "writeBytes",
            "Int16Property" or "UInt16Property"
                => "writeSmallInteger",
            "FloatProperty"
                => "writeFloat",
            "DoubleProperty"
                => "writeDouble",
            "Int64Property" or "UInt64Property"
                or "NameProperty" or "ObjectProperty" or "ClassProperty"
                or "SoftObjectProperty" or "SoftClassProperty"
                or "WeakObjectProperty" or "LazyObjectProperty"
                or "InterfaceProperty"
                => "writeQword",
            // EnumProperty is DELIBERATELY absent here (audit #5 Y16, the enum-width
            // family's fourth finding). UE sizes an enum by its underlying type --
            // 1 byte for the common TEnumAsByte / uint8 enum class -- so writing 4
            // clobbers the next parameter in params_data. The `_ => size switch`
            // fallback below already maps 1/2/8 correctly; letting enums reach it is
            // the whole fix. `size` was a parameter here the entire time.
            "IntProperty" or "UInt32Property"
                => "writeInteger",
            _ => size switch
            {
                1 => "writeBytes",
                2 => "writeSmallInteger",
                8 => "writeQword",
                _ => "writeInteger",
            },
        };

        // writeBytes takes a table: writeBytes(addr, {val})
        if (writeFunc == "writeBytes")
            return $"writeBytes(PD + {offset}, {{{valueExpr}}})";

        return $"{writeFunc}(PD + {offset}, {valueExpr})";
    }

    /// <summary>Short display name for param type label.</summary>
    private static string ShortTypeName(string typeName)
    {
        return typeName switch
        {
            "BoolProperty" => "bool",
            "ByteProperty" => "uint8",
            "Int8Property" => "int8",
            "Int16Property" => "int16",
            "UInt16Property" => "uint16",
            "IntProperty" => "int32",
            "UInt32Property" => "uint32",
            "Int64Property" => "int64",
            "UInt64Property" => "uint64",
            "FloatProperty" => "float",
            "DoubleProperty" => "double",
            "NameProperty" => "FName",
            "ObjectProperty" => "UObject*",
            "ClassProperty" => "UClass*",
            "StrProperty" => "FString",
            "TextProperty" => "FText",
            "EnumProperty" => "enum",
            "StructProperty" => "struct",
            _ => typeName.Replace("Property", ""),
        };
    }

    /// <summary>Default edit field value for a type.</summary>
    private static string GetDefaultValue(string typeName)
    {
        return typeName switch
        {
            "FloatProperty" or "DoubleProperty" => "0.0",
            "BoolProperty" => "0",
            // String types start empty so the form shows a text field, not "0".
            "StrProperty" or "Utf8StrProperty" or "AnsiStrProperty" => "",
            "NameProperty" or "ObjectProperty" or "ClassProperty"
                or "SoftObjectProperty" or "SoftClassProperty"
                or "WeakObjectProperty" or "LazyObjectProperty"
                or "InterfaceProperty" => "0x0",
            _ => "0",
        };
    }

    /// <summary>Lua expression to parse edit field text into a value.</summary>
    private static string GetParseExpression(string typeName, int editIndex)
    {
        // String types: pass the raw edit text straight to writeFStr (no numeric parse).
        if (IsStringType(typeName))
            return $"edits[{editIndex}].Text or ''";

        // Pointer/FName types: hex-aware parsing.
        //
        // The prefix MUST be stripped before tonumber(s, 16). Lua's base form rejects any
        // character that is not a digit of that base, and 'x' is not a hex digit, so
        // tonumber('0x1F2A3B4C5D0', 16) is nil -- the old code detected the "0x" and then
        // handed the still-prefixed string straight to it, so `or 0` wrote a NULL POINTER
        // for every address the user actually pasted. The app formats every address as
        // "0x" + uppercase hex (Renge::AddrToStr), so that was every real input; only the
        // '0x0' default parsed "correctly", which is why it went unnoticed (audit #5 Y1).
        //
        // Verified in Cheat Engine's own lua53-64.dll: 0x1F2A3B4C5D0 -> 2141640246736,
        // bare hex 1F2A3B4C5D0 -> the same, decimal 1234 -> 1234, junk -> 0, and every
        // result is a Lua *integer* (math.type), which writeQword requires.
        //
        // Decimal is tried BEFORE bare hex on purpose: this branch also serves
        // NameProperty, whose value is an FName index a user may well type in decimal.
        // Reading "1234" as hex would silently change its meaning.
        if (typeName is "NameProperty" or "ObjectProperty" or "ClassProperty"
            or "SoftObjectProperty" or "SoftClassProperty"
            or "WeakObjectProperty" or "LazyObjectProperty"
            or "InterfaceProperty")
        {
            return $"(function() local s = edits[{editIndex}].Text or ''; " +
                   "s = s:gsub('%s+',''); " +
                   "local h = s:match('^0[xX](%x+)$'); " +
                   "if h then return tonumber(h,16) or 0 end; " +
                   "return tonumber(s) or tonumber(s,16) or 0 end)()";
        }

        // Float types: direct tonumber
        if (typeName is "FloatProperty" or "DoubleProperty")
            return $"tonumber(edits[{editIndex}].Text) or 0.0";

        // Integer types: floor to avoid fractional
        return $"math.floor(tonumber(edits[{editIndex}].Text) or 0)";
    }

    /// <summary>Escape for a Lua single-quoted literal. Forwards to the one
    /// implementation (R2). This copy was the WEAKEST of the three: it handled only
    /// backslash / quote / newline, so CR and TAB survived verbatim and — the real
    /// hazard — so did a closing long bracket, which would terminate AOBMaker's
    /// <c>[==[ … ]==]</c> wrapper around the whole script.</summary>
    private static string EscapeLua(string s) => CeLuaHygiene.EscapeLuaString(s);
}
