using System.Collections.Generic;
using System.Globalization;
using System.Text;
using UE5DumpUI.Models;

namespace UE5DumpUI.Services;

/// <summary>
/// Generates CE memory-record AA Scripts for the movement-tuning knobs (Laufen):
/// Move Speed / Gravity / Super Jump. Each is a STATEFUL toggle (like
/// <see cref="ProtectionScriptGenerator"/>): ticking runs <c>[ENABLE]</c> →
/// mailbox <c>CMD_MOVEMENT=10</c> with the baked percent; unticking runs
/// <c>[DISABLE]</c> → percent 100 (which the DLL treats as OFF / restore base).
///
/// SELF-CONTAINED: talks to the UE5Dumper.dll mailbox directly — no helper Lua.
/// The DLL owns the reflection, the base-value cache, the height→velocity √ (for
/// Super Jump) and the re-assert worker (so the value survives respawns while the
/// record is ticked). The "100% = OFF" rule is decided DLL-side
/// (<c>Laufen::SetKnobPercent</c>), so the script just sends a percentage.
/// </summary>
public static class MovementScriptGenerator
{
    // Mimic mailbox layout (must match dll/src/Mimic.h MailboxData + Cmd):
    //   0x00 cmd (write LAST to trigger) = CMD_MOVEMENT(10)
    //   0x04 status (poll == 1), 0x08 result (1 active / 0 off / negative error)
    //   0x10 instanceAddr = knobId (0 MaxWalkSpeed / 1 GravityScale / 2 JumpZVelocity)
    //   0x328 paramsData[0..7] = double percent (100 = off; knob 2 = jump HEIGHT %)
    private const int CmdMovement = CeMailboxLayout.CmdMovement;

    /// <summary>The three tunable knobs — value is the mailbox knobId.</summary>
    public enum Knob { WalkSpeed = 0, Gravity = 1, Jump = 2 }

    /// <summary>Build a stateful [ENABLE]/[DISABLE] record for one knob baked at
    /// <paramref name="percent"/> (the current slider %). For
    /// <see cref="Knob.Jump"/> the percent is jump HEIGHT %.</summary>
    public static string Generate(Knob knob, double percent)
    {
        string label = Label(knob);
        var sb = new StringBuilder(2048);
        EmitBlock(sb, "[ENABLE]", knob, label, percent, enable: true);
        EmitBlock(sb, "[DISABLE]", knob, label, percent, enable: false);
        return sb.ToString();
    }

    private static void EmitBlock(StringBuilder sb, string header, Knob knob,
        string label, double percent, bool enable)
    {
        // [DISABLE] always sends 100% — the DLL reads that as OFF (restore base).
        double sent = enable ? percent : 100.0;
        Line(sb, header);
        Line(sb, "{$lua}");
        Line(sb, "if syntaxcheck then return end");
        CeLuaHygiene.AppendDebugPreamble(sb);
        if (enable)
        {
            Line(sb, "-- ================================================================");
            Line(sb, $"-- Movement: {label} {Pct(percent)} -- Generated by UE5CEDumper (self-contained) | {CeLuaHygiene.AttributionUrl}");
            Line(sb, $"-- Tick = apply {Pct(percent)} (held by the DLL re-assert worker), untick = OFF.");
            Line(sb, "-- Talks to UE5Dumper.dll's mailbox directly (CMD_MOVEMENT=10). 100% = OFF.");
            Line(sb, $"-- {knob switch { Knob.Jump => "Jump slider is HEIGHT %; the DLL applies sqrt to JumpZVelocity.", _ => "Percent multiplies the captured base value." }}");
            Line(sb, "-- Requires UE5Dumper.dll injected (version.dll proxy or CE inject).");
            Line(sb, "-- ================================================================");
        }
        else
        {
            Line(sb, $"-- Movement: {label} OFF (send 100% -> DLL restores the captured base).");
        }
        Line(sb);
        Line(sb, "local mb = getAddressSafe('g_invokeMailbox')");
        Line(sb, "if not mb or mb == 0 then mb = getAddressSafe('UE5Dumper.g_invokeMailbox') end");
        Line(sb, "if not mb or mb == 0 then");
        if (enable)
        {
            Line(sb, "  showMessage('[Movement] g_invokeMailbox not found -- is UE5Dumper.dll injected?')");
            Line(sb, CeLuaHygiene.DeferredUntickLua("  "));
        }
        Line(sb, "  return");
        Line(sb, "end");
        // Contract check BEFORE the first write (see AppendContractCheck).
        CeLuaHygiene.AppendContractCheck(sb, "Movement",
            enable ? MailboxTimeout.UntickAndReturn : MailboxTimeout.SilentReturn);
        Line(sb);
        // Bounded wait for IDLE before the FIRST write (audit #5 AA10). This
        // generator had no guard at all -- 7 of the 11 mailbox emitters did not, so
        // a toggle fired while another command was still in flight wrote straight
        // over it. Above the OPERAND writes, not merely above the status clear:
        // operands land in the same mailbox, so writing them corrupts the command in
        // flight just as surely -- the same reason the contract check sits here.
        CeLuaHygiene.AppendIdleWaitOrBail(sb, "mb", "Movement",
            enable ? MailboxTimeout.UntickAndReturn : MailboxTimeout.SilentReturn);
        Line(sb, $"writeQword(mb + {CeMailboxLayout.OffInstanceAddr}, {(int)knob})        -- knobId: {label}");
        Line(sb, $"writeDouble(mb + {CeMailboxLayout.OffParamsData}, {Lua(sent)})   -- percent (100 = off)");
        Line(sb, $"writeInteger(mb + {CeMailboxLayout.OffStatus}, 0)        -- clear status");
        Line(sb, $"writeInteger(mb + {CeMailboxLayout.OffCmd}, {CmdMovement})       -- CMD_MOVEMENT (write LAST)");
        // Shared wait: real-time deadline, status-specific diagnosis, and (on ENABLE)
        // the untick that stops a timed-out row claiming to be active.
        CeLuaHygiene.AppendMailboxWait(sb, "Movement",
            enable ? MailboxTimeout.UntickAndReturn : MailboxTimeout.SilentReturn);
        if (enable)
        {
            Line(sb, $"local state = readInteger(mb + {CeMailboxLayout.OffResult}, true)   -- 1=active, 0=off, <0=error");
            Line(sb, $"dbg('[Movement] {label} {Pct(percent)} -> state=' .. tostring(state))");
            Line(sb, "if state < 0 then");
            // Nothing was applied, so the row must not stay ticked (same rule as the
            // timeout path above; this one was missed for the same reason).
            Line(sb, $"  showMessage('[Movement] {label} -- no pawn / no CharacterMovement (enter gameplay first)')");
            Line(sb, CeLuaHygiene.DeferredUntickLua("  "));
            Line(sb, "elseif DEBUG == 0 then");
            Line(sb, $"  {CeLuaHygiene.CloseCall}   -- clean success: close the Lua Engine window");
            Line(sb, "end");
        }
        else
        {
            // [DISABLE] restored the base -- close the window on a clean untick.
            CeLuaHygiene.AppendCloseOnSuccess(sb);
        }
        Line(sb, "{$asm}");
    }

    /// <summary>Build a stateful [ENABLE]/[DISABLE] record for the gravity DIRECTION
    /// vector (UE5.4+) baked at (x,y,z) ∈ [-1,1]. [DISABLE] sends (0,0,0) = OFF
    /// (the DLL restores the captured game default). Pre-5.4 games report
    /// unavailable when ticked.</summary>
    public static string GenerateGravityDirection(double x, double y, double z)
    {
        var sb = new StringBuilder(2048);
        EmitGravDirBlock(sb, "[ENABLE]", x, y, z, enable: true);
        EmitGravDirBlock(sb, "[DISABLE]", x, y, z, enable: false);
        return sb.ToString();
    }

    private static void EmitGravDirBlock(StringBuilder sb, string header,
        double x, double y, double z, bool enable)
    {
        // [DISABLE] always sends (0,0,0) — the DLL reads that as OFF (restore default).
        double sx = enable ? x : 0, sy = enable ? y : 0, sz = enable ? z : 0;
        Line(sb, header);
        Line(sb, "{$lua}");
        Line(sb, "if syntaxcheck then return end");
        CeLuaHygiene.AppendDebugPreamble(sb);
        if (enable)
        {
            Line(sb, "-- ================================================================");
            Line(sb, $"-- Movement: Gravity Direction ({Lua(x)}, {Lua(y)}, {Lua(z)}) -- Generated by UE5CEDumper | {CeLuaHygiene.AttributionUrl}");
            Line(sb, "-- Tick = tilt gravity to this (normalized) direction, untick = OFF (restore default).");
            Line(sb, "-- Talks to UE5Dumper.dll's mailbox directly (CMD_MOVEMENT=10, knobId 3).");
            Line(sb, "-- (0,0,0) = OFF. Needs UE5.4+ with a reflected GravityDirection.");
            Line(sb, "-- ================================================================");
        }
        else
        {
            Line(sb, "-- Movement: Gravity Direction OFF (send (0,0,0) -> DLL restores the game default).");
        }
        Line(sb);
        Line(sb, "local mb = getAddressSafe('g_invokeMailbox')");
        Line(sb, "if not mb or mb == 0 then mb = getAddressSafe('UE5Dumper.g_invokeMailbox') end");
        Line(sb, "if not mb or mb == 0 then");
        if (enable)
        {
            Line(sb, "  showMessage('[Movement] g_invokeMailbox not found -- is UE5Dumper.dll injected?')");
            Line(sb, CeLuaHygiene.DeferredUntickLua("  "));
        }
        Line(sb, "  return");
        Line(sb, "end");
        // Contract check BEFORE the first write (see AppendContractCheck).
        CeLuaHygiene.AppendContractCheck(sb, "Movement",
            enable ? MailboxTimeout.UntickAndReturn : MailboxTimeout.SilentReturn);
        Line(sb);
        // Bounded wait for IDLE before the FIRST write (audit #5 AA10). This
        // generator had no guard at all -- 7 of the 11 mailbox emitters did not, so
        // a toggle fired while another command was still in flight wrote straight
        // over it. Above the OPERAND writes, not merely above the status clear:
        // operands land in the same mailbox, so writing them corrupts the command in
        // flight just as surely -- the same reason the contract check sits here.
        CeLuaHygiene.AppendIdleWaitOrBail(sb, "mb", "Movement",
            enable ? MailboxTimeout.UntickAndReturn : MailboxTimeout.SilentReturn);
        Line(sb, $"writeQword(mb + {CeMailboxLayout.OffInstanceAddr}, 3)        -- knobId 3 = GravityDirection");
        Line(sb, $"writeDouble(mb + {CeMailboxLayout.OffParamsData}, {Lua(sx)})   -- X");
        Line(sb, $"writeDouble(mb + {CeMailboxLayout.OffParamsData1}, {Lua(sy)})   -- Y");
        Line(sb, $"writeDouble(mb + {CeMailboxLayout.OffParamsData2}, {Lua(sz)})   -- Z");
        Line(sb, $"writeInteger(mb + {CeMailboxLayout.OffStatus}, 0)        -- clear status");
        Line(sb, $"writeInteger(mb + {CeMailboxLayout.OffCmd}, {CmdMovement})       -- CMD_MOVEMENT (write LAST)");
        CeLuaHygiene.AppendMailboxWait(sb, "Movement",
            enable ? MailboxTimeout.UntickAndReturn : MailboxTimeout.SilentReturn);
        if (enable)
        {
            Line(sb, $"local state = readInteger(mb + {CeMailboxLayout.OffResult}, true)   -- 1=active, 0=off, <0=error/unavailable");
            Line(sb, "dbg('[Movement] Gravity Direction -> state=' .. tostring(state))");
            Line(sb, "if state < 0 then");
            // Applied nothing -> the row must not stay ticked.
            Line(sb, "  showMessage('[Movement] Gravity Direction -- unavailable (needs UE5.4+) or no pawn.')");
            Line(sb, CeLuaHygiene.DeferredUntickLua("  "));
            Line(sb, "elseif DEBUG == 0 then");
            Line(sb, $"  {CeLuaHygiene.CloseCall}   -- clean success: close the Lua Engine window");
            Line(sb, "end");
        }
        else
        {
            // [DISABLE] restored the default gravity -- close on a clean untick.
            CeLuaHygiene.AppendCloseOnSuccess(sb);
        }
        Line(sb, "{$asm}");
    }

    /// <summary>Build the .CT batch (Move Speed / Gravity / Super Jump + Gravity
    /// Direction) baked at the current slider values, ready for
    /// <see cref="CheatTableBuilder.Build"/>.</summary>
    public static List<CheatTableRow> BuildBatchRows(
        double walkPercent, double gravityPercent, double jumpHeightPercent,
        double gravDirX, double gravDirY, double gravDirZ)
    {
        return new List<CheatTableRow>
        {
            new CtScriptRow
            {
                Category = "Movement",
                Description = $"Move Speed ({Pct(walkPercent)})",
                Script = Generate(Knob.WalkSpeed, walkPercent),
            },
            new CtScriptRow
            {
                Category = "Movement",
                Description = $"Gravity ({Pct(gravityPercent)})",
                Script = Generate(Knob.Gravity, gravityPercent),
            },
            new CtScriptRow
            {
                Category = "Movement",
                Description = $"Super Jump ({Pct(jumpHeightPercent)} height)",
                Script = Generate(Knob.Jump, jumpHeightPercent),
            },
            new CtScriptRow
            {
                Category = "Movement",
                Description = $"Gravity Direction ({Lua(gravDirX)}, {Lua(gravDirY)}, {Lua(gravDirZ)})",
                Script = GenerateGravityDirection(gravDirX, gravDirY, gravDirZ),
            },
        };
    }

    private static string Label(Knob knob) => knob switch
    {
        Knob.WalkSpeed => "Move Speed",
        Knob.Gravity   => "Gravity",
        Knob.Jump      => "Super Jump",
        _              => "Movement",
    };

    private static string Pct(double percent) =>
        percent.ToString("0", CultureInfo.InvariantCulture) + "%";

    private static string Lua(double v) => v.ToString("0.0###", CultureInfo.InvariantCulture);

    private static void Line(StringBuilder sb, string text = "")
    {
        sb.Append(text);
        sb.Append('\n');
    }
}
