using System.Text;

namespace UE5DumpUI.Services;

/// <summary>
/// Generates a CE memory-record AA Script for the GodMode toggle (Solitar).
///
/// A STATEFUL checkbox like <see cref="DebugCameraScriptGenerator"/>: ticking
/// runs <c>[ENABLE]</c> → mailbox <c>CMD_PROTECT</c> op <c>SET_GODMODE</c> value
/// 1 (force <c>AActor::bCanBeDamaged</c> FALSE on the local pawn), unticking runs
/// <c>[DISABLE]</c> → value 0 (restore). SELF-CONTAINED: talks to the
/// UE5Dumper.dll mailbox directly — no <c>ue5_invoke_helper.lua</c> needed. The
/// DLL owns the reflection, the bit write, and the re-assert worker (so the flag
/// survives respawns while the record is ticked).
/// </summary>
public static class ProtectionScriptGenerator
{
    // Mimic mailbox layout (must match dll/src/Mimic.h MailboxData + ProtectOp):
    //   0x00 cmd (write LAST to trigger) = CMD_PROTECT(9)
    //   0x04 status (poll == 1), 0x08 result (observed state / negative error)
    //   0x10 instanceAddr = op  (PROTECT_OP_SET_GODMODE = 0)
    //   0x18 ufuncAddr    = value (1 = ON / 0 = OFF)
    private const int CmdProtect = CeMailboxLayout.CmdProtect;
    private const int OpSetGodMode = 0;

    /// <summary>Build the [ENABLE]/[DISABLE] memory-record script.</summary>
    public static string Generate()
    {
        var sb = new StringBuilder(2048);
        EmitBlock(sb, "[ENABLE]", enable: true);
        EmitBlock(sb, "[DISABLE]", enable: false);
        return sb.ToString();
    }

    private static void EmitBlock(StringBuilder sb, string header, bool enable)
    {
        var label = enable ? "ON" : "OFF";
        var value = enable ? 1 : 0;
        Line(sb, header);
        Line(sb, "{$lua}");
        Line(sb, "if syntaxcheck then return end");
        CeLuaHygiene.AppendDebugPreamble(sb);
        Line(sb, "-- ================================================================");
        Line(sb, $"-- GodMode force {label} -- Generated by UE5CEDumper | {CeLuaHygiene.AttributionUrl}");
        Line(sb, "-- Tick = GodMode ON (AActor.bCanBeDamaged forced FALSE), untick = OFF.");
        Line(sb, "-- SELF-CONTAINED: talks to UE5Dumper.dll's mailbox directly -- no");
        Line(sb, "-- ue5_invoke_helper.lua needed. The DLL resolves the local pawn, writes");
        Line(sb, "-- the bitfield, and re-asserts it on a timer (survives respawns).");
        Line(sb, "-- Requires UE5Dumper.dll injected (version.dll proxy or CE inject).");
        Line(sb, "-- ================================================================");
        Line(sb);

        // Resolve the exported mailbox symbol (tolerate the module-qualified form).
        Line(sb, "local mb = getAddressSafe('g_invokeMailbox')");
        Line(sb, "if not mb or mb == 0 then mb = getAddressSafe('UE5Dumper.g_invokeMailbox') end");
        Line(sb, "if not mb or mb == 0 then");
        Line(sb, "  showMessage('[GodMode] g_invokeMailbox not found -- is " +
                  "UE5Dumper.dll injected?')");
        Line(sb, CeLuaHygiene.DeferredUntickLua("  "));
        Line(sb, "  return");
        Line(sb, "end");
        // Contract check BEFORE the first write: if the layout moved we would
        // otherwise scribble on whatever now lives at those offsets.
        CeLuaHygiene.AppendContractCheck(sb, "GodMode", MailboxTimeout.UntickAndReturn);
        Line(sb);

        // Mailbox round-trip: write op + value, trigger CMD_PROTECT=9, poll status.
        // Bounded wait for IDLE before the FIRST write (audit #5 AA10). This
        // generator had no guard at all -- 7 of the 11 mailbox emitters did not, so
        // a toggle fired while another command was still in flight wrote straight
        // over it. Above the OPERAND writes, not merely above the status clear:
        // operands land in the same mailbox, so writing them corrupts the command in
        // flight just as surely -- the same reason the contract check sits here.
        CeLuaHygiene.AppendIdleWaitOrBail(sb, "mb", "GodMode");
        Line(sb, $"writeQword(mb + {CeMailboxLayout.OffInstanceAddr}, {OpSetGodMode})    -- op: PROTECT_OP_SET_GODMODE");
        Line(sb, $"writeQword(mb + {CeMailboxLayout.OffUfuncAddr}, {value})    -- value: {value} = {label}");
        Line(sb, $"writeInteger(mb + {CeMailboxLayout.OffStatus}, 0)    -- clear status");
        Line(sb, $"writeInteger(mb + {CeMailboxLayout.OffCmd}, {CmdProtect})    -- CMD_PROTECT (write LAST)");
        // Shared wait: real-time deadline, status-specific diagnosis, and the untick
        // that stops a timed-out row claiming to be active.
        CeLuaHygiene.AppendMailboxWait(sb, "GodMode");
        Line(sb, $"local state = readInteger(mb + {CeMailboxLayout.OffResult}, true)   -- 1=immune, 0=can be damaged, <0=error");
        Line(sb, $"dbg('[GodMode] {label} -> state=' .. tostring(state))");
        Line(sb, "if state < 0 then");
        Line(sb, $"  showMessage('[GodMode] {label} -- no pawn? (enter gameplay first)')");
        // Nothing was applied on this branch, so the record must not stay ticked.
        Line(sb, CeLuaHygiene.DeferredUntickLua("  "));
        Line(sb, "elseif DEBUG == 0 then");
        Line(sb, $"  {CeLuaHygiene.CloseCall}   -- clean success: close the Lua Engine window");
        Line(sb, "end");
        Line(sb, "{$asm}");
    }

    /// <summary>Append a line with LF-only ending (no CR) for CE compatibility.</summary>
    private static void Line(StringBuilder sb, string text = "")
    {
        sb.Append(text);
        sb.Append('\n');
    }
}
