using System.Text;

namespace UE5DumpUI.Services;

/// <summary>
/// Generates a CE memory-record AA Script for See-through occluders (Schlacht).
///
/// A STATEFUL checkbox like <see cref="ForegroundScriptGenerator"/>: ticking runs
/// <c>[ENABLE]</c> → mailbox <c>CMD_SEETHROUGH</c> value 1 (the DLL starts a worker
/// that traces the camera→view ray each tick and hides the nearest non-Pawn actor
/// blocking it); unticking runs <c>[DISABLE]</c> → value 0 (un-hide + stop).
/// SELF-CONTAINED: talks to the UE5Dumper.dll mailbox directly — no
/// <c>ue5_invoke_helper.lua</c>. Schlacht owns its own worker thread, so the
/// mailbox round-trip is just a flag flip.
/// </summary>
public static class SeeThroughScriptGenerator
{
    // Mimic mailbox layout (must match dll/src/Mimic.h MailboxData + CMD_SEETHROUGH):
    //   0x00 cmd (write LAST to trigger) = CMD_SEETHROUGH(14)
    //   0x04 status (poll == 1), 0x08 result (1 on / 0 off / <0 error)
    //   0x18 ufuncAddr = value (1 = ON / 0 = OFF)
    private const int CmdSeeThrough = CeMailboxLayout.CmdSeeThrough;

    /// <summary>Build the [ENABLE]/[DISABLE] memory-record script.</summary>
    public static string Generate()
    {
        var sb = new StringBuilder(2048);
        EmitBlock(sb, "[ENABLE]", enable: true);
        EmitBlock(sb, "[DISABLE]", enable: false);
        return sb.ToString();
    }

    private static void EmitBlock(StringBuilder sb, string header, bool enable)
    {
        var label = enable ? "ON" : "OFF";
        var value = enable ? 1 : 0;
        Line(sb, header);
        Line(sb, "{$lua}");
        Line(sb, "if syntaxcheck then return end");
        CeLuaHygiene.AppendDebugPreamble(sb);
        Line(sb, "-- ================================================================");
        Line(sb, $"-- See-through occluders {label} -- Generated by UE5CEDumper | {CeLuaHygiene.AttributionUrl}");
        Line(sb, "-- Tick = the DLL hides the nearest non-Pawn/Character object blocking");
        Line(sb, "-- the camera->view line (so a wall stops covering your view); untick");
        Line(sb, "-- = un-hide + stop. Enemies / NPCs / the player are never hidden.");
        Line(sb, "-- SELF-CONTAINED: talks to UE5Dumper.dll's mailbox directly -- no");
        Line(sb, "-- ue5_invoke_helper.lua needed. Requires UE5Dumper.dll injected");
        Line(sb, "-- (version.dll proxy or CE inject).");
        Line(sb, "-- ================================================================");
        Line(sb);

        // Resolve the exported mailbox symbol (tolerate the module-qualified form).
        Line(sb, "local mb = getAddressSafe('g_invokeMailbox')");
        Line(sb, "if not mb or mb == 0 then mb = getAddressSafe('UE5Dumper.g_invokeMailbox') end");
        Line(sb, "if not mb or mb == 0 then");
        Line(sb, "  showMessage('[SeeThrough] g_invokeMailbox not found -- is " +
                  "UE5Dumper.dll injected?')");
        Line(sb, "  if memrec then memrec.Active = false end");
        Line(sb, "  return");
        Line(sb, "end");
        // Contract check BEFORE the first write: if the layout moved we would
        // otherwise scribble on whatever now lives at those offsets.
        CeLuaHygiene.AppendContractCheck(sb, "SeeThrough", MailboxTimeout.UntickAndReturn);
        Line(sb);

        // Pierce depth: how many nearest objects to see through. EDIT `pierceCount`
        // below (1 = just the nearest object; 2 = it + the wall behind; …). Only the
        // [ENABLE] block sends it; [DISABLE] sends 0 (ignored).
        if (enable)
        {
            Line(sb, "local pierceCount = 1   -- EDIT ME: how many nearest objects to see through (1 = nearest only)");
        // Bounded wait for IDLE before the FIRST write (audit #5 AA10). This
        // generator had no guard at all -- 7 of the 11 mailbox emitters did not, so
        // a toggle fired while another command was still in flight wrote straight
        // over it. Above the OPERAND writes, not merely above the status clear:
        // operands land in the same mailbox, so writing them corrupts the command in
        // flight just as surely -- the same reason the contract check sits here.
        CeLuaHygiene.AppendIdleWaitOrBail(sb, "mb", "SeeThrough");
            Line(sb, $"writeQword(mb + {CeMailboxLayout.OffInstanceAddr}, pierceCount)    -- pierce depth (>=1)");
        }
        else
        {
            Line(sb, $"writeQword(mb + {CeMailboxLayout.OffInstanceAddr}, 0)    -- pierce depth ignored on OFF");
        }
        // Mailbox round-trip: write value, trigger CMD_SEETHROUGH=14, poll status.
        Line(sb, $"writeQword(mb + {CeMailboxLayout.OffUfuncAddr}, {value})    -- value: {value} = {label}");
        Line(sb, $"writeInteger(mb + {CeMailboxLayout.OffStatus}, 0)    -- clear status");
        Line(sb, $"writeInteger(mb + {CeMailboxLayout.OffCmd}, {CmdSeeThrough})    -- CMD_SEETHROUGH (write LAST)");
        // Shared wait: real-time deadline, status-specific diagnosis, and the untick
        // that stops a timed-out row claiming to be active.
        CeLuaHygiene.AppendMailboxWait(sb, "SeeThrough");
        Line(sb, $"local state = readInteger(mb + {CeMailboxLayout.OffResult}, true)   -- 1=on, 0=off, <0=error");
        Line(sb, $"dbg('[SeeThrough] {label} -> state=' .. tostring(state))");
        Line(sb, "if state < 0 then");
        Line(sb, $"  showMessage('[SeeThrough] {label} failed (error ' .. tostring(state) .. ')')");
        // Nothing was applied on this branch, so the record must not stay ticked.
        Line(sb, "  if memrec then memrec.Active = false end");
        Line(sb, "elseif DEBUG == 0 then");
        Line(sb, $"  {CeLuaHygiene.CloseCall}   -- clean success: close the Lua Engine window");
        Line(sb, "end");
        Line(sb, "{$asm}");
    }

    /// <summary>Append a line with LF-only ending (no CR) for CE compatibility.</summary>
    private static void Line(StringBuilder sb, string text = "")
    {
        sb.Append(text);
        sb.Append('\n');
    }
}
