using System.Globalization;
using System.Text;
using UE5DumpUI.Models;

namespace UE5DumpUI.Services;

/// <summary>
/// Generates per-action CE memory-record AA Scripts for Teleport — the CE
/// integration path. Ship them straight into the table via AOBMaker
/// (<c>CreateAAScript</c>), or batch them into a .CT via
/// <see cref="CheatTableBuilder"/>.
///
/// Every teleport action is MOMENTARY (not a stateful toggle like Debug
/// Camera), so each record's <c>[ENABLE]</c> fires the mailbox round-trip then
/// schedules a deferred self-untick (<c>createTimer</c>) so the checkbox clears
/// itself ~50 ms later; <c>[DISABLE]</c> is a nop. Self-contained: talks to the
/// Mimic mailbox directly, no helper-Lua dependency.
///
/// Hotkeys: bind a CE <b>record-level</b> hotkey to a record (reliable), or use
/// the app's own OS-level global hotkeys on the Teleport tab. The old
/// <c>createHotkey</c> Lua "hotkey bundle" was REMOVED (build 1111) — it never
/// reliably fired in CE and had been unsurfaced (no UI button) since build 1038.
/// </summary>
public static class TeleportScriptGenerator
{
    // Mailbox layout — see dll/src/Mimic.h (MailboxData / TeleportOp).
    private const int CmdTeleport = CeMailboxLayout.CmdTeleport;

    public enum Action
    {
        Save, Recall, RecallLast, BugIt, BugItGo, Cursor, GetPov, ClearAll,
        Relative, Explicit, CursorOn, CursorOff, GetPose,
    }

    /// <summary>Build the [ENABLE]/[DISABLE] AA Script body for one action.
    /// <paramref name="distance"/>/<paramref name="horizontal"/> apply to
    /// <see cref="Action.Relative"/>; the <paramref name="coordX"/>… and
    /// <paramref name="hasRot"/>/<paramref name="pitch"/>… apply to
    /// <see cref="Action.Explicit"/>.</summary>
    public static string Generate(Action action, int slot = 0,
        double zOffset = 100.0, int channel = 0, bool fallbackCenter = true,
        double distance = 100.0, bool horizontal = true,
        double coordX = 0, double coordY = 0, double coordZ = 0,
        bool hasRot = false, double pitch = 0, double yaw = 0, double roll = 0)
    {
        if (action == Action.ClearAll)
            return GenerateClearAll();

        int op = action switch
        {
            Action.Save => 1,
            Action.Recall => 2,
            Action.RecallLast => 7,   // TP_OP_RECALL_LAST (slot ignored)
            Action.BugIt => 9,        // TP_OP_BUGIT_SAVE  (store current pose)
            Action.BugItGo => 10,     // TP_OP_BUGIT_GO    (go to stored pose)
            Action.Cursor => 4,
            Action.GetPov => 11,      // TP_OP_GET_POV     (read camera POV)
            Action.Relative => 12,    // TP_OP_RELATIVE    (move along facing)
            Action.Explicit => 13,    // TP_OP_EXPLICIT    (go to coordinates)
            Action.CursorOn => 14,    // TP_OP_SET_CURSOR  (slot field = 1)
            Action.CursorOff => 14,   // TP_OP_SET_CURSOR  (slot field = 0)
            Action.GetPose => 0,      // TP_OP_GET_POSE    (read current coords)
            _ => 2,
        };
        // For SET_CURSOR the slot/ufuncAddr field carries the show flag (1/0).
        int slotField = action switch
        {
            Action.CursorOn => 1,
            Action.CursorOff => 0,
            _ => slot,
        };
        string label = action switch
        {
            Action.Save => $"Save marker {slot + 1}",
            Action.Recall => $"Recall marker {slot + 1}",
            Action.RecallLast => "Recall last",
            Action.BugIt => "BugIt (store pose)",
            Action.BugItGo => "BugItGo (go to stored)",
            Action.Cursor => "Teleport to cursor",
            Action.GetPov => "Get camera POV",
            Action.Relative => "Teleport facing direction",
            Action.Explicit => "Teleport to coordinates",
            Action.CursorOn => "Cursor ON",
            Action.CursorOff => "Cursor OFF",
            Action.GetPose => "Get current coords",
            _ => "Teleport",
        };

        var sb = new StringBuilder(2048);
        Line(sb, "[ENABLE]");
        Line(sb, "{$lua}");
        Line(sb, "if syntaxcheck then return end");
        CeLuaHygiene.AppendDebugPreamble(sb);
        Line(sb, "-- ================================================================");
        Line(sb, $"-- Teleport: {label} -- Generated by UE5CEDumper (self-contained) | {CeLuaHygiene.AttributionUrl}");
        Line(sb, "-- Momentary action: fires once, then auto-unticks. Talks to");
        Line(sb, $"-- UE5Dumper.dll's mailbox directly (CMD_TELEPORT={CmdTeleport}). Requires the");
        Line(sb, "-- DLL injected (version.dll proxy or CE inject).");
        Line(sb, "-- ================================================================");
        Line(sb);
        Line(sb, "local mb = getAddressSafe('g_invokeMailbox')");
        Line(sb, "if not mb or mb == 0 then mb = getAddressSafe('UE5Dumper.g_invokeMailbox') end");
        Line(sb, "if not mb or mb == 0 then");
        Line(sb, "  showMessage('[Teleport] g_invokeMailbox not found -- is UE5Dumper.dll injected?')");
        Line(sb, CeLuaHygiene.DeferredUntickLua("  "));
        Line(sb, "  return");
        Line(sb, "end");
        // Contract check BEFORE the first write. UntickAndReturn even though these
        // rows are momentary: the deferred untick timer is created further down, so
        // at THIS point a bare return would reach nothing (see AppendBail).
        CeLuaHygiene.AppendContractCheck(sb, "Teleport");
        Line(sb);
        Line(sb, "local hadError = false");
        // Bounded wait for IDLE before sampling cmd. This is the R3 fix, and it reached
        // GenerateClearAll (below) and CoordLibrary but never got applied HERE — where
        // back-to-back firing is the ORDINARY use: hotkey-spamming "TP facing direction",
        // or Save immediately followed by Recall. A single sample meant the whole
        // round-trip below was skipped with no else branch: nothing written, no message,
        // hadError still false — so the deferred timer closed the window as if it were a
        // clean success. A silent no-op that looks like it worked is the worst outcome
        // this file can produce, and it affected 16 of the 17 shipped rows.
        // hadError is set AT the break, not only in the else below: a bare `then break end`
        // is exactly the silent-timeout shape CeLuaHygieneTests forbids, and the rule is
        // right — the flag has to be true from the moment the wait gives up. The message
        // lives in the else so it is emitted once.
        CeLuaHygiene.AppendIdleWait(sb, "mb", "hadError = true; break");
        Line(sb, $"if readInteger(mb + {CeMailboxLayout.OffCmd}) == 0 then");
        if (op == 4)
        {
            Line(sb, $"  writeDouble(mb + {CeMailboxLayout.OffParamsData}, {Lua(zOffset)})   -- zOffset");
            Line(sb, $"  writeBytes(mb + {CeMailboxLayout.OffParamsData1}, {channel & 0xFF})            -- trace channel");
            Line(sb, $"  writeBytes(mb + 0x331, {(fallbackCenter ? 1 : 0)})            -- fall back to screen center");
        }
        else if (op == 12)
        {
            Line(sb, $"  writeDouble(mb + {CeMailboxLayout.OffParamsData}, {Lua(distance)})  -- distance (uu; -ve = backward)");
            Line(sb, $"  writeBytes(mb + {CeMailboxLayout.OffParamsData1}, {(horizontal ? 0 : 1)})            -- mode (0 = horizontal, 1 = 3D)");
        }
        else if (op == 13)
        {
            Line(sb, $"  writeDouble(mb + {CeMailboxLayout.OffParamsData}, {Lua(coordX)})  -- X");
            Line(sb, $"  writeDouble(mb + {CeMailboxLayout.OffParamsData1}, {Lua(coordY)})  -- Y");
            Line(sb, $"  writeDouble(mb + {CeMailboxLayout.OffParamsData2}, {Lua(coordZ)})  -- Z");
            Line(sb, $"  writeDouble(mb + 0x340, {Lua(pitch)})  -- Pitch");
            Line(sb, $"  writeDouble(mb + 0x348, {Lua(yaw)})  -- Yaw");
            Line(sb, $"  writeDouble(mb + 0x350, {Lua(roll)})  -- Roll");
            Line(sb, $"  writeBytes(mb + 0x358, {(hasRot ? 1 : 0)})            -- hasRot (restore rotation)");
        }
        Line(sb, $"  writeQword(mb + {CeMailboxLayout.OffUfuncAddr}, {slotField})           -- slot / show flag");
        Line(sb, $"  writeQword(mb + {CeMailboxLayout.OffInstanceAddr}, {op})             -- op");
        Line(sb, $"  writeInteger(mb + {CeMailboxLayout.OffStatus}, 0)             -- clear status");
        Line(sb, $"  writeInteger(mb + {CeMailboxLayout.OffCmd}, {CmdTeleport})  -- CMD_TELEPORT (write LAST)");
        // A timeout is an ERROR (CLAUDE.md's CE-Lua hygiene rule). A bare `break` fell
        // straight through to the auto-close, so the Lua Engine window shut on the one
        // outcome the user needed to see. A bare `return` would be wrong too — it would
        // strand the record ticked — so set hadError, say so, and leave the loop. (B15)
        //
        // That reasoning is why this passes FlagAndBreak rather than the toggles'
        // UntickAndReturn: these rows are MOMENTARY, and the deferred timer below both
        // unticks and suppresses the close. What the shared emitter adds is the half
        // B15 did not cover — a real getTickCount deadline instead of a count of
        // sleep(1) calls (measured 15.47 ms each, so the old bound was ~155 s), and a
        // message that reads `status` rather than guessing at the cause.
        CeLuaHygiene.AppendMailboxWait(sb, "Teleport", MailboxTimeout.FlagAndBreak, indent: "  ");
        Line(sb, $"  local code = readInteger(mb + {CeMailboxLayout.OffResult}, true)");
        Line(sb, $"  dbg('[Teleport] {label} -> code=' .. code)");
        if (op == 11)
        {
            // POV block (op 11 out): [0..47] cam X,Y,Z,Pitch,Yaw,Roll, [48..55] FOV.
            Line(sb, "  if code == 0 then");
            Line(sb, "    dbg(string.format('[Teleport] camera loc=(%.2f, %.2f, %.2f) " +
                     "rot=(%.2f, %.2f, %.2f) fov=%.1f',");
            Line(sb, $"      readDouble(mb + {CeMailboxLayout.OffParamsData}), readDouble(mb + {CeMailboxLayout.OffParamsData1}), readDouble(mb + {CeMailboxLayout.OffParamsData2}),");
            Line(sb, "      readDouble(mb + 0x340), readDouble(mb + 0x348), readDouble(mb + 0x350),");
            Line(sb, "      readDouble(mb + 0x358)))");
            Line(sb, "  end");
        }
        if (op == 0)
        {
            // GET_POSE block (op 0 out): [0..47] X,Y,Z,Pitch,Yaw,Roll (6 doubles).
            // The 6 values are left in the mailbox paramsData for Lua to read.
            Line(sb, "  if code == 0 then");
            Line(sb, "    dbg(string.format('[Teleport] coords loc=(%.3f, %.3f, %.3f) " +
                     "rot=(%.3f, %.3f, %.3f)',");
            Line(sb, $"      readDouble(mb + {CeMailboxLayout.OffParamsData}), readDouble(mb + {CeMailboxLayout.OffParamsData1}), readDouble(mb + {CeMailboxLayout.OffParamsData2}),");
            Line(sb, "      readDouble(mb + 0x340), readDouble(mb + 0x348), readDouble(mb + 0x350)))");
            Line(sb, "  end");
        }
        // Both arms are gated on `not hadError`: a timeout BREAKS out of the wait, so
        // `code` then holds whatever the PREVIOUS command left in the mailbox. Ungated,
        // a stale -7 would pop "marker saved on another map" on top of the timeout
        // dialog and send the user chasing a fault that did not happen.
        Line(sb, "  if not hadError and code == -7 then");
        Line(sb, "    hadError = true");
        Line(sb, "    showMessage('[Teleport] marker saved on another map -- recall refused. " +
                 "Use the UI Force button.')");
        // Wirbel defines TEN negative codes; only -7 had a message, so the other nine
        // (-6 empty marker, -8 no hit, -9 no cursor, ...) reached dbg() — silent at the
        // shipped DEBUG==0 — left hadError false, and closed the window. "Recall marker
        // 2" on an empty slot looked exactly like a successful recall. Report the rest
        // generically rather than inventing per-code prose the DLL can outgrow.
        Line(sb, "  elseif not hadError and code < 0 then");
        Line(sb, "    hadError = true");
        Line(sb, $"    showMessage('[Teleport] {label} failed (code ' .. tostring(code) .. ')')");
        Line(sb, "  end");
        Line(sb, "else");
        // The idle wait above expired with the mailbox still busy. Say so once, and keep
        // hadError set so the window stays open instead of closing on a no-op.
        Line(sb, "  hadError = true");
        Line(sb, "  showMessage('[Teleport] mailbox busy -- the previous command has not " +
                 "finished yet. Try again.')");
        Line(sb, "end");
        Line(sb);
        Line(sb, "-- Deferred self-untick (avoids reentrancy on the activating thread).");
        Line(sb, "-- On a clean fire (DEBUG off, no error) it also closes the Lua Engine window.");
        Line(sb, "local t = createTimer(nil)");
        Line(sb, "t.Interval = 50");
        Line(sb, "t.OnTimer = function(timer)");
        Line(sb, "  timer.destroy()");
        Line(sb, "  if memrec then memrec.Active = false end");
        Line(sb, $"  if DEBUG == 0 and not hadError then {CeLuaHygiene.CloseCall} end");
        Line(sb, "end");
        Line(sb, "{$asm}");
        Line(sb, "[DISABLE]");
        Line(sb, "{$lua}");
        Line(sb, "-- momentary action -- nothing to undo");
        Line(sb, "{$asm}");
        return sb.ToString();
    }

    // Clears all 3 marker slots in one momentary record (op 6 = TP_OP_CLEAR_MARKER
    // per slot). Self-contained mailbox loop; auto-unticks like the others.
    private static string GenerateClearAll()
    {
        var sb = new StringBuilder(1536);
        Line(sb, "[ENABLE]");
        Line(sb, "{$lua}");
        Line(sb, "if syntaxcheck then return end");
        CeLuaHygiene.AppendDebugPreamble(sb);
        // This generator had no hadError at all, so its close was unconditional. (B15)
        Line(sb, "local hadError = false");
        Line(sb, "-- ================================================================");
        Line(sb, "-- Teleport: Clear all markers -- Generated by UE5CEDumper");
        Line(sb, "-- Momentary action: clears slots 1-3, then auto-unticks.");
        Line(sb, "-- ================================================================");
        Line(sb);
        Line(sb, "local mb = getAddressSafe('g_invokeMailbox')");
        Line(sb, "if not mb or mb == 0 then mb = getAddressSafe('UE5Dumper.g_invokeMailbox') end");
        Line(sb, "if not mb or mb == 0 then");
        Line(sb, "  showMessage('[Teleport] g_invokeMailbox not found -- is UE5Dumper.dll injected?')");
        Line(sb, CeLuaHygiene.DeferredUntickLua("  "));
        Line(sb, "  return");
        Line(sb, "end");
        // Contract check BEFORE the first write. UntickAndReturn even though these
        // rows are momentary: the deferred untick timer is created further down, so
        // at THIS point a bare return would reach nothing (see AppendBail).
        CeLuaHygiene.AppendContractCheck(sb, "Teleport");
        Line(sb);
        Line(sb, "for slot = 0, 2 do");
        // R3: this used to sample cmd ONCE and silently SKIP the slot when it was
        // non-zero — clearing 2 of 3 markers and reporting "all markers cleared". And
        // three back-to-back round-trips is precisely the shape that trips the
        // status-before-cmd publication order.
        CeLuaHygiene.AppendIdleWait(sb, "mb",
            "hadError = true; showMessage('[Teleport] mailbox busy -- markers not cleared'); break", "  ");
        Line(sb, $"  if readInteger(mb + {CeMailboxLayout.OffCmd}) == 0 then");
        Line(sb, $"    writeQword(mb + {CeMailboxLayout.OffUfuncAddr}, slot)            -- slot");
        Line(sb, $"    writeQword(mb + {CeMailboxLayout.OffInstanceAddr}, 6)               -- op = CLEAR_MARKER");
        Line(sb, $"    writeInteger(mb + {CeMailboxLayout.OffStatus}, 0)             -- clear status");
        Line(sb, $"    writeInteger(mb + {CeMailboxLayout.OffCmd}, {CmdTeleport})  -- CMD_TELEPORT (write LAST)");
        // Same shape as the single-op wait above: momentary row, so flag and break.
        CeLuaHygiene.AppendMailboxWait(sb, "Teleport", MailboxTimeout.FlagAndBreak, indent: "    ");
        Line(sb, "  end");
        Line(sb, "end");
        Line(sb, "if not hadError then dbg('[Teleport] all markers cleared') end");
        Line(sb);
        Line(sb, "local t = createTimer(nil)");
        Line(sb, "t.Interval = 50");
        Line(sb, "t.OnTimer = function(timer)");
        Line(sb, "  timer.destroy()");
        Line(sb, "  if memrec then memrec.Active = false end");
        Line(sb, $"  if DEBUG == 0 and not hadError then {CeLuaHygiene.CloseCall} end");
        Line(sb, "end");
        Line(sb, "{$asm}");
        Line(sb, "[DISABLE]");
        Line(sb, "{$lua}");
        Line(sb, "-- momentary action -- nothing to undo");
        Line(sb, "{$asm}");
        return sb.ToString();
    }

    /// <summary>Build the standard 17-row .CT batch (Save 1-3, Recall 1-3,
    /// Recall last, BugIt, BugItGo, Cursor, Get POV, Get coords, TP facing dir,
    /// TP to coords, Cursor ON, Cursor OFF, Clear all) ready for
    /// <see cref="CheatTableBuilder.Build"/>.</summary>
    public static List<CheatTableRow> BuildBatchRows(
        double zOffset = 100.0, int channel = 0, bool fallbackCenter = true,
        double distance = 100.0, bool horizontal = true,
        double coordX = 0, double coordY = 0, double coordZ = 0,
        bool hasRot = false, double pitch = 0, double yaw = 0, double roll = 0)
    {
        var rows = new List<CheatTableRow>();
        for (int i = 0; i < 3; i++)
            rows.Add(new CtScriptRow
            {
                Category = "Teleport",
                Description = $"Save marker {i + 1}",
                Script = Generate(Action.Save, i),
            });
        for (int i = 0; i < 3; i++)
            rows.Add(new CtScriptRow
            {
                Category = "Teleport",
                Description = $"Recall marker {i + 1}",
                Script = Generate(Action.Recall, i),
            });
        rows.Add(new CtScriptRow
        {
            Category = "Teleport",
            Description = "Recall last",
            Script = Generate(Action.RecallLast),
        });
        rows.Add(new CtScriptRow
        {
            Category = "Teleport",
            Description = "BugIt (store pose)",
            Script = Generate(Action.BugIt),
        });
        rows.Add(new CtScriptRow
        {
            Category = "Teleport",
            Description = "BugItGo (go to stored)",
            Script = Generate(Action.BugItGo),
        });
        rows.Add(new CtScriptRow
        {
            Category = "Teleport",
            Description = "Teleport to cursor",
            Script = Generate(Action.Cursor, 0, zOffset, channel, fallbackCenter),
        });
        rows.Add(new CtScriptRow
        {
            Category = "Teleport",
            Description = "Get camera POV",
            Script = Generate(Action.GetPov),
        });
        rows.Add(new CtScriptRow
        {
            Category = "Teleport",
            Description = "Get current coords",
            Script = Generate(Action.GetPose),
        });
        rows.Add(new CtScriptRow
        {
            Category = "Teleport",
            Description = "TP facing direction",
            Script = Generate(Action.Relative, 0, zOffset, channel, fallbackCenter,
                distance, horizontal),
        });
        rows.Add(new CtScriptRow
        {
            Category = "Teleport",
            Description = "TP to coordinates",
            Script = Generate(Action.Explicit, 0, zOffset, channel, fallbackCenter,
                distance, horizontal, coordX, coordY, coordZ, hasRot, pitch, yaw, roll),
        });
        rows.Add(new CtScriptRow
        {
            Category = "Teleport",
            Description = "Cursor ON",
            Script = Generate(Action.CursorOn),
        });
        rows.Add(new CtScriptRow
        {
            Category = "Teleport",
            Description = "Cursor OFF",
            Script = Generate(Action.CursorOff),
        });
        rows.Add(new CtScriptRow
        {
            Category = "Teleport",
            Description = "Clear all markers",
            Script = Generate(Action.ClearAll),
        });
        return rows;
    }

    private static string Lua(double v) => v.ToString("0.0###", CultureInfo.InvariantCulture);

    private static void Line(StringBuilder sb, string text = "")
    {
        sb.Append(text);
        sb.Append('\n');
    }
}
