using System.Collections.Generic;
using System.Globalization;
using System.Text;
using UE5DumpUI.Models;

namespace UE5DumpUI.Services;

/// <summary>
/// Generates CE memory-record AA Scripts for the time-dilation levers (Hemmung):
/// whole-world <c>AWorldSettings::TimeDilation</c> and per-pawn
/// <c>AActor::CustomTimeDilation</c>. Each is a STATEFUL toggle (like
/// <see cref="MovementScriptGenerator"/>): ticking runs <c>[ENABLE]</c> → mailbox
/// <c>CMD_TIME=15</c> with op <c>SET</c> and the baked value; unticking runs
/// <c>[DISABLE]</c> → op <c>RESET</c> (the DLL restores the captured natural value
/// and stops holding).
///
/// SELF-CONTAINED: talks to the UE5Dumper.dll mailbox directly — no helper Lua.
/// The DLL owns the reflection (WorldSettings / pawn resolution), the natural-value
/// cache and the re-assert worker (so the dilation survives level loads / respawns
/// while the record is ticked). Unlike the movement knobs (100% = OFF), time uses an
/// explicit RESET op for OFF because 1.0× is a valid "lock at normal speed" state.
/// </summary>
public static class TimeDilationScriptGenerator
{
    // Mimic mailbox layout (must match dll/src/Mimic.h MailboxData + Cmd + TimeOp):
    //   0x00 cmd (write LAST to trigger) = CMD_TIME(15)
    //   0x04 status (poll == 1), 0x08 result (1 active / 0 off / negative error)
    //   0x10 instanceAddr = op (0 SET / 1 RESET)
    //   0x18 ufuncAddr    = target (0 global / 1 pawn)
    //   0x328 paramsData[0..7] = double value (SET only; 1.0 = normal, 0 = frozen)
    private const int CmdTime = CeMailboxLayout.CmdTime;

    /// <summary>The two dilation levers — value is the mailbox target.</summary>
    public enum Target { Global = 0, Pawn = 1 }

    /// <summary>Build a stateful [ENABLE]/[DISABLE] record for one lever baked at
    /// <paramref name="value"/> (the absolute dilation: 1.0 = normal, 0.5 = half,
    /// 0 = frozen). Tick holds the value (re-asserted by the DLL); untick resets.</summary>
    public static string Generate(Target target, double value)
    {
        string label = Label(target);
        var sb = new StringBuilder(2048);
        EmitBlock(sb, "[ENABLE]", target, label, value, enable: true);
        EmitBlock(sb, "[DISABLE]", target, label, value, enable: false);
        return sb.ToString();
    }

    private static void EmitBlock(StringBuilder sb, string header, Target target,
        string label, double value, bool enable)
    {
        int op = enable ? CeMailboxLayout.TimeOpSet : CeMailboxLayout.TimeOpReset;
        Line(sb, header);
        Line(sb, "{$lua}");
        Line(sb, "if syntaxcheck then return end");
        CeLuaHygiene.AppendDebugPreamble(sb);
        if (enable)
        {
            Line(sb, "-- ================================================================");
            Line(sb, $"-- Time: {label} {Mult(value)} -- Generated by UE5CEDumper (self-contained) | {CeLuaHygiene.AttributionUrl}");
            Line(sb, "-- Time Dilation: slow-mo / bullet time / freeze / fast-forward");
            Line(sb, $"-- Tick = hold {Mult(value)} (re-asserted by the DLL worker), untick = OFF (restore natural).");
            Line(sb, "-- Talks to UE5Dumper.dll's mailbox directly (CMD_TIME=15, op SET/RESET).");
            Line(sb, $"-- {(target == Target.Global ? "Whole-world AWorldSettings.TimeDilation (everything slows)." : "Per-pawn AActor.CustomTimeDilation (the player only).")}");
            Line(sb, "-- World + Player are INDEPENDENT records held by the DLL -- tick BOTH at");
            Line(sb, "-- once for bullet time (effective pawn rate = world x pawn: World 0.5x +");
            Line(sb, "-- Player 2x = the player at normal speed in a half-speed world). Enabling");
            Line(sb, "-- one never disturbs the other.");
            Line(sb, "-- 1x = normal, 0.5x = half speed, 0 = frozen (a literal 0 can destabilise");
            Line(sb, "-- physics on some games -- use a small value like 0.05x). Requires");
            Line(sb, "-- UE5Dumper.dll injected (version.dll proxy or CE inject).");
            Line(sb, "-- ================================================================");
        }
        else
        {
            Line(sb, $"-- Time: {label} OFF (op RESET -> DLL restores the captured natural value).");
        }
        Line(sb);
        Line(sb, "local mb = getAddressSafe('g_invokeMailbox')");
        Line(sb, "if not mb or mb == 0 then mb = getAddressSafe('UE5Dumper.g_invokeMailbox') end");
        Line(sb, "if not mb or mb == 0 then");
        if (enable)
        {
            Line(sb, "  showMessage('[Time] g_invokeMailbox not found -- is UE5Dumper.dll injected?')");
            Line(sb, CeLuaHygiene.DeferredUntickLua("  "));
        }
        Line(sb, "  return");
        Line(sb, "end");
        // Contract check BEFORE the first write (see AppendContractCheck).
        CeLuaHygiene.AppendContractCheck(sb, "Time",
            enable ? MailboxTimeout.UntickAndReturn : MailboxTimeout.SilentReturn);
        Line(sb);
        // Bounded wait for IDLE before the FIRST write (audit #5 AA10). This
        // generator had no guard at all -- 7 of the 11 mailbox emitters did not, so
        // a toggle fired while another command was still in flight wrote straight
        // over it. Above the OPERAND writes, not merely above the status clear:
        // operands land in the same mailbox, so writing them corrupts the command in
        // flight just as surely -- the same reason the contract check sits here.
        CeLuaHygiene.AppendIdleWaitOrBail(sb, "mb", "Time",
            enable ? MailboxTimeout.UntickAndReturn : MailboxTimeout.SilentReturn);
        Line(sb, $"writeQword(mb + {CeMailboxLayout.OffInstanceAddr}, {op})        -- op: {(enable ? "SET" : "RESET")}");
        Line(sb, $"writeQword(mb + {CeMailboxLayout.OffUfuncAddr}, {(int)target})        -- target: {label}");
        if (enable)
            Line(sb, $"writeDouble(mb + {CeMailboxLayout.OffParamsData}, {Lua(value)})   -- dilation (1.0 = normal)");
        Line(sb, $"writeInteger(mb + {CeMailboxLayout.OffStatus}, 0)        -- clear status");
        Line(sb, $"writeInteger(mb + {CeMailboxLayout.OffCmd}, {CmdTime})       -- CMD_TIME (write LAST)");
        // Shared wait: real-time deadline, status-specific diagnosis, and (on ENABLE)
        // the untick that stops a timed-out row claiming to be active.
        CeLuaHygiene.AppendMailboxWait(sb, "Time",
            enable ? MailboxTimeout.UntickAndReturn : MailboxTimeout.SilentReturn);
        if (enable)
        {
            Line(sb, $"local state = readInteger(mb + {CeMailboxLayout.OffResult}, true)   -- 1=active, 0=off, <0=error");
            Line(sb, $"dbg('[Time] {label} {Mult(value)} -> state=' .. tostring(state))");
            Line(sb, "if state < 0 then");
            Line(sb, $"  showMessage('[Time] {label} -- {(target == Target.Global ? "no WorldSettings (enter a level first)" : "no player pawn (enter gameplay first)")}.')");
            // Applied nothing -> the row must not stay ticked.
            Line(sb, CeLuaHygiene.DeferredUntickLua("  "));
            Line(sb, "elseif DEBUG == 0 then");
            Line(sb, $"  {CeLuaHygiene.CloseCall}   -- clean success: close the Lua Engine window");
            Line(sb, "end");
        }
        else
        {
            // [DISABLE] reset the lever -- close the window on a clean untick.
            CeLuaHygiene.AppendCloseOnSuccess(sb);
        }
        Line(sb, "{$asm}");
    }

    /// <summary>Build the .CT batch (both levers) baked at a single shared
    /// <paramref name="value"/>. Convenience overload of
    /// <see cref="BuildBatchRows(double, double)"/>.</summary>
    public static List<CheatTableRow> BuildBatchRows(double value)
        => BuildBatchRows(value, value);

    /// <summary>Build the .CT batch (both levers) with INDEPENDENT per-lever values —
    /// the whole-world dilation baked at <paramref name="worldValue"/> and the pawn at
    /// <paramref name="pawnValue"/> (e.g. World 0.5× + Player 2× = bullet time). The
    /// two records are stateful toggles held simultaneously by the DLL worker; edit
    /// each in CE (or re-export) to retune. Ready for
    /// <see cref="CheatTableBuilder.Build"/>.</summary>
    public static List<CheatTableRow> BuildBatchRows(double worldValue, double pawnValue)
    {
        return new List<CheatTableRow>
        {
            new CtScriptRow
            {
                Category = "Time",
                Description = $"Time: World {Mult(worldValue)}",
                Script = Generate(Target.Global, worldValue),
            },
            new CtScriptRow
            {
                Category = "Time",
                Description = $"Time: Player {Mult(pawnValue)}",
                Script = Generate(Target.Pawn, pawnValue),
            },
        };
    }

    private static string Label(Target target) => target switch
    {
        Target.Global => "World",
        Target.Pawn   => "Player",
        _             => "Time",
    };

    private static string Mult(double value) =>
        value.ToString("0.0##", CultureInfo.InvariantCulture) + "x";

    private static string Lua(double v) => v.ToString("0.0###", CultureInfo.InvariantCulture);

    private static void Line(StringBuilder sb, string text = "")
    {
        sb.Append(text);
        sb.Append('\n');
    }
}
