// ============================================================
// Lugner_Winmm -- winmm.dll forwarding proxy (data + resolver half)
//
// Compiled only for UE5_PROXY_WINMM_BUILD. Resolves the real winmm.dll
// exports from System32 into mProcs[], which the asm jmp-thunks in
// Lugner_Winmm.asm jump through. ProxyWinmm.def maps each Windows
// export name to its thunk.
//
// Forwarding goes through signature-agnostic asm jmp trampolines rather
// than C forwarders: a bare jmp preserves every register, the stack and
// the return address, so it forwards a call of ANY signature. winmm.dll
// exports undocumented internals whose prototypes we do not know.
//
// LAZY resolution -- the real exports are resolved on the FIRST forwarded
// call, NOT eagerly in DllMain. Resolving in DllMain would LoadLibrary
// under the loader lock while the EXE's static imports are still being
// initialised; that crashed Octopath Traveler through the dxgi proxy. The
// first forwarded call runs on a game thread after DllMain returns.
//
// Generated by scripts/gen_proxy_forwarders.py from the real
// System32 winmm.dll. DO NOT EDIT BY HAND -- re-run the generator.
// ============================================================

#ifdef UE5_PROXY_WINMM_BUILD

#include <Windows.h>
#include <cstdint>
#define LOG_CAT "PROXY"
#include "Sein.h"
#include "Lugner.h"

// Real winmm.dll export addresses, indexed to match the f<N> thunks in
// Lugner_Winmm.asm and the "name = f<N>" map in ProxyWinmm.def.
static constexpr int kWinmmExportCount = 180;
extern "C" uintptr_t mProcs[kWinmmExportCount] = { 0 };

// Resolution is by NAME (version-robust: a name absent on some Windows
// build simply yields a null slot).
static const char* const kWinmmExports[kWinmmExportCount] = {
    "mciExecute",                    // f0 @3
    "CloseDriver",                   // f1 @4
    "DefDriverProc",                 // f2 @5
    "DriverCallback",                // f3 @6
    "DrvGetModuleHandle",            // f4 @7
    "GetDriverModuleHandle",         // f5 @8
    "OpenDriver",                    // f6 @9
    "PlaySound",                     // f7 @10
    "PlaySoundA",                    // f8 @11
    "PlaySoundW",                    // f9 @12
    "SendDriverMessage",             // f10 @13
    "WOWAppExit",                    // f11 @14
    "auxGetDevCapsA",                // f12 @15
    "auxGetDevCapsW",                // f13 @16
    "auxGetNumDevs",                 // f14 @17
    "auxGetVolume",                  // f15 @18
    "auxOutMessage",                 // f16 @19
    "auxSetVolume",                  // f17 @20
    "joyConfigChanged",              // f18 @21
    "joyGetDevCapsA",                // f19 @22
    "joyGetDevCapsW",                // f20 @23
    "joyGetNumDevs",                 // f21 @24
    "joyGetPos",                     // f22 @25
    "joyGetPosEx",                   // f23 @26
    "joyGetThreshold",               // f24 @27
    "joyReleaseCapture",             // f25 @28
    "joySetCapture",                 // f26 @29
    "joySetThreshold",               // f27 @30
    "mciDriverNotify",               // f28 @31
    "mciDriverYield",                // f29 @32
    "mciFreeCommandResource",        // f30 @33
    "mciGetCreatorTask",             // f31 @34
    "mciGetDeviceIDA",               // f32 @35
    "mciGetDeviceIDFromElementIDA",  // f33 @36
    "mciGetDeviceIDFromElementIDW",  // f34 @37
    "mciGetDeviceIDW",               // f35 @38
    "mciGetDriverData",              // f36 @39
    "mciGetErrorStringA",            // f37 @40
    "mciGetErrorStringW",            // f38 @41
    "mciGetYieldProc",               // f39 @42
    "mciLoadCommandResource",        // f40 @43
    "mciSendCommandA",               // f41 @44
    "mciSendCommandW",               // f42 @45
    "mciSendStringA",                // f43 @46
    "mciSendStringW",                // f44 @47
    "mciSetDriverData",              // f45 @48
    "mciSetYieldProc",               // f46 @49
    "midiConnect",                   // f47 @50
    "midiDisconnect",                // f48 @51
    "midiInAddBuffer",               // f49 @52
    "midiInClose",                   // f50 @53
    "midiInGetDevCapsA",             // f51 @54
    "midiInGetDevCapsW",             // f52 @55
    "midiInGetErrorTextA",           // f53 @56
    "midiInGetErrorTextW",           // f54 @57
    "midiInGetID",                   // f55 @58
    "midiInGetNumDevs",              // f56 @59
    "midiInMessage",                 // f57 @60
    "midiInOpen",                    // f58 @61
    "midiInPrepareHeader",           // f59 @62
    "midiInReset",                   // f60 @63
    "midiInStart",                   // f61 @64
    "midiInStop",                    // f62 @65
    "midiInUnprepareHeader",         // f63 @66
    "midiOutCacheDrumPatches",       // f64 @67
    "midiOutCachePatches",           // f65 @68
    "midiOutClose",                  // f66 @69
    "midiOutGetDevCapsA",            // f67 @70
    "midiOutGetDevCapsW",            // f68 @71
    "midiOutGetErrorTextA",          // f69 @72
    "midiOutGetErrorTextW",          // f70 @73
    "midiOutGetID",                  // f71 @74
    "midiOutGetNumDevs",             // f72 @75
    "midiOutGetVolume",              // f73 @76
    "midiOutLongMsg",                // f74 @77
    "midiOutMessage",                // f75 @78
    "midiOutOpen",                   // f76 @79
    "midiOutPrepareHeader",          // f77 @80
    "midiOutReset",                  // f78 @81
    "midiOutSetVolume",              // f79 @82
    "midiOutShortMsg",               // f80 @83
    "midiOutUnprepareHeader",        // f81 @84
    "midiStreamClose",               // f82 @85
    "midiStreamOpen",                // f83 @86
    "midiStreamOut",                 // f84 @87
    "midiStreamPause",               // f85 @88
    "midiStreamPosition",            // f86 @89
    "midiStreamProperty",            // f87 @90
    "midiStreamRestart",             // f88 @91
    "midiStreamStop",                // f89 @92
    "mixerClose",                    // f90 @93
    "mixerGetControlDetailsA",       // f91 @94
    "mixerGetControlDetailsW",       // f92 @95
    "mixerGetDevCapsA",              // f93 @96
    "mixerGetDevCapsW",              // f94 @97
    "mixerGetID",                    // f95 @98
    "mixerGetLineControlsA",         // f96 @99
    "mixerGetLineControlsW",         // f97 @100
    "mixerGetLineInfoA",             // f98 @101
    "mixerGetLineInfoW",             // f99 @102
    "mixerGetNumDevs",               // f100 @103
    "mixerMessage",                  // f101 @104
    "mixerOpen",                     // f102 @105
    "mixerSetControlDetails",        // f103 @106
    "mmDrvInstall",                  // f104 @107
    "mmGetCurrentTask",              // f105 @108
    "mmTaskBlock",                   // f106 @109
    "mmTaskCreate",                  // f107 @110
    "mmTaskSignal",                  // f108 @111
    "mmTaskYield",                   // f109 @112
    "mmioAdvance",                   // f110 @113
    "mmioAscend",                    // f111 @114
    "mmioClose",                     // f112 @115
    "mmioCreateChunk",               // f113 @116
    "mmioDescend",                   // f114 @117
    "mmioFlush",                     // f115 @118
    "mmioGetInfo",                   // f116 @119
    "mmioInstallIOProcA",            // f117 @120
    "mmioInstallIOProcW",            // f118 @121
    "mmioOpenA",                     // f119 @122
    "mmioOpenW",                     // f120 @123
    "mmioRead",                      // f121 @124
    "mmioRenameA",                   // f122 @125
    "mmioRenameW",                   // f123 @126
    "mmioSeek",                      // f124 @127
    "mmioSendMessage",               // f125 @128
    "mmioSetBuffer",                 // f126 @129
    "mmioSetInfo",                   // f127 @130
    "mmioStringToFOURCCA",           // f128 @131
    "mmioStringToFOURCCW",           // f129 @132
    "mmioWrite",                     // f130 @133
    "mmsystemGetVersion",            // f131 @134
    "sndPlaySoundA",                 // f132 @135
    "sndPlaySoundW",                 // f133 @136
    "timeBeginPeriod",               // f134 @137
    "timeEndPeriod",                 // f135 @138
    "timeGetDevCaps",                // f136 @139
    "timeGetSystemTime",             // f137 @140
    "timeGetTime",                   // f138 @141
    "timeKillEvent",                 // f139 @142
    "timeSetEvent",                  // f140 @143
    "waveInAddBuffer",               // f141 @144
    "waveInClose",                   // f142 @145
    "waveInGetDevCapsA",             // f143 @146
    "waveInGetDevCapsW",             // f144 @147
    "waveInGetErrorTextA",           // f145 @148
    "waveInGetErrorTextW",           // f146 @149
    "waveInGetID",                   // f147 @150
    "waveInGetNumDevs",              // f148 @151
    "waveInGetPosition",             // f149 @152
    "waveInMessage",                 // f150 @153
    "waveInOpen",                    // f151 @154
    "waveInPrepareHeader",           // f152 @155
    "waveInReset",                   // f153 @156
    "waveInStart",                   // f154 @157
    "waveInStop",                    // f155 @158
    "waveInUnprepareHeader",         // f156 @159
    "waveOutBreakLoop",              // f157 @160
    "waveOutClose",                  // f158 @161
    "waveOutGetDevCapsA",            // f159 @162
    "waveOutGetDevCapsW",            // f160 @163
    "waveOutGetErrorTextA",          // f161 @164
    "waveOutGetErrorTextW",          // f162 @165
    "waveOutGetID",                  // f163 @166
    "waveOutGetNumDevs",             // f164 @167
    "waveOutGetPitch",               // f165 @168
    "waveOutGetPlaybackRate",        // f166 @169
    "waveOutGetPosition",            // f167 @170
    "waveOutGetVolume",              // f168 @171
    "waveOutMessage",                // f169 @172
    "waveOutOpen",                   // f170 @173
    "waveOutPause",                  // f171 @174
    "waveOutPrepareHeader",          // f172 @175
    "waveOutReset",                  // f173 @176
    "waveOutRestart",                // f174 @177
    "waveOutSetPitch",               // f175 @178
    "waveOutSetPlaybackRate",        // f176 @179
    "waveOutSetVolume",              // f177 @180
    "waveOutUnprepareHeader",        // f178 @181
    "waveOutWrite",                  // f179 @182
};

// Populate mProcs from the real System32 winmm.dll, once, on the FIRST forwarded call.
//
// NO LOCK, deliberately (audit #4 B43). This used to hold an EXCLUSIVE SRWLOCK across
// LoadLibraryW AND a Sein log write. LoadLibraryW takes the loader lock, so a thunk
// reached from a foreign DllMain -- which already holds it -- inverts the lock order
// against any thread that took ours first. The dxgi original's safety argument was
// explicitly CONDITIONAL on RHI init being the only entry point; this generator was
// emitting that conclusion as a constant for every DLL, and it does not transfer --
// winmm's timeGetTime family is callable from any thread at any time.
//
// A lock is not needed for correctness. mProcs[] entries are pointer-sized and
// aligned, so a store cannot tear; two racing resolvers write IDENTICAL values (the
// same GetProcAddress results from the same module), so the work is idempotent and
// the worst case is doing it twice. What the lock DID buy -- nobody observes a
// half-populated table -- is preserved by the thunk itself, which tests its own slot
// and calls back here while it is still null.
//
// The 'spin until resolved' alternative is REJECTED and must stay rejected: a thread
// created from DllMain cannot start until the loader lock is released, so a spinning
// thunk would deadlock DETERMINISTICALLY, not occasionally.
extern "C" void WinmmProxy_EnsureResolved()
{
    // NO early-out gate either. A 'first caller wins, others return' check would let
    // the loser return with its slot STILL NULL, and the thunk's next instruction is
    // `jmp rax` -- an immediate AV at RIP=0. Racing resolvers are idempotent (same
    // module, same names, same addresses), so every caller simply does the work and
    // returns with the table populated. LoadLibraryW is refcounted; a duplicate is cheap.

    wchar_t realPath[MAX_PATH] = {};
    // false => refuse. The old code discarded GetSystemDirectoryW's return and formatted
    // an empty buffer into a drive-root-relative `\winmm.dll`. Refusing leaves mProcs
    // null, which the logging below already reports as 0/N resolved. (AD18)
    HMODULE real = Lugner::SystemDllPath(L"winmm.dll", realPath, MAX_PATH)
                 ? LoadLibraryW(realPath) : nullptr;
    int resolved = 0;
    if (real) {
        for (int i = 0; i < kWinmmExportCount; ++i) {
            mProcs[i] = reinterpret_cast<uintptr_t>(GetProcAddress(real, kWinmmExports[i]));
            if (mProcs[i]) ++resolved;
        }
    }

    // Logging is the ONE thing that should happen once -- it is file I/O, and a
    // duplicate line would misreport a race as two resolves. Claimed after the work,
    // never around it.
    static volatile LONG s_logged = 0;
    if (InterlockedCompareExchange(&s_logged, 1, 0) != 0) return;
    if (real) {
        LOG_INFO("winmm proxy: lazily forwarded %d/%d exports to real System32 winmm.dll",
                 resolved, kWinmmExportCount);
    } else {
        LOG_ERROR("winmm proxy: FAILED to load real System32 winmm.dll (err=%lu) -- forwarded calls will crash",
                  GetLastError());
    }
}

#endif // UE5_PROXY_WINMM_BUILD
