; ============================================================
; Lugner_Winmm.asm -- winmm.dll proxy forwarding thunks (x64 MASM)
;
; Each fN is a LAZY self-resolving trampoline:
;   - Fast path: jump through mProcs[N] (the real export address).
;   - First call (mProcs[N] == 0): call WinmmProxy_EnsureResolved,
;     preserving all argument registers, then jump.
;
; A bare `jmp` preserves every register / the stack / the return address,
; so it forwards a call of ANY signature transparently.
;
; The fN index order MUST stay in sync with:
;   - kWinmmExports[] in Lugner_Winmm.cpp
;   - the "name = fN @ordinal" map in ProxyWinmm.def
;
; Generated by scripts/gen_proxy_forwarders.py from the real
; System32 winmm.dll. DO NOT EDIT BY HAND -- re-run the generator.
; ============================================================

option casemap:none

.code

extern mProcs:QWORD
extern mResolveAttempted:QWORD
extern WinmmProxy_EnsureResolved:PROC

public f0, f1, f2, f3, f4, f5, f6, f7, f8, f9
public f10, f11, f12, f13, f14, f15, f16, f17, f18, f19
public f20, f21, f22, f23, f24, f25, f26, f27, f28, f29
public f30, f31, f32, f33, f34, f35, f36, f37, f38, f39
public f40, f41, f42, f43, f44, f45, f46, f47, f48, f49
public f50, f51, f52, f53, f54, f55, f56, f57, f58, f59
public f60, f61, f62, f63, f64, f65, f66, f67, f68, f69
public f70, f71, f72, f73, f74, f75, f76, f77, f78, f79
public f80, f81, f82, f83, f84, f85, f86, f87, f88, f89
public f90, f91, f92, f93, f94, f95, f96, f97, f98, f99
public f100, f101, f102, f103, f104, f105, f106, f107, f108, f109
public f110, f111, f112, f113, f114, f115, f116, f117, f118, f119
public f120, f121, f122, f123, f124, f125, f126, f127, f128, f129
public f130, f131, f132, f133, f134, f135, f136, f137, f138, f139
public f140, f141, f142, f143, f144, f145, f146, f147, f148, f149
public f150, f151, f152, f153, f154, f155, f156, f157, f158, f159
public f160, f161, f162, f163, f164, f165, f166, f167, f168, f169
public f170, f171, f172, f173, f174, f175, f176, f177, f178, f179

; One-time resolver detour -- preserves every register that could carry a
; forwarded argument (RCX/RDX/R8/R9 + XMM0-3).
ResolveAll proc
    push rcx
    push rdx
    push r8
    push r9
    sub  rsp, 64
    movups [rsp+0],  xmm0
    movups [rsp+16], xmm1
    movups [rsp+32], xmm2
    movups [rsp+48], xmm3
    sub  rsp, 32                       ; shadow space (RSP stays 16-aligned)
    call WinmmProxy_EnsureResolved
    add  rsp, 32
    movups xmm0, [rsp+0]
    movups xmm1, [rsp+16]
    movups xmm2, [rsp+32]
    movups xmm3, [rsp+48]
    add  rsp, 64
    pop  r9
    pop  r8
    pop  rdx
    pop  rcx
    ret
ResolveAll endp

; fN: jump through mProcs[N]; on first use (mProcs[N]==0) resolve, then jump.
;
; A slot that is STILL null after ResolveAll has two very different causes, and they
; get two different answers. Collapsing them EITHER way is a real defect that has
; already been paid for once in each direction.
;
;   mResolveAttempted == 0  The resolver REFUSED: our CRT was not initialised yet,
;                           because Windows' AppCompat shim engine called this export
;                           from apphelp!SE_DllLoaded -- after our module was mapped,
;                           before _DllMainCRTStartup ran. Answer 0 and do NOT forward.
;                           Nothing is latched, so the host's own first call resolves
;                           normally. Without this test the thunk fell through to
;                           `jmp rax` with rax == 0 and the process died during loader
;                           init -- see docs/audit-2026-08-26-dxgi-appcompat-crash.md.
;
;   mResolveAttempted == 1  The resolver ran and this NAME is genuinely absent from the
;                           host System32 DLL. Fall through to `jmp rax` with rax == 0 --
;                           a loud crash, ON PURPOSE, and this half must stay. A stub
;                           returning 0 would be worse for winmm, where
;                           0 == TIMERR_NOERROR, so a missing timeBeginPeriod would
;                           SILENTLY no-op the 1 ms tick instead of saying anything
;                           (dll/CMakeLists.txt records the same rejection).
;
; The upstream defence against the second case is in this file's generator: it asserts
; the source DLL is a 64-bit PE. A 32-bit Python run used to read the SysWOW64 copy via
; WOW64 redirection and emit permanently-null slots pointing straight at that `jmp`,
; with a build that stayed internally consistent. (B44 / B48)
LAZY_THUNK macro idx
f&idx& proc
    mov  rax, qword ptr mProcs[8*idx]
    test rax, rax
    jnz  f&idx&_ready
    call ResolveAll
    mov  rax, qword ptr mProcs[8*idx]
    test rax, rax
    jnz  f&idx&_ready
    cmp  qword ptr mResolveAttempted, 0   ; does not touch rax
    jne  f&idx&_ready                     ; resolver ran -> genuinely absent -> jmp 0, loudly
    xor  eax, eax                         ; resolver refused (pre-CRT) -> answer 0, no forward
    ret
f&idx&_ready:
    jmp  rax
f&idx& endp
endm

    LAZY_THUNK 0
    LAZY_THUNK 1
    LAZY_THUNK 2
    LAZY_THUNK 3
    LAZY_THUNK 4
    LAZY_THUNK 5
    LAZY_THUNK 6
    LAZY_THUNK 7
    LAZY_THUNK 8
    LAZY_THUNK 9
    LAZY_THUNK 10
    LAZY_THUNK 11
    LAZY_THUNK 12
    LAZY_THUNK 13
    LAZY_THUNK 14
    LAZY_THUNK 15
    LAZY_THUNK 16
    LAZY_THUNK 17
    LAZY_THUNK 18
    LAZY_THUNK 19
    LAZY_THUNK 20
    LAZY_THUNK 21
    LAZY_THUNK 22
    LAZY_THUNK 23
    LAZY_THUNK 24
    LAZY_THUNK 25
    LAZY_THUNK 26
    LAZY_THUNK 27
    LAZY_THUNK 28
    LAZY_THUNK 29
    LAZY_THUNK 30
    LAZY_THUNK 31
    LAZY_THUNK 32
    LAZY_THUNK 33
    LAZY_THUNK 34
    LAZY_THUNK 35
    LAZY_THUNK 36
    LAZY_THUNK 37
    LAZY_THUNK 38
    LAZY_THUNK 39
    LAZY_THUNK 40
    LAZY_THUNK 41
    LAZY_THUNK 42
    LAZY_THUNK 43
    LAZY_THUNK 44
    LAZY_THUNK 45
    LAZY_THUNK 46
    LAZY_THUNK 47
    LAZY_THUNK 48
    LAZY_THUNK 49
    LAZY_THUNK 50
    LAZY_THUNK 51
    LAZY_THUNK 52
    LAZY_THUNK 53
    LAZY_THUNK 54
    LAZY_THUNK 55
    LAZY_THUNK 56
    LAZY_THUNK 57
    LAZY_THUNK 58
    LAZY_THUNK 59
    LAZY_THUNK 60
    LAZY_THUNK 61
    LAZY_THUNK 62
    LAZY_THUNK 63
    LAZY_THUNK 64
    LAZY_THUNK 65
    LAZY_THUNK 66
    LAZY_THUNK 67
    LAZY_THUNK 68
    LAZY_THUNK 69
    LAZY_THUNK 70
    LAZY_THUNK 71
    LAZY_THUNK 72
    LAZY_THUNK 73
    LAZY_THUNK 74
    LAZY_THUNK 75
    LAZY_THUNK 76
    LAZY_THUNK 77
    LAZY_THUNK 78
    LAZY_THUNK 79
    LAZY_THUNK 80
    LAZY_THUNK 81
    LAZY_THUNK 82
    LAZY_THUNK 83
    LAZY_THUNK 84
    LAZY_THUNK 85
    LAZY_THUNK 86
    LAZY_THUNK 87
    LAZY_THUNK 88
    LAZY_THUNK 89
    LAZY_THUNK 90
    LAZY_THUNK 91
    LAZY_THUNK 92
    LAZY_THUNK 93
    LAZY_THUNK 94
    LAZY_THUNK 95
    LAZY_THUNK 96
    LAZY_THUNK 97
    LAZY_THUNK 98
    LAZY_THUNK 99
    LAZY_THUNK 100
    LAZY_THUNK 101
    LAZY_THUNK 102
    LAZY_THUNK 103
    LAZY_THUNK 104
    LAZY_THUNK 105
    LAZY_THUNK 106
    LAZY_THUNK 107
    LAZY_THUNK 108
    LAZY_THUNK 109
    LAZY_THUNK 110
    LAZY_THUNK 111
    LAZY_THUNK 112
    LAZY_THUNK 113
    LAZY_THUNK 114
    LAZY_THUNK 115
    LAZY_THUNK 116
    LAZY_THUNK 117
    LAZY_THUNK 118
    LAZY_THUNK 119
    LAZY_THUNK 120
    LAZY_THUNK 121
    LAZY_THUNK 122
    LAZY_THUNK 123
    LAZY_THUNK 124
    LAZY_THUNK 125
    LAZY_THUNK 126
    LAZY_THUNK 127
    LAZY_THUNK 128
    LAZY_THUNK 129
    LAZY_THUNK 130
    LAZY_THUNK 131
    LAZY_THUNK 132
    LAZY_THUNK 133
    LAZY_THUNK 134
    LAZY_THUNK 135
    LAZY_THUNK 136
    LAZY_THUNK 137
    LAZY_THUNK 138
    LAZY_THUNK 139
    LAZY_THUNK 140
    LAZY_THUNK 141
    LAZY_THUNK 142
    LAZY_THUNK 143
    LAZY_THUNK 144
    LAZY_THUNK 145
    LAZY_THUNK 146
    LAZY_THUNK 147
    LAZY_THUNK 148
    LAZY_THUNK 149
    LAZY_THUNK 150
    LAZY_THUNK 151
    LAZY_THUNK 152
    LAZY_THUNK 153
    LAZY_THUNK 154
    LAZY_THUNK 155
    LAZY_THUNK 156
    LAZY_THUNK 157
    LAZY_THUNK 158
    LAZY_THUNK 159
    LAZY_THUNK 160
    LAZY_THUNK 161
    LAZY_THUNK 162
    LAZY_THUNK 163
    LAZY_THUNK 164
    LAZY_THUNK 165
    LAZY_THUNK 166
    LAZY_THUNK 167
    LAZY_THUNK 168
    LAZY_THUNK 169
    LAZY_THUNK 170
    LAZY_THUNK 171
    LAZY_THUNK 172
    LAZY_THUNK 173
    LAZY_THUNK 174
    LAZY_THUNK 175
    LAZY_THUNK 176
    LAZY_THUNK 177
    LAZY_THUNK 178
    LAZY_THUNK 179

end
