"""Generate a forwarding-proxy trio (.cpp / .asm / .def) from a real system DLL.

The 4th-proxy evaluation in docs/todo.md set the rule this implements: with 180
exports, winmm must NOT be hand-written. This reads the export table of the real
System32 DLL and emits the same three artefacts the dxgi proxy uses, in the same
shapes, so the two flavours cannot drift apart by hand-editing.

Emits, for <name>:
  dll/src/Lugner_<Name>.cpp   -- mProcs[] + the export-name table + the lazy
                                 System32 resolver
  dll/src/Lugner_<Name>.asm   -- MASM lazy jmp-thunks f0..fN-1
  dll/src/Proxy<Name>.def     -- "export = fN @ordinal" + our UE5_* C ABI

Why jmp-thunks rather than C forwarders: a bare `jmp` preserves every register,
the stack and the return address, so it forwards a call of ANY signature
transparently. That matters because a system DLL's export table contains
undocumented internals whose prototypes we do not know -- true of dxgi, and of
winmm's driver/MCI internals.

Why lazy: resolving in DllMain would run LoadLibrary under the loader lock while
the EXE's static imports are still initialising. That crashed Octopath Traveler
via the dxgi proxy (see the header comment in Lugner_Dxgi.asm). The first
forwarded call happens on a game thread after DllMain returns, which is the safe
place.

ORDINAL-ONLY exports are skipped and reported: a game that imports the proxied
DLL by ordinal rather than by name would miss them. winmm has exactly one, an
internal, which no game imports.

Usage:
    python scripts/gen_proxy_forwarders.py winmm
    python scripts/gen_proxy_forwarders.py winmm --check   # verify, write nothing
"""
import argparse
import os
import struct
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO, "dll", "src")


# ── PE export-table reader ───────────────────────────────────────────────

def read_exports(path):
    """Return (named, skipped_ordinals): named = [(name, ordinal), ...]."""
    with open(path, "rb") as fh:
        d = fh.read()
    pe = struct.unpack_from("<I", d, 0x3C)[0]
    magic = struct.unpack_from("<H", d, pe + 24)[0]
    machine = struct.unpack_from("<H", d, pe + 4)[0]
    # Refuse a 32-bit source outright. This function happily parses PE32, and the
    # generated files would build and link clean — but they would be WRONG in a way
    # nothing downstream can detect. Measured on this machine: System32 winmm.dll has
    # 180 named exports, SysWOW64 has 192; 12 are x86-only, and 174 shared names sit at
    # DIFFERENT ordinals. A 32-bit Python run therefore emits 12 permanently-null lazy
    # thunks (each one a `jmp rax` with rax==0 — see Lugner_Winmm.asm) plus a
    # wholesale-wrong @ordinal map, and the build stays internally consistent. (B48)
    if magic != 0x20B or machine != 0x8664:
        raise RuntimeError(
            f"{path} is not a 64-bit PE (magic=0x{magic:X}, machine=0x{machine:04X}); "
            "expected magic=0x20B machine=0x8664. Under 32-bit Python, WOW64 redirects "
            r"%SystemRoot%\System32 to SysWOW64 — re-run with 64-bit Python."
        )
    dd = pe + 24 + (112 if magic == 0x20B else 96)
    nsec = struct.unpack_from("<H", d, pe + 6)[0]
    so = pe + 24 + struct.unpack_from("<H", d, pe + 20)[0]
    secs = [(struct.unpack_from("<I", d, so + i * 40 + 12)[0],
             max(struct.unpack_from("<I", d, so + i * 40 + 8)[0], 1),
             struct.unpack_from("<I", d, so + i * 40 + 20)[0]) for i in range(nsec)]

    def rva2off(r):
        for va, vs, pr in secs:
            if va <= r < va + vs:
                return pr + (r - va)
        return None

    exp_rva = struct.unpack_from("<I", d, dd)[0]
    off = rva2off(exp_rva)
    if off is None:
        raise RuntimeError("no export directory")

    base = struct.unpack_from("<I", d, off + 16)[0]
    n_func, n_name = struct.unpack_from("<II", d, off + 20)
    addr_rva, name_rva, ord_rva = struct.unpack_from("<III", d, off + 28)
    a_off, n_off, o_off = rva2off(addr_rva), rva2off(name_rva), rva2off(ord_rva)

    named_by_index = {}
    for i in range(n_name):
        nr = struct.unpack_from("<I", d, n_off + i * 4)[0]
        no = rva2off(nr)
        nm = d[no:d.index(b"\0", no)].decode("ascii")
        idx = struct.unpack_from("<H", d, o_off + i * 2)[0]
        named_by_index[idx] = nm

    named, skipped = [], []
    for i in range(n_func):
        fn_rva = struct.unpack_from("<I", d, a_off + i * 4)[0]
        if fn_rva == 0:
            continue                      # gap in the ordinal space
        ordinal = base + i
        if i in named_by_index:
            named.append((named_by_index[i], ordinal))
        else:
            skipped.append(ordinal)
    named.sort(key=lambda t: t[1])
    return named, skipped


# ── Emitters ─────────────────────────────────────────────────────────────

BANNER = ("// Generated by scripts/gen_proxy_forwarders.py from the real\n"
          "// System32 {dll}. DO NOT EDIT BY HAND -- re-run the generator.\n")


def emit_cpp(name, dll, exports):
    up, low = name.upper(), name.lower()
    lines = [
        "// ============================================================",
        f"// Lugner_{name} -- {dll} forwarding proxy (data + resolver half)",
        "//",
        f"// Compiled only for UE5_PROXY_{up}_BUILD. Resolves the real {dll}",
        f"// exports from System32 into mProcs[], which the asm jmp-thunks in",
        f"// Lugner_{name}.asm jump through. Proxy{name}.def maps each Windows",
        "// export name to its thunk.",
        "//",
        "// Forwarding goes through signature-agnostic asm jmp trampolines rather",
        "// than C forwarders: a bare jmp preserves every register, the stack and",
        f"// the return address, so it forwards a call of ANY signature. {dll}",
        "// exports undocumented internals whose prototypes we do not know.",
        "//",
        "// LAZY resolution -- the real exports are resolved on the FIRST forwarded",
        "// call, NOT eagerly in DllMain. Resolving in DllMain would LoadLibrary",
        "// under the loader lock while the EXE's static imports are still being",
        "// initialised; that crashed Octopath Traveler through the dxgi proxy. The",
        "// first forwarded call runs on a game thread after DllMain returns.",
        "//",
        BANNER.format(dll=dll).rstrip(),
        "// ============================================================",
        "",
        f"#ifdef UE5_PROXY_{up}_BUILD",
        "",
        "#include <Windows.h>",
        "#include <cstdint>",
        '#define LOG_CAT "PROXY"',
        '#include "Sein.h"',
        '#include "Lugner.h"',
        "",
        f"// Real {dll} export addresses, indexed to match the f<N> thunks in",
        f"// Lugner_{name}.asm and the \"name = f<N>\" map in Proxy{name}.def.",
        f"static constexpr int k{name}ExportCount = {len(exports)};",
        f"extern \"C\" uintptr_t mProcs[k{name}ExportCount] = {{ 0 }};",
        "",
        "// 1 once the resolver has actually ATTEMPTED resolution (whether or not the real DLL",
        "// loaded). Read by the asm thunks, which need to tell two very different reasons a slot",
        "// can be null apart:",
        "//",
        "//   mResolveAttempted == 0 -> the resolver REFUSED because our CRT was not up yet",
        "//                             (Lugner::CrtReady() false). The thunk answers 0 without",
        "//                             forwarding; the next call after DllMain resolves normally.",
        "//   mResolveAttempted == 1 -> the resolver ran and this NAME is genuinely absent from the",
        "//                             host System32 DLL. The thunk keeps the deliberate loud",
        "//                             `jmp rax` with rax == 0 -- see Lugner_" + f"{name}" + ".asm for why a",
        "//                             stub returning 0 is worse here. Do NOT collapse these.",
        "//",
        "// Plain uintptr_t, constant-initialised, so it lives in zero-filled .data and is readable",
        "// before the CRT exists -- same requirement as Lugner::g_crtReady.",
        "extern \"C\" uintptr_t mResolveAttempted = 0;",
        "",
        "// Resolution is by NAME (version-robust: a name absent on some Windows",
        "// build simply yields a null slot).",
        f"static const char* const k{name}Exports[k{name}ExportCount] = {{",
    ]
    width = max(len(n) for n, _ in exports) + 3
    for i, (n, o) in enumerate(exports):
        lines.append(f'    "{n}",'.ljust(width + 6) + f"// f{i} @{o}")
    lines += [
        "};",
        "",
        f"// Populate mProcs from the real System32 {dll}, once, on the FIRST forwarded call.",
        "//",
        "// NO LOCK, deliberately (audit #4 B43). This used to hold an EXCLUSIVE SRWLOCK across",
        "// LoadLibraryW AND a Sein log write. LoadLibraryW takes the loader lock, so a thunk",
        "// reached from a foreign DllMain -- which already holds it -- inverts the lock order",
        "// against any thread that took ours first. The dxgi original's safety argument was",
        "// explicitly CONDITIONAL on RHI init being the only entry point; this generator was",
        "// emitting that conclusion as a constant for every DLL, and it does not transfer --",
        "// winmm's timeGetTime family is callable from any thread at any time.",
        "//",
        "// A lock is not needed for correctness. mProcs[] entries are pointer-sized and",
        "// aligned, so a store cannot tear; two racing resolvers write IDENTICAL values (the",
        "// same GetProcAddress results from the same module), so the work is idempotent and",
        "// the worst case is doing it twice. What the lock DID buy -- nobody observes a",
        "// half-populated table -- is preserved by the thunk itself, which tests its own slot",
        "// and calls back here while it is still null.",
        "//",
        "// The 'spin until resolved' alternative is REJECTED and must stay rejected: a thread",
        "// created from DllMain cannot start until the loader lock is released, so a spinning",
        "// thunk would deadlock DETERMINISTICALLY, not occasionally.",
        f'extern "C" void {name}Proxy_EnsureResolved()',
        "{",
        "    // PRE-CRT GATE -- the first thing, before anything that could allocate or take the",
        "    // loader lock. Windows' AppCompat shim engine calls a proxied export from",
        "    // apphelp!SE_DllLoaded, i.e. after our module is MAPPED but before",
        "    // _DllMainCRTStartup has run: LoadLibraryW would recurse into a still-held loader",
        "    // lock and LOG_* would malloc on a heap that does not exist yet",
        "    // (HeapAlloc(NULL, ...) -> AV in ntdll!RtlAllocateHeap). Returning leaves mProcs[]",
        "    // null and mResolveAttempted 0, which the thunk reads as 'answer 0, do not forward'.",
        "    // Nothing is latched, so the host's own first call resolves normally.",
        "    // See docs/audit-2026-08-26-dxgi-appcompat-crash.md.",
        "    if (!Lugner::CrtReady()) { Lugner::NotePreCrtCall(); return; }",
        "",
        "    // NO early-out gate beyond that one. A 'first caller wins, others return' check would",
        "    // let the loser return with its slot STILL NULL. Racing resolvers are idempotent (same",
        "    // module, same names, same addresses), so every caller simply does the work and",
        "    // returns with the table populated. LoadLibraryW is refcounted; a duplicate is cheap.",
        "",
        "    wchar_t realPath[MAX_PATH] = {};",
        "    // false => refuse. The old code discarded GetSystemDirectoryW's return and formatted",
        f"    // an empty buffer into a drive-root-relative `\\{dll}`. Refusing leaves mProcs",
        "    // null, which the logging below already reports as 0/N resolved. (AD18)",
        f'    HMODULE real = Lugner::SystemDllPath(L"{dll}", realPath, MAX_PATH)',
        "                 ? LoadLibraryW(realPath) : nullptr;",
        "    // Captured AT the failure, before GetProcAddress/logging clobber it. (AB10/AB11)",
        "    const DWORD loadErr = real ? 0 : GetLastError();",
        "    int resolved = 0;",
        "    if (real) {",
        f"        for (int i = 0; i < k{name}ExportCount; ++i) {{",
        f"            mProcs[i] = reinterpret_cast<uintptr_t>(GetProcAddress(real, k{name}Exports[i]));",
        "            if (mProcs[i]) ++resolved;",
        "        }",
        "    }",
        "    // Published only after mProcs[] is fully written, so no thunk observes",
        "    // 'resolution finished' over a half-filled table.",
        "    mResolveAttempted = 1;",
        "",
        "    // Logging is the ONE thing that should happen once -- it is file I/O, and a",
        "    // duplicate line would misreport a race as two resolves. Claimed after the work,",
        "    // never around it.",
        "    static volatile LONG s_logged = 0;",
        "    if (InterlockedCompareExchange(&s_logged, 1, 0) != 0) return;",
        "    if (real) {",
        f'        LOG_INFO("{low} proxy: lazily forwarded %d/%d exports to real System32 {dll}",',
        f"                 resolved, k{name}ExportCount);",
        "    } else {",
        f'        LOG_ERROR("{low} proxy: FAILED to load real System32 {dll} (err=%lu) '
        '-- forwarded calls will crash",',
        "                  loadErr);",
        "    }",
        "}",
        "",
        f"#endif // UE5_PROXY_{up}_BUILD",
        "",
    ]
    return "\n".join(lines)


def emit_asm(name, dll, count):
    pub = []
    for i in range(0, count, 10):
        pub.append("public " + ", ".join(f"f{j}" for j in range(i, min(i + 10, count))))
    lines = [
        "; ============================================================",
        f"; Lugner_{name}.asm -- {dll} proxy forwarding thunks (x64 MASM)",
        ";",
        "; Each fN is a LAZY self-resolving trampoline:",
        ";   - Fast path: jump through mProcs[N] (the real export address).",
        f";   - First call (mProcs[N] == 0): call {name}Proxy_EnsureResolved,",
        ";     preserving all argument registers, then jump.",
        ";",
        "; A bare `jmp` preserves every register / the stack / the return address,",
        "; so it forwards a call of ANY signature transparently.",
        ";",
        "; The fN index order MUST stay in sync with:",
        f";   - k{name}Exports[] in Lugner_{name}.cpp",
        f";   - the \"name = fN @ordinal\" map in Proxy{name}.def",
        ";",
        BANNER.format(dll=dll).replace("//", ";").rstrip(),
        "; ============================================================",
        "",
        "option casemap:none",
        "",
        ".code",
        "",
        "extern mProcs:QWORD",
        "extern mResolveAttempted:QWORD",
        f"extern {name}Proxy_EnsureResolved:PROC",
        "",
    ]
    lines += pub
    lines += [
        "",
        "; One-time resolver detour -- preserves every register that could carry a",
        "; forwarded argument (RCX/RDX/R8/R9 + XMM0-3).",
        "ResolveAll proc",
        "    push rcx",
        "    push rdx",
        "    push r8",
        "    push r9",
        "    sub  rsp, 64",
        "    movups [rsp+0],  xmm0",
        "    movups [rsp+16], xmm1",
        "    movups [rsp+32], xmm2",
        "    movups [rsp+48], xmm3",
        "    sub  rsp, 32                       ; shadow space (RSP stays 16-aligned)",
        f"    call {name}Proxy_EnsureResolved",
        "    add  rsp, 32",
        "    movups xmm0, [rsp+0]",
        "    movups xmm1, [rsp+16]",
        "    movups xmm2, [rsp+32]",
        "    movups xmm3, [rsp+48]",
        "    add  rsp, 64",
        "    pop  r9",
        "    pop  r8",
        "    pop  rdx",
        "    pop  rcx",
        "    ret",
        "ResolveAll endp",
        "",
        "; fN: jump through mProcs[N]; on first use (mProcs[N]==0) resolve, then jump.",
        ";",
        "; A slot that is STILL null after ResolveAll has two very different causes, and they",
        "; get two different answers. Collapsing them EITHER way is a real defect that has",
        "; already been paid for once in each direction.",
        ";",
        ";   mResolveAttempted == 0  The resolver REFUSED: our CRT was not initialised yet,",
        ";                           because Windows' AppCompat shim engine called this export",
        ";                           from apphelp!SE_DllLoaded -- after our module was mapped,",
        ";                           before _DllMainCRTStartup ran. Answer 0 and do NOT forward.",
        ";                           Nothing is latched, so the host's own first call resolves",
        ";                           normally. Without this test the thunk fell through to",
        ";                           `jmp rax` with rax == 0 and the process died during loader",
        ";                           init -- see docs/audit-2026-08-26-dxgi-appcompat-crash.md.",
        ";",
        ";   mResolveAttempted == 1  The resolver ran and this NAME is genuinely absent from the",
        ";                           host System32 DLL. Fall through to `jmp rax` with rax == 0 --",
        ";                           a loud crash, ON PURPOSE, and this half must stay. A stub",
        ";                           returning 0 would be worse for winmm, where",
        ";                           0 == TIMERR_NOERROR, so a missing timeBeginPeriod would",
        ";                           SILENTLY no-op the 1 ms tick instead of saying anything",
        ";                           (dll/CMakeLists.txt records the same rejection).",
        ";",
        "; The upstream defence against the second case is in this file's generator: it asserts",
        "; the source DLL is a 64-bit PE. A 32-bit Python run used to read the SysWOW64 copy via",
        "; WOW64 redirection and emit permanently-null slots pointing straight at that `jmp`,",
        "; with a build that stayed internally consistent. (B44 / B48)",
        "LAZY_THUNK macro idx",
        "f&idx& proc",
        "    mov  rax, qword ptr mProcs[8*idx]",
        "    test rax, rax",
        "    jnz  f&idx&_ready",
        "    call ResolveAll",
        "    mov  rax, qword ptr mProcs[8*idx]",
        "    test rax, rax",
        "    jnz  f&idx&_ready",
        "    cmp  qword ptr mResolveAttempted, 0   ; does not touch rax",
        "    jne  f&idx&_ready                     ; resolver ran -> genuinely absent -> jmp 0, loudly",
        "    xor  eax, eax                         ; resolver refused (pre-CRT) -> answer 0, no forward",
        "    ret",
        "f&idx&_ready:",
        "    jmp  rax",
        "f&idx& endp",
        "endm",
        "",
    ]
    lines += [f"    LAZY_THUNK {i}" for i in range(count)]
    lines += ["", "end", ""]
    return "\n".join(lines)


def emit_def(name, dll, exports, ue5_exports):
    width = max(len(n) for n, _ in exports) + 2
    lines = [
        "; ============================================================",
        f"; Proxy{name}.def -- Module definition for the {dll} proxy",
        ";",
        f"; Maps each Windows {dll} export name to its asm jmp thunk, and",
        "; re-exports our UE5 C ABI so CE Lua's getAddress() can resolve the",
        "; dumper functions through the proxy DLL.",
        ";",
        "; The @ordinals are mandatory, not decoration: link.exe hands UNPINNED",
        "; exports out in name-sorted order starting at (highest PINNED ordinal",
        "; + 1), so an unpinned forwarding block lets our UE5_* symbols land on",
        "; real ordinals and an ordinal import then calls the wrong function.",
        "; Pinning the whole real range keeps ours above it automatically.",
        "; tools/check_proxy_exports.py re-derives every pin. (Audit PX1.)",
        ";",
        "; The UE5_* block below is listed for CE Lua's getAddress(), not because",
        "; /DEF: would otherwise hide it: /DEF: MERGES with __declspec(dllexport)",
        "; rather than suppressing it. Conversely a line here exports nothing on",
        "; its own -- it needs an implementation to bind to.",
        ";",
        BANNER.format(dll=dll).replace("//", ";").rstrip(),
        "; ============================================================",
        "",
        # LIBRARY sets IMAGE_EXPORT_DIRECTORY.Name -- what the module reports as
        # its own name. Windows resolves the proxy by on-disk filename, but a
        # wrong name here misleads any tool that reports module identity.
        f"LIBRARY {name.lower()}",
        "EXPORTS",
        f"    ; --- Windows {dll} forwarding (export = asm thunk @ real-ordinal) ---",
    ]
    for i, (n, o) in enumerate(exports):
        lines.append(f"    {n.ljust(width)}= f{i} @{o}")
    lines += ["", "    ; --- UE5CEDumper C ABI (unchanged from the other proxies) ---"]
    lines += [f"    {e}" for e in ue5_exports]
    lines.append("")
    return "\n".join(lines)


def ue5_export_list():
    """Reuse ProxyDxgi.def's UE5_* block so all proxies export the same ABI."""
    path = os.path.join(SRC, "ProxyDxgi.def")
    out, seen_ue5 = [], False
    for line in open(path, encoding="utf-8"):
        s = line.strip()
        # LIBRARY names the module; it is per-proxy and emit_def writes its own.
        # Harvesting dxgi's would plant "LIBRARY dxgi" inside the generated
        # EXPORTS block, making the built DLL report dxgi.dll as its own name.
        if (not s or s.startswith(";") or s == "EXPORTS"
                or s.upper().startswith("LIBRARY")):
            continue
        if "=" in s:            # a forwarding entry, not ours
            continue
        seen_ue5 = True
        out.append(s)
    if not seen_ue5:
        raise RuntimeError("no UE5_* exports found in ProxyDxgi.def")
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("name", help="system DLL base name, e.g. winmm")
    ap.add_argument("--check", action="store_true", help="verify only; write nothing")
    args = ap.parse_args()

    low = args.name.lower()
    cap = low.capitalize()
    dll = low + ".dll"
    # Under 32-bit Python, WOW64 silently redirects System32 -> SysWOW64. `Sysnative`
    # is the documented escape hatch that reaches the REAL 64-bit System32 from a
    # 32-bit process; it does not exist for 64-bit processes, hence the conditional.
    # read_exports asserts the result anyway — this just makes the common case work
    # instead of only failing loudly. (B48)
    sysroot = os.environ.get("SystemRoot", r"C:\Windows")
    sysdir = "Sysnative" if sys.maxsize < 2 ** 32 else "System32"
    real = os.path.join(sysroot, sysdir, dll)
    print(f"host python: {8 * struct.calcsize('P')}-bit -> reading {real}")

    exports, skipped = read_exports(real)
    print(f"{dll}: {len(exports)} named exports"
          + (f", {len(skipped)} ordinal-only SKIPPED: {skipped}" if skipped else ""))

    files = {
        f"Lugner_{cap}.cpp": emit_cpp(cap, dll, exports),
        f"Lugner_{cap}.asm": emit_asm(cap, dll, len(exports)),
        f"Proxy{cap}.def":   emit_def(cap, dll, exports, ue5_export_list()),
    }

    rc = 0
    for fn, text in files.items():
        path = os.path.join(SRC, fn)
        if args.check:
            cur = open(path, encoding="utf-8").read() if os.path.exists(path) else None
            state = "OK" if cur == text else "STALE/MISSING"
            if cur != text:
                rc = 1
            print(f"  {fn:24s} {state}")
        else:
            with open(path, "w", encoding="utf-8", newline="\n") as fh:
                fh.write(text)
            print(f"  wrote {fn} ({len(text.splitlines())} lines)")
    return rc


if __name__ == "__main__":
    sys.exit(main())
